-- Infinite Dungeon (Donjon infini) creatures: copies of stock dungeon creatures under their own entries, so the
-- stock ones stay untouched. Generated by localTools/infiniteDungeon/buildArenas.py.
-- A copy keeps its model, weapons, movement and French name; the floor sets its level, health and damage
-- (InfiniteDungeon.cpp). No loot, no experience (the floor pays), our script, rank by role: trash normal, elite
-- and boss elite, the boss with the boss portrait (type flag 4).

DELETE FROM `creature_template_locale` WHERE `entry` BETWEEN 920010 AND 920299;
DELETE FROM `creature_template_movement` WHERE `CreatureId` BETWEEN 920010 AND 920299;
DELETE FROM `creature_equip_template` WHERE `CreatureID` BETWEEN 920010 AND 920299;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 920010 AND 920299;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 920010 AND 920299;

DROP TEMPORARY TABLE IF EXISTS `tmp_infinite_dungeon_copy`;
CREATE TEMPORARY TABLE `tmp_infinite_dungeon_copy` (
    `entry` INT UNSIGNED NOT NULL,
    `source` INT UNSIGNED NOT NULL,
    `role` TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (`entry`)
) ENGINE=InnoDB;
INSERT INTO `tmp_infinite_dungeon_copy` (`entry`, `source`, `role`) VALUES
    (920010, 1731, 0), -- trash
    (920011, 622, 0), -- trash
    (920012, 4416, 0), -- trash
    (920013, 4417, 1), -- elite
    (920014, 1763, 2), -- boss
    (920015, 657, 0), -- trash
    (920016, 1732, 0), -- trash
    (920017, 636, 1), -- elite
    (920018, 647, 2), -- boss
    (920019, 3877, 0), -- trash
    (920020, 3875, 0), -- trash
    (920021, 3857, 1), -- elite
    (920022, 4278, 2), -- boss
    (920023, 3853, 0), -- trash
    (920024, 3864, 1), -- elite
    (920025, 3886, 2), -- boss
    (920026, 4306, 0), -- trash
    (920027, 4283, 0), -- trash
    (920028, 4540, 1), -- elite
    (920029, 3983, 2), -- boss
    (920030, 7309, 0), -- trash
    (920031, 7077, 0), -- trash
    (920032, 7076, 0), -- trash
    (920033, 10120, 1), -- elite
    (920034, 2748, 2), -- boss
    (920035, 4851, 0), -- trash
    (920036, 4852, 0), -- trash
    (920037, 4850, 1), -- elite
    (920038, 6910, 2), -- boss
    (920039, 5649, 0), -- trash
    (920040, 7247, 0), -- trash
    (920041, 5650, 0), -- trash
    (920042, 7246, 1), -- elite
    (920043, 7272, 2), -- boss
    (920044, 8095, 1), -- elite
    (920045, 7795, 2), -- boss
    (920046, 11792, 0), -- trash
    (920047, 11791, 0), -- trash
    (920048, 12217, 1), -- elite
    (920049, 12236, 2), -- boss
    (920050, 9545, 0), -- trash
    (920051, 9547, 0), -- trash
    (920052, 9554, 0), -- trash
    (920053, 9541, 1), -- elite
    (920054, 9537, 2), -- boss
    (920055, 8892, 0), -- trash
    (920056, 8891, 0), -- trash
    (920057, 8921, 0), -- trash
    (920058, 8909, 1), -- elite
    (920059, 9025, 2), -- boss
    (920060, 10390, 0), -- trash
    (920061, 10391, 0), -- trash
    (920062, 10405, 0), -- trash
    (920063, 10381, 1), -- elite
    (920064, 10558, 2), -- boss
    (920065, 10424, 0), -- trash
    (920066, 11043, 0), -- trash
    (920067, 10425, 0), -- trash
    (920068, 10422, 1), -- elite
    (920069, 10811, 2), -- boss
    (920070, 10480, 0), -- trash
    (920071, 10481, 0), -- trash
    (920072, 10495, 1), -- elite
    (920073, 10901, 2), -- boss
    (920074, 10485, 0), -- trash
    (920075, 10503, 2), -- boss
    (920076, 17259, 0), -- trash
    (920077, 17269, 0), -- trash
    (920078, 17270, 0), -- trash
    (920079, 17271, 1), -- elite
    (920080, 17306, 2), -- boss
    (920081, 17397, 0), -- trash
    (920082, 17477, 0), -- trash
    (920083, 17371, 1), -- elite
    (920084, 17377, 2), -- boss
    (920085, 18312, 0), -- trash
    (920086, 18315, 0), -- trash
    (920087, 19306, 0), -- trash
    (920088, 19307, 1), -- elite
    (920089, 18341, 2), -- boss
    (920090, 18700, 0), -- trash
    (920091, 18493, 0), -- trash
    (920092, 18702, 1), -- elite
    (920093, 18373, 2), -- boss
    (920094, 17962, 0), -- trash
    (920095, 17940, 0), -- trash
    (920096, 21127, 1), -- elite
    (920097, 17941, 2), -- boss
    (920098, 17728, 0), -- trash
    (920099, 17771, 0), -- trash
    (920100, 17729, 0), -- trash
    (920101, 17735, 1), -- elite
    (920102, 17882, 2), -- boss
    (920103, 19168, 0), -- trash
    (920104, 19510, 0), -- trash
    (920105, 19735, 1), -- elite
    (920106, 19221, 2), -- boss
    (920107, 19507, 0), -- trash
    (920108, 19513, 0), -- trash
    (920109, 19865, 1), -- elite
    (920110, 17978, 2), -- boss
    (920111, 24078, 0), -- trash
    (920112, 24080, 0), -- trash
    (920113, 28419, 0), -- trash
    (920114, 24085, 1), -- elite
    (920115, 23953, 2), -- boss
    (920116, 26694, 0), -- trash
    (920117, 26696, 0), -- trash
    (920118, 28368, 0), -- trash
    (920119, 26555, 1), -- elite
    (920120, 26687, 2), -- boss
    (920121, 28732, 0), -- trash
    (920122, 28734, 0), -- trash
    (920123, 28733, 0), -- trash
    (920124, 28730, 1), -- elite
    (920125, 28684, 2), -- boss
    (920126, 29768, 0), -- trash
    (920127, 29774, 0), -- trash
    (920128, 29819, 0), -- trash
    (920129, 29838, 1), -- elite
    (920130, 29304, 2), -- boss
    (920131, 27963, 0), -- trash
    (920132, 27960, 0), -- trash
    (920133, 27962, 0), -- trash
    (920134, 27969, 1), -- elite
    (920135, 27977, 2), -- boss
    (920136, 28837, 0), -- trash
    (920137, 28581, 0), -- trash
    (920138, 28836, 0), -- trash
    (920139, 28838, 1), -- elite
    (920140, 28586, 2), -- boss
    (920141, 37711, 0), -- trash
    (920142, 37712, 0), -- trash
    (920143, 37713, 0), -- trash
    (920144, 36879, 1), -- elite
    (920145, 36494, 2), -- boss
    (920146, 36564, 0), -- trash
    (920147, 36620, 0), -- trash
    (920148, 36516, 0), -- trash
    (920149, 36522, 1), -- elite
    (920150, 36497, 2); -- boss

DROP TEMPORARY TABLE IF EXISTS `tmp_infinite_dungeon_template`;
CREATE TEMPORARY TABLE `tmp_infinite_dungeon_template` LIKE `creature_template`;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 1731;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920010 WHERE `entry` = 1731;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 622;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920011 WHERE `entry` = 622;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4416;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920012 WHERE `entry` = 4416;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4417;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920013 WHERE `entry` = 4417;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 1763;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920014 WHERE `entry` = 1763;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 657;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920015 WHERE `entry` = 657;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 1732;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920016 WHERE `entry` = 1732;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 636;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920017 WHERE `entry` = 636;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 647;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920018 WHERE `entry` = 647;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 3877;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920019 WHERE `entry` = 3877;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 3875;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920020 WHERE `entry` = 3875;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 3857;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920021 WHERE `entry` = 3857;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4278;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920022 WHERE `entry` = 4278;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 3853;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920023 WHERE `entry` = 3853;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 3864;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920024 WHERE `entry` = 3864;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 3886;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920025 WHERE `entry` = 3886;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4306;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920026 WHERE `entry` = 4306;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4283;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920027 WHERE `entry` = 4283;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4540;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920028 WHERE `entry` = 4540;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 3983;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920029 WHERE `entry` = 3983;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 7309;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920030 WHERE `entry` = 7309;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 7077;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920031 WHERE `entry` = 7077;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 7076;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920032 WHERE `entry` = 7076;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10120;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920033 WHERE `entry` = 10120;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 2748;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920034 WHERE `entry` = 2748;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4851;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920035 WHERE `entry` = 4851;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4852;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920036 WHERE `entry` = 4852;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 4850;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920037 WHERE `entry` = 4850;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 6910;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920038 WHERE `entry` = 6910;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 5649;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920039 WHERE `entry` = 5649;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 7247;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920040 WHERE `entry` = 7247;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 5650;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920041 WHERE `entry` = 5650;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 7246;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920042 WHERE `entry` = 7246;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 7272;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920043 WHERE `entry` = 7272;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 8095;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920044 WHERE `entry` = 8095;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 7795;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920045 WHERE `entry` = 7795;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 11792;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920046 WHERE `entry` = 11792;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 11791;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920047 WHERE `entry` = 11791;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 12217;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920048 WHERE `entry` = 12217;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 12236;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920049 WHERE `entry` = 12236;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 9545;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920050 WHERE `entry` = 9545;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 9547;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920051 WHERE `entry` = 9547;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 9554;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920052 WHERE `entry` = 9554;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 9541;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920053 WHERE `entry` = 9541;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 9537;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920054 WHERE `entry` = 9537;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 8892;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920055 WHERE `entry` = 8892;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 8891;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920056 WHERE `entry` = 8891;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 8921;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920057 WHERE `entry` = 8921;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 8909;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920058 WHERE `entry` = 8909;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 9025;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920059 WHERE `entry` = 9025;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10390;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920060 WHERE `entry` = 10390;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10391;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920061 WHERE `entry` = 10391;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10405;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920062 WHERE `entry` = 10405;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10381;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920063 WHERE `entry` = 10381;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10558;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920064 WHERE `entry` = 10558;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10424;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920065 WHERE `entry` = 10424;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 11043;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920066 WHERE `entry` = 11043;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10425;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920067 WHERE `entry` = 10425;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10422;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920068 WHERE `entry` = 10422;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10811;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920069 WHERE `entry` = 10811;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10480;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920070 WHERE `entry` = 10480;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10481;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920071 WHERE `entry` = 10481;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10495;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920072 WHERE `entry` = 10495;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10901;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920073 WHERE `entry` = 10901;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10485;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920074 WHERE `entry` = 10485;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 10503;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920075 WHERE `entry` = 10503;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17259;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920076 WHERE `entry` = 17259;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17269;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920077 WHERE `entry` = 17269;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17270;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920078 WHERE `entry` = 17270;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17271;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920079 WHERE `entry` = 17271;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17306;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920080 WHERE `entry` = 17306;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17397;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920081 WHERE `entry` = 17397;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17477;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920082 WHERE `entry` = 17477;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17371;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920083 WHERE `entry` = 17371;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17377;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920084 WHERE `entry` = 17377;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 18312;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920085 WHERE `entry` = 18312;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 18315;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920086 WHERE `entry` = 18315;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19306;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920087 WHERE `entry` = 19306;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19307;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920088 WHERE `entry` = 19307;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 18341;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920089 WHERE `entry` = 18341;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 18700;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920090 WHERE `entry` = 18700;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 18493;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920091 WHERE `entry` = 18493;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 18702;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920092 WHERE `entry` = 18702;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 18373;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920093 WHERE `entry` = 18373;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17962;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920094 WHERE `entry` = 17962;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17940;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920095 WHERE `entry` = 17940;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 21127;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920096 WHERE `entry` = 21127;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17941;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920097 WHERE `entry` = 17941;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17728;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920098 WHERE `entry` = 17728;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17771;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920099 WHERE `entry` = 17771;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17729;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920100 WHERE `entry` = 17729;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17735;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920101 WHERE `entry` = 17735;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17882;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920102 WHERE `entry` = 17882;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19168;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920103 WHERE `entry` = 19168;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19510;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920104 WHERE `entry` = 19510;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19735;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920105 WHERE `entry` = 19735;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19221;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920106 WHERE `entry` = 19221;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19507;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920107 WHERE `entry` = 19507;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19513;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920108 WHERE `entry` = 19513;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 19865;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920109 WHERE `entry` = 19865;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 17978;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920110 WHERE `entry` = 17978;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 24078;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920111 WHERE `entry` = 24078;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 24080;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920112 WHERE `entry` = 24080;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28419;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920113 WHERE `entry` = 28419;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 24085;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920114 WHERE `entry` = 24085;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 23953;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920115 WHERE `entry` = 23953;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 26694;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920116 WHERE `entry` = 26694;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 26696;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920117 WHERE `entry` = 26696;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28368;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920118 WHERE `entry` = 28368;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 26555;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920119 WHERE `entry` = 26555;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 26687;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920120 WHERE `entry` = 26687;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28732;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920121 WHERE `entry` = 28732;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28734;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920122 WHERE `entry` = 28734;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28733;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920123 WHERE `entry` = 28733;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28730;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920124 WHERE `entry` = 28730;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28684;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920125 WHERE `entry` = 28684;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 29768;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920126 WHERE `entry` = 29768;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 29774;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920127 WHERE `entry` = 29774;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 29819;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920128 WHERE `entry` = 29819;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 29838;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920129 WHERE `entry` = 29838;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 29304;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920130 WHERE `entry` = 29304;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 27963;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920131 WHERE `entry` = 27963;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 27960;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920132 WHERE `entry` = 27960;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 27962;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920133 WHERE `entry` = 27962;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 27969;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920134 WHERE `entry` = 27969;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 27977;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920135 WHERE `entry` = 27977;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28837;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920136 WHERE `entry` = 28837;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28581;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920137 WHERE `entry` = 28581;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28836;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920138 WHERE `entry` = 28836;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28838;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920139 WHERE `entry` = 28838;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 28586;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920140 WHERE `entry` = 28586;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 37711;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920141 WHERE `entry` = 37711;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 37712;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920142 WHERE `entry` = 37712;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 37713;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920143 WHERE `entry` = 37713;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 36879;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920144 WHERE `entry` = 36879;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 36494;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920145 WHERE `entry` = 36494;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 36564;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920146 WHERE `entry` = 36564;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 36620;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920147 WHERE `entry` = 36620;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 36516;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920148 WHERE `entry` = 36516;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 36522;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920149 WHERE `entry` = 36522;
INSERT INTO `tmp_infinite_dungeon_template` SELECT * FROM `creature_template` WHERE `entry` = 36497;
UPDATE `tmp_infinite_dungeon_template` SET `entry` = 920150 WHERE `entry` = 36497;
UPDATE `tmp_infinite_dungeon_template` t JOIN `tmp_infinite_dungeon_copy` c ON c.`entry` = t.`entry` SET
    t.`difficulty_entry_1` = 0, t.`difficulty_entry_2` = 0, t.`difficulty_entry_3` = 0,
    t.`KillCredit1` = 0, t.`KillCredit2` = 0, t.`gossip_menu_id` = 0, t.`npcflag` = 0, t.`faction` = 14,
    t.`rank` = IF(c.`role` = 0, 0, 1),
    t.`type_flags` = IF(c.`role` = 2, t.`type_flags` | 4, t.`type_flags` & ~4),
    t.`unit_flags` = 0, t.`unit_flags2` = 0, t.`dynamicflags` = 0, t.`VehicleId` = 0,
    t.`lootid` = 0, t.`pickpocketloot` = 0, t.`skinloot` = 0, t.`mingold` = 0, t.`maxgold` = 0,
    t.`AIName` = '', t.`MovementType` = 0, t.`HealthModifier` = 1, t.`ManaModifier` = 1,
    t.`ArmorModifier` = 1, t.`DamageModifier` = 1, t.`ExperienceModifier` = 1, t.`RegenHealth` = 1,
    t.`CreatureImmunitiesId` = 0, t.`flags_extra` = 64, t.`ScriptName` = 'npc_infinite_dungeon_creature',
    t.`detection_range` = IF(c.`role` = 2, 10, 12),
    t.`VerifiedBuild` = NULL;
INSERT INTO `creature_template` SELECT * FROM `tmp_infinite_dungeon_template`;

INSERT INTO `creature_template_model`
    (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)
SELECT c.`entry`, m.`Idx`, m.`CreatureDisplayID`, m.`DisplayScale`, m.`Probability`, NULL
FROM `tmp_infinite_dungeon_copy` c JOIN `creature_template_model` m ON m.`CreatureID` = c.`source`;

INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`)
SELECT c.`entry`, e.`ID`, e.`ItemID1`, e.`ItemID2`, e.`ItemID3`, NULL
FROM `tmp_infinite_dungeon_copy` c JOIN `creature_equip_template` e ON e.`CreatureID` = c.`source`;

INSERT INTO `creature_template_movement`
    (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Chase`, `Random`, `InteractionPauseTimer`)
SELECT c.`entry`, v.`Ground`, v.`Swim`, v.`Flight`, 0, v.`Chase`, 0, v.`InteractionPauseTimer`
FROM `tmp_infinite_dungeon_copy` c JOIN `creature_template_movement` v ON v.`CreatureId` = c.`source`;

INSERT INTO `creature_template_locale` (`entry`, `locale`, `Name`, `Title`, `VerifiedBuild`)
SELECT c.`entry`, l.`locale`, l.`Name`, l.`Title`, NULL
FROM `tmp_infinite_dungeon_copy` c JOIN `creature_template_locale` l ON l.`entry` = c.`source`;

DROP TEMPORARY TABLE `tmp_infinite_dungeon_template`;
DROP TEMPORARY TABLE `tmp_infinite_dungeon_copy`;
