-- Generated by localTools/paragon/buildParagonTree.py -- do not edit by hand.
--
-- The paragon glyphs as items (ParagonSystem.cpp): legendary, soulbound, one a stack. Using one from the
-- bags learns it into the character's collection, or absorbs a copy of one already known as experience.
-- Entries 13642-13671: below 65536 and already in the client's Item.dbc (empty class 15 rows) with no
-- template on the server before these. Their icons are the inscription glyphs', set in the client's
-- Item.dbc by localTools/patchSinisterStrike.ps1 from localTools/paragon/glyphItemDisplays.json.
DELETE FROM `item_template_locale` WHERE `ID` BETWEEN 13642 AND 13671;
DELETE FROM `item_template` WHERE `entry` BETWEEN 13642 AND 13671;
INSERT INTO `item_template` (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `maxcount`, `stackable`, `bonding`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`, `description`, `Material`, `ScriptName`, `VerifiedBuild`) VALUES
(13642, 15, 0, 'Glyph of the Anvil', 54733, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Struck on Khaz''goroth''s anvil, it still rings when held tight.', 0, 'item_paragon_glyph', 12340),
(13643, 15, 0, 'Glyph of the Verdict', 57346, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Tyr only ever struck once. He never needed a second blow.', 0, 'item_paragon_glyph', 12340),
(13644, 15, 0, 'Glyph of the Colossus', 57356, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'The iron giants of Ulduar bore this sign carved on their fists.', 0, 'item_paragon_glyph', 12340),
(13645, 15, 0, 'Glyph of the Burning Forge', 57349, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'An ember of the Forge of Wills, caught in a rune.', 0, 'item_paragon_glyph', 12340),
(13646, 15, 0, 'Glyph of the Titan', 57345, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Whoever bears this glyph stands as a mountain stands.', 0, 'item_paragon_glyph', 12340),
(13647, 15, 0, 'Glyph of the Quarry', 57353, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Every prey brought down feeds the next.', 0, 'item_paragon_glyph', 12340),
(13648, 15, 0, 'Glyph of Carnage', 54954, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Odyn counted his warriors by the height of their foes'' pile.', 0, 'item_paragon_glyph', 12340),
(13649, 15, 0, 'Glyph of Deflagration', 57351, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Aggramar never struck a demon alone.', 0, 'item_paragon_glyph', 12340),
(13650, 15, 0, 'Glyph of the Feast', 57348, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Blood that is spilled always returns to the one who spilled it.', 0, 'item_paragon_glyph', 12340),
(13651, 15, 0, 'Glyph of the Horde', 57344, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'The more of them there are, the farther the blow carries.', 0, 'item_paragon_glyph', 12340),
(13652, 15, 0, 'Glyph of the Mirror', 57347, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'What is sent your way now belongs to you.', 0, 'item_paragon_glyph', 12340),
(13653, 15, 0, 'Glyph of Shadow', 57352, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Carved in the night before Thorim''s storm.', 0, 'item_paragon_glyph', 12340),
(13654, 15, 0, 'Glyph of Twin Blades', 55304, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Lightning never strikes twice in the same place. Except here.', 0, 'item_paragon_glyph', 12340),
(13655, 15, 0, 'Glyph of Bloodletting', 57343, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'The finest blade leaves the longest trail.', 0, 'item_paragon_glyph', 12340),
(13656, 15, 0, 'Glyph of the Wind', 57359, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Golganneth breathed the speed of storms into it.', 0, 'item_paragon_glyph', 12340),
(13657, 15, 0, 'Glyph of the Rampart', 57358, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Hodir once held a frozen pass alone against a whole army.', 0, 'item_paragon_glyph', 12340),
(13658, 15, 0, 'Glyph of Granite', 54953, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'A scale of the first earthen''s stone skin.', 0, 'item_paragon_glyph', 12340),
(13659, 15, 0, 'Glyph of Rancor', 57357, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Every blow taken is a debt. This one keeps the books.', 0, 'item_paragon_glyph', 12340),
(13660, 15, 0, 'Glyph of Defiance', 57354, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'The roar carved into this rune draws every eye, and every blow.', 0, 'item_paragon_glyph', 12340),
(13661, 15, 0, 'Glyph of Life', 57355, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Forged by Mimiron so that a machine would never stop.', 0, 'item_paragon_glyph', 12340),
(13662, 15, 0, 'Glyph of Resonance', 57350, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Norgannon wrote a word in it that never stops repeating.', 0, 'item_paragon_glyph', 12340),
(13663, 15, 0, 'Glyph of the Tempest', 57362, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'A shard of the storm that rumbles over Ulduar.', 0, 'item_paragon_glyph', 12340),
(13664, 15, 0, 'Glyph of Celerity', 57364, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Aman''Thul''s time runs a little faster in it than anywhere else.', 0, 'item_paragon_glyph', 12340),
(13665, 15, 0, 'Glyph of Arcane Might', 57367, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'It burns the fingers of those who cannot read it.', 0, 'item_paragon_glyph', 12340),
(13666, 15, 0, 'Glyph of the Singularity', 54728, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'All that weakens is drawn into it, then swallowed.', 0, 'item_paragon_glyph', 12340),
(13667, 15, 0, 'Glyph of Sap', 54730, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'A drop of dew from the gardens of Eonar.', 0, 'item_paragon_glyph', 12340),
(13668, 15, 0, 'Glyph of Sharing', 54958, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'Freya kept nothing for herself, not even life.', 0, 'item_paragon_glyph', 12340),
(13669, 15, 0, 'Glyph of the Aegis', 57371, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'A warding rune the Keepers carved upon their doors.', 0, 'item_paragon_glyph', 12340),
(13670, 15, 0, 'Glyph of Clarity', 54727, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'The mind that bears it knows no weariness.', 0, 'item_paragon_glyph', 12340),
(13671, 15, 0, 'Glyph of Revelation', 54729, 5, 0, 1, 0, 0, 0, -1, -1, 80, 80, 0, 1, 1, 483, 0, 0, 'It shows, for a moment, what the Titans saw.', 0, 'item_paragon_glyph', 12340);

INSERT INTO `item_template_locale` (`ID`, `locale`, `Name`, `Description`, `VerifiedBuild`) VALUES
(13642, 'frFR', 'Glyphe de l''Enclume', 'Frappé sur l''enclume de Khaz''goroth, il sonne encore quand on le serre.', 12340),
(13643, 'frFR', 'Glyphe du Verdict', 'Tyr ne frappait qu''une fois. Il n''avait jamais besoin d''une deuxième.', 12340),
(13644, 'frFR', 'Glyphe du Colosse', 'Les géants de fer d''Ulduar portaient ce signe gravé sur le poing.', 12340),
(13645, 'frFR', 'Glyphe de la Forge ardente', 'Une braise de la Forge des volontés, prisonnière d''une rune.', 12340),
(13646, 'frFR', 'Glyphe du Titan', 'Qui porte ce glyphe se tient comme une montagne se tient.', 12340),
(13647, 'frFR', 'Glyphe de la Curée', 'Chaque proie abattue nourrit la suivante.', 12340),
(13648, 'frFR', 'Glyphe du Carnage', 'Odyn comptait ses guerriers à la hauteur de leur tas d''ennemis.', 12340),
(13649, 'frFR', 'Glyphe de la Déflagration', 'Aggramar ne frappait jamais un démon seul.', 12340),
(13650, 'frFR', 'Glyphe du Festin', 'Le sang versé revient toujours à celui qui l''a versé.', 12340),
(13651, 'frFR', 'Glyphe de la Horde', 'Plus ils sont nombreux, plus le coup porte loin.', 12340),
(13652, 'frFR', 'Glyphe du Miroir', 'Ce que l''on vous envoie vous appartient désormais.', 12340),
(13653, 'frFR', 'Glyphe de l''Ombre', 'Taillé dans la nuit qui précède l''orage de Thorim.', 12340),
(13654, 'frFR', 'Glyphe des Lames jumelles', 'Deux éclairs ne tombent jamais au même endroit. Sauf ici.', 12340),
(13655, 'frFR', 'Glyphe de la Saignée', 'La plus fine des lames laisse la plus longue des traces.', 12340),
(13656, 'frFR', 'Glyphe du Vent', 'Golganneth y a soufflé la vitesse des tempêtes.', 12340),
(13657, 'frFR', 'Glyphe du Rempart', 'Hodir a tenu seul une passe gelée contre une armée entière.', 12340),
(13658, 'frFR', 'Glyphe de Granit', 'Une écaille de la peau de pierre des premiers terrestres.', 12340),
(13659, 'frFR', 'Glyphe de Rancune', 'Chaque coup reçu est une dette. Celui-ci tient les comptes.', 12340),
(13660, 'frFR', 'Glyphe du Défi', 'Le rugissement gravé dans cette rune attire les regards, et les coups.', 12340),
(13661, 'frFR', 'Glyphe de Vie', 'Forgé par Mimiron pour qu''une machine ne s''arrête jamais.', 12340),
(13662, 'frFR', 'Glyphe de Résonance', 'Norgannon y a écrit un mot qui ne cesse de se répéter.', 12340),
(13663, 'frFR', 'Glyphe de la Tempête', 'Un fragment de l''orage qui gronde au-dessus d''Ulduar.', 12340),
(13664, 'frFR', 'Glyphe de Célérité', 'Le temps d''Aman''Thul s''y écoule un peu plus vite qu''ailleurs.', 12340),
(13665, 'frFR', 'Glyphe de Puissance arcanique', 'Il brûle les doigts de ceux qui ne savent pas le lire.', 12340),
(13666, 'frFR', 'Glyphe de la Singularité', 'Tout ce qui faiblit y est attiré, puis englouti.', 12340),
(13667, 'frFR', 'Glyphe de Sève', 'Une goutte de la rosée des jardins d''Eonar.', 12340),
(13668, 'frFR', 'Glyphe du Partage', 'Freya ne gardait rien pour elle, pas même la vie.', 12340),
(13669, 'frFR', 'Glyphe de l''Égide', 'Une rune de garde que les Gardiens gravaient sur leurs portes.', 12340),
(13670, 'frFR', 'Glyphe de Clarté', 'L''esprit qui le porte ne connaît pas la fatigue.', 12340),
(13671, 'frFR', 'Glyphe de Révélation', 'Il montre, un instant, ce que les Titans ont vu.', 12340);
