-- Generated by localTools/retailImport (RetailImport import) from
-- localTools/retailImport/items.json -- do not edit by hand.
--
-- Test items wearing looks imported from the retail client
-- (localTools/retailImport/README.md).
-- Each copies a stock item's stats and shows a retail display. Their entries are below 65536
-- and already in the client's Item.dbc with no template on the server before these;
-- localTools/patchSinisterStrike.ps1 gives those Item.dbc rows the class, slot and display
-- written here.
DELETE FROM `item_template_locale` WHERE `ID` IN (19313, 19314, 16144);
DELETE FROM `item_template` WHERE `entry` IN (19313, 19314, 16144);

DROP TEMPORARY TABLE IF EXISTS `tmp_retail_item`;
CREATE TEMPORARY TABLE `tmp_retail_item` LIKE `item_template`;

-- Fangs of the Devourer: stats of item 50641, display 70001
INSERT INTO `tmp_retail_item` SELECT * FROM `item_template` WHERE `entry` = 50641;
UPDATE `tmp_retail_item` SET
    `entry` = 19313,
    `name` = 'Fangs of the Devourer',
    `class` = 2,
    `subclass` = 15,
    `SoundOverrideSubclass` = -1,
    `Material` = 1,
    `displayid` = 70001,
    `InventoryType` = 21,
    `sheath` = 3,
    `description` = 'Retail import test piece.',
    `itemset` = 0,
    `VerifiedBuild` = NULL;
INSERT INTO `item_template` SELECT * FROM `tmp_retail_item`;
DELETE FROM `tmp_retail_item`;

-- Fangs of the Devourer: stats of item 50676, display 70001
INSERT INTO `tmp_retail_item` SELECT * FROM `item_template` WHERE `entry` = 50676;
UPDATE `tmp_retail_item` SET
    `entry` = 19314,
    `name` = 'Fangs of the Devourer',
    `class` = 2,
    `subclass` = 15,
    `SoundOverrideSubclass` = -1,
    `Material` = 1,
    `displayid` = 70001,
    `InventoryType` = 22,
    `sheath` = 3,
    `description` = 'Retail import test piece.',
    `itemset` = 0,
    `VerifiedBuild` = NULL;
INSERT INTO `item_template` SELECT * FROM `tmp_retail_item`;
DELETE FROM `tmp_retail_item`;

-- Shoulderpads of the Dashing Scoundrel: stats of item 50646, display 70002
INSERT INTO `tmp_retail_item` SELECT * FROM `item_template` WHERE `entry` = 50646;
UPDATE `tmp_retail_item` SET
    `entry` = 16144,
    `name` = 'Shoulderpads of the Dashing Scoundrel',
    `class` = 4,
    `subclass` = 2,
    `SoundOverrideSubclass` = -1,
    `Material` = 8,
    `displayid` = 70002,
    `InventoryType` = 3,
    `sheath` = 0,
    `description` = 'Retail import test piece.',
    `itemset` = 0,
    `VerifiedBuild` = NULL;
INSERT INTO `item_template` SELECT * FROM `tmp_retail_item`;
DELETE FROM `tmp_retail_item`;

DROP TEMPORARY TABLE `tmp_retail_item`;

INSERT INTO `item_template_locale` (`ID`, `locale`, `Name`, `Description`, `VerifiedBuild`) VALUES
(19313, 'frFR', 'Crocs du Dévoreur', 'Pièce de test importée du jeu actuel.', NULL),
(19314, 'frFR', 'Crocs du Dévoreur', 'Pièce de test importée du jeu actuel.', NULL),
(16144, 'frFR', 'Protège-épaules du scélérat fringant', 'Pièce de test importée du jeu actuel.', NULL);
