#ifndef MOD_STAT_GROWTH_INFINITE_DUNGEON_ARENAS_H
#define MOD_STAT_GROWTH_INFINITE_DUNGEON_ARENAS_H

#include "Define.h"

#include <array>
#include <vector>

// The rooms the Infinite Dungeon's floors are fought in (InfiniteDungeonArenas.cpp, generated by
// localTools/infiniteDungeon/buildArenas.py). Each one is a room of an existing dungeon, picked by the level of the
// run, so the setting fits: the players arrive in the safety bubble at `entry`, the boss waits at `boss`, and the
// trash packs stand on the `trash` spots. The creatures are the room's own, copied under the entries named here.
namespace InfiniteDungeon
{
struct ArenaSpot
{
    float x = 0.0f;
    float y = 0.0f;
    float z = 0.0f;
    float o = 0.0f;
};

constexpr std::size_t MaxTrashSpots = 6;
constexpr std::size_t MaxTrashEntries = 3;

struct Arena
{
    char const* nameEn;
    char const* nameFr;
    uint32 mapId;
    uint8 minLevel;             // the run levels this arena is drawn for
    uint8 maxLevel;
    ArenaSpot entry;            // where the players arrive: the centre of the bubble
    ArenaSpot boss;
    std::array<ArenaSpot, MaxTrashSpots> trash;
    uint32 trashSpots;
    std::array<uint32, MaxTrashEntries> trashEntries;   // 0 past the last
    uint32 eliteEntry;
    uint32 bossEntry;
};

std::vector<Arena> const& GetArenas();
}

#endif
