param(
    [Parameter(Mandatory = $true)]
    [string]$ClientPath,
    # Generated by localTools/clientExe/buildWowExePatch.py
    [string]$SpecPath = (Join-Path $PSScriptRoot 'WowExePatch.json'),
    # Where the untouched Wow.exe is saved; the installer passes its backup folder
    [string]$BackupPath
)

# Applies every change made to Wow.exe 3.3.5a (12340): the awesome_wotlk loader (MSDF fonts and client fixes,
# from AwesomeWotlkLib.dll) and the Dungeon Finder roles of the custom classes.
#
# Each patch is a byte range with its stock and its patched bytes. Every range is checked before anything is
# written: a range that is neither aborts the whole run and leaves the file untouched. Ranges already patched
# are skipped, so running this again does nothing.

$ErrorActionPreference = 'Stop'

function ConvertFrom-Hex([string]$hex) {
    $bytes = [byte[]]::new($hex.Length / 2)
    for ($i = 0; $i -lt $bytes.Length; ++$i) {
        $bytes[$i] = [Convert]::ToByte($hex.Substring($i * 2, 2), 16)
    }
    return , $bytes
}

function Test-Range([byte[]]$bytes, [int]$offset, [byte[]]$expected) {
    for ($i = 0; $i -lt $expected.Length; ++$i) {
        if ($bytes[$offset + $i] -ne $expected[$i]) {
            return $false
        }
    }
    return $true
}

function Test-CompatibleRoleRange([byte[]]$bytes, [int]$offset, [byte[]]$stock, [byte[]]$patched) {
    # Existing installs may already carry the older Pestiféré-only table. Accept only bytes that are
    # either stock or ours at each position; every unrelated modification still aborts the patch.
    if ($stock.Length -ne $patched.Length) {
        return $false
    }
    for ($i = 0; $i -lt $patched.Length; ++$i) {
        if ($bytes[$offset + $i] -ne $stock[$i] -and $bytes[$offset + $i] -ne $patched[$i]) {
            return $false
        }
    }
    return $true
}

$spec = Get-Content -LiteralPath $SpecPath -Raw -Encoding UTF8 | ConvertFrom-Json
$exePath = Join-Path $ClientPath $spec.file
if (-not (Test-Path -LiteralPath $exePath)) {
    throw "Client executable not found: $exePath"
}
$bytes = [IO.File]::ReadAllBytes($exePath)

# Check every range first: nothing is written unless all of them are recognised
$pending = @()
foreach ($patch in $spec.patches) {
    $offset = [int]$patch.offset
    $stock = ConvertFrom-Hex $patch.stock
    $patched = ConvertFrom-Hex $patch.patched
    if ($bytes.Length -lt $offset + $patched.Length) {
        throw "$exePath is not the WotLK 3.3.5a ($($spec.build)) client these patches are made for."
    }
    if (Test-Range $bytes $offset $patched) {
        continue
    }
    $compatibleRoles = $patch.name -like 'Dungeon Finder roles:*' -and
        (Test-CompatibleRoleRange $bytes $offset $stock $patched)
    if (-not (Test-Range $bytes $offset $stock) -and -not $compatibleRoles) {
        throw ("$exePath has been modified where '{0}' goes ({1}), by something this installer does not know. " +
            "Nothing was changed.") -f $patch.name, $patch.va
    }
    $pending += [pscustomobject]@{ Patch = $patch; Offset = $offset; Bytes = $patched }
}

if (-not $pending) {
    Write-Host 'Wow.exe already carries every patch.'
    return
}

if ($BackupPath) {
    New-Item -ItemType Directory -Path $BackupPath -Force | Out-Null
    Copy-Item -LiteralPath $exePath -Destination (Join-Path $BackupPath $spec.file) -Force
}
else {
    $localBackup = "$exePath.before-custom-classes"
    if (-not (Test-Path -LiteralPath $localBackup)) {
        Copy-Item -LiteralPath $exePath -Destination $localBackup
    }
}

foreach ($item in $pending) {
    [Array]::Copy($item.Bytes, 0, $bytes, $item.Offset, $item.Bytes.Length)
}
[IO.File]::WriteAllBytes($exePath, $bytes)

$written = [IO.File]::ReadAllBytes($exePath)
foreach ($item in $pending) {
    if (-not (Test-Range $written $item.Offset $item.Bytes)) {
        throw "Writing '$($item.Patch.name)' into $exePath failed."
    }
    Write-Host "Wow.exe: $($item.Patch.name)"
}
