#ifndef MOD_STAT_GROWTH_COMBAT_ROGUE_H
#define MOD_STAT_GROWTH_COMBAT_ROGUE_H

#include "Define.h"

class Player;
class Unit;

// Combat rogue rework ("Crimson Duelist"): design in .agents/plans/combat-rogue-rework/.
// Client spell and talent data is generated by localTools/patchSinisterStrike.ps1.
void AddCombatRogueScripts();
void OnCombatRogueLogin(Player* player);
void UpdateCombatRogue(Player* player, uint32 diff);
void OnCombatRogueLevelChanged(Player* player, uint8 oldLevel);
void OnCombatRogueKill(Player* player, Unit* killed);

#endif
