#include "MythicAppearance.h"

#include "CharacterDatabase.h"
#include "Chat.h"
#include "ChatCommand.h"
#include "CommandScript.h"
#include "DBCStores.h"
#include "DatabaseEnv.h"
#include "Item.h"
#include "Log.h"
#include "MythicDungeon.h"
#include "ObjectMgr.h"
#include "Player.h"
#include "PlayerScript.h"
#include "PlayerSettings.h"
#include "ScriptMgr.h"
#include "StatGrowthConfig.h"
#include "Timer.h"
#include "WorldScript.h"

#include <string_view>
#include <unordered_map>
#include <vector>

// The looks of the Mythic+ generated gear. A generated item is a copy of a real item (MythicItemGeneration.cpp) and
// the client draws it with that item's look, so a 400 piece looked like the 284 piece it came from. What the client
// is told a character wears - its visible item fields, which the other players' clients, the character's own model
// and the character list draw - names another real item instead: one of the same slot and armour or weapon type, a
// tier set piece or a famous weapon, picked by the generated item's item level; and a generated weapon shows a glow,
// the look of a stock enchantment. The way transmogrification works: the item itself, its stats, its tooltip, the
// paper doll and what inspecting it shows do not change, nor does the weapon's real enchantment.
//
// The looks are data: mythic_appearance_tier and mythic_appearance_glow, generated by
// localTools/mythicAppearance/buildMythicAppearance.py. A player turns them off with .appearance off.
namespace
{
// Where a character's choice is kept: 1 turns the looks off
constexpr char SettingsSource[] = "mod_stat_growth_appearance";
constexpr uint32 HiddenSetting = 0;

// A real enchantment put on a worn weapon rewrites its visible enchantment (Player::ApplyEnchantment) without going
// through the hook: the glow is put back this often
constexpr uint32 GlowRefreshMs = 2000;

struct AppearanceTier
{
    uint32 minItemLevel;
    uint32 entry;
};

// (item class, subclass, inventory type as read by GetAppearanceType, player class) -> tiers, lowest first
std::unordered_map<uint32, std::vector<AppearanceTier>> Appearances;
std::vector<AppearanceTier> Glows;

uint32 MakeKey(uint32 itemClass, uint32 subclass, uint32 inventoryType, uint32 playerClass)
{
    return (itemClass << 24) | (subclass << 16) | (inventoryType << 8) | playerClass;
}

uint32 FindTier(std::vector<AppearanceTier> const& tiers, uint32 itemLevel)
{
    uint32 entry = 0;
    for (AppearanceTier const& tier : tiers)
    {
        if (tier.minItemLevel > itemLevel)
            break;
        entry = tier.entry;
    }
    return entry;
}

// A robe shows a chest's look; a one-hand weapon a main or off hand's, by where it is worn (a pair can differ)
uint8 GetAppearanceType(ItemTemplate const* proto, uint8 slot)
{
    switch (proto->InventoryType)
    {
        case INVTYPE_ROBE:
            return INVTYPE_CHEST;
        case INVTYPE_WEAPON:
        case INVTYPE_WEAPONMAINHAND:
        case INVTYPE_WEAPONOFFHAND:
            return slot == EQUIPMENT_SLOT_OFFHAND ? INVTYPE_WEAPONOFFHAND : INVTYPE_WEAPONMAINHAND;
        default:
            return proto->InventoryType;
    }
}

uint32 FindAppearance(uint8 playerClass, ItemTemplate const* proto, uint8 slot)
{
    uint8 const type = GetAppearanceType(proto, slot);
    auto found = Appearances.find(MakeKey(proto->Class, proto->SubClass, type, playerClass));
    if (found == Appearances.end())
        found = Appearances.find(MakeKey(proto->Class, proto->SubClass, type, 0));
    return found != Appearances.end() ? FindTier(found->second, proto->ItemLevel) : 0;
}

// The character's choice, read once it is loaded (the items are shown while loading, before it is)
struct AppearanceState : public DataMap::Base
{
    bool known = false;
    bool hidden = false;
    uint32 glowTimer = GlowRefreshMs;
};
constexpr char StateKey[] = "MythicAppearance";

AppearanceState* GetState(Player* player)
{
    return player->CustomData.GetDefault<AppearanceState>(StateKey);
}

bool IsShown(Player* player)
{
    if (!statGrowthConfig.GetConfigValue<bool>(StatGrowthConfigKey::MythicAppearanceEnabled))
        return false;
    AppearanceState const* state = player->CustomData.Get<AppearanceState>(StateKey);
    return !state || !state->hidden;
}

bool IsGenerated(Item const* item)
{
    return item && Mythic::IsGeneratedItem(item->GetEntry()) && item->GetTemplate();
}

void ShowGlow(Player* player, uint8 slot, Item const* item)
{
    uint32 const glow = MythicAppearance::GetWeaponGlow(player, item);
    if (!glow)
        return;
    uint32 const field = PLAYER_VISIBLE_ITEM_1_ENCHANTMENT + slot * 2;
    if (player->GetUInt16Value(field, 0) != glow)
        player->SetUInt16Value(field, 0, uint16(glow));
}

// Run after the core has shown the real item in the slot (Player::SetVisibleItemSlot)
void ShowAppearance(Player* player, uint8 slot, Item const* item)
{
    if (slot >= EQUIPMENT_SLOT_END || !IsGenerated(item) || !IsShown(player))
        return;
    if (uint32 const entry = FindAppearance(player->getClass(), item->GetTemplate(), slot))
        player->SetUInt32Value(PLAYER_VISIBLE_ITEM_1_ENTRYID + slot * 2, entry);
    ShowGlow(player, slot, item);
}

// Every worn item shown again from scratch: the real one first, then the hooks (this one, mod-forge's glow)
void RefreshAll(Player* player)
{
    for (uint8 slot = EQUIPMENT_SLOT_START; slot < EQUIPMENT_SLOT_END; ++slot)
        player->SetVisibleItemSlot(slot, player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot));
}

// The choice is loaded once the character is: the items shown while loading are shown again with it, and their
// glows over the enchantments the load applied after them. Bots too, on their first update.
void Initialize(Player* player)
{
    AppearanceState* state = GetState(player);
    state->hidden = player->GetPlayerSetting(SettingsSource, HiddenSetting).value != 0;
    state->known = true;
    RefreshAll(player);
}

void LoadAppearances()
{
    uint32 const startTime = getMSTime();
    Appearances.clear();
    Glows.clear();

    uint32 count = 0;
    if (QueryResult result = WorldDatabase.Query("SELECT item_class, item_subclass, inventory_type, player_class, "
        "min_item_level, appearance_entry FROM mythic_appearance_tier ORDER BY min_item_level"))
    {
        do
        {
            Field* field = result->Fetch();
            uint32 const entry = field[5].Get<uint32>();
            if (!sObjectMgr->GetItemTemplate(entry) || Mythic::IsGeneratedItem(entry))
            {
                LOG_ERROR("sql.sql", "mythic_appearance_tier: appearance_entry {} is not a real item, skipped", entry);
                continue;
            }
            Appearances[MakeKey(field[0].Get<uint8>(), field[1].Get<uint8>(), field[2].Get<uint8>(),
                field[3].Get<uint8>())].push_back({ field[4].Get<uint16>(), entry });
            ++count;
        } while (result->NextRow());
    }

    if (QueryResult result = WorldDatabase.Query(
        "SELECT min_item_level, enchantment FROM mythic_appearance_glow ORDER BY min_item_level"))
    {
        do
        {
            Field* field = result->Fetch();
            uint32 const enchantment = field[1].Get<uint16>();
            if (!sSpellItemEnchantmentStore.LookupEntry(enchantment))
            {
                LOG_ERROR("sql.sql", "mythic_appearance_glow: enchantment {} does not exist, skipped", enchantment);
                continue;
            }
            Glows.push_back({ field[0].Get<uint16>(), enchantment });
        } while (result->NextRow());
    }

    LOG_INFO("server.loading", ">> Loaded {} Mythic+ appearances and {} glows in {} ms", count, Glows.size(),
        GetMSTimeDiffToNow(startTime));
}

class MythicAppearanceWorldScript : public WorldScript
{
public:
    MythicAppearanceWorldScript() : WorldScript("MythicAppearanceWorldScript", {
        WORLDHOOK_ON_STARTUP
    }) { }

    // Once the world is up: the item templates and the enchantments the rows are checked against are loaded by then
    // (OnLoadCustomDatabaseTable came before both, and every row was dropped)
    void OnStartup() override
    {
        LoadAppearances();
    }
};

class MythicAppearancePlayerScript : public PlayerScript
{
public:
    MythicAppearancePlayerScript() : PlayerScript("MythicAppearancePlayerScript", {
        PLAYERHOOK_ON_LOGIN,
        PLAYERHOOK_ON_UPDATE,
        PLAYERHOOK_ON_AFTER_SET_VISIBLE_ITEM_SLOT
    }) { }

    void OnPlayerLogin(Player* player) override
    {
        Initialize(player);
    }

    void OnPlayerUpdate(Player* player, uint32 diff) override
    {
        AppearanceState* state = GetState(player);
        if (!state->known)
            return Initialize(player);
        if (state->glowTimer > diff)
        {
            state->glowTimer -= diff;
            return;
        }
        state->glowTimer = GlowRefreshMs;
        for (uint8 slot : { EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_OFFHAND, EQUIPMENT_SLOT_RANGED })
            ShowGlow(player, slot, player->GetItemByPos(INVENTORY_SLOT_BAG_0, slot));
    }

    // An item put on, taken off (item null: nothing to do), or shown again
    void OnPlayerAfterSetVisibleItemSlot(Player* player, uint8 slot, Item* item) override
    {
        ShowAppearance(player, slot, item);
    }
};

using namespace Acore::ChatCommands;

class MythicAppearanceCommandScript : public CommandScript
{
public:
    MythicAppearanceCommandScript() : CommandScript("MythicAppearanceCommandScript") { }

    ChatCommandTable GetCommands() const override
    {
        static ChatCommandTable commandTable =
        {
            { "appearance", HandleAppearance, SEC_PLAYER, Console::No }
        };
        return commandTable;
    }

    // .appearance [on|off]: the tiered looks of the Mythic+ gear, or the base items' own
    static bool HandleAppearance(ChatHandler* handler, Optional<std::string_view> mode)
    {
        Player* player = handler->GetPlayer();
        AppearanceState* state = GetState(player);
        if (!mode)
        {
            handler->PSendSysMessage("Mythic+ gear looks: {}. Use .appearance on or .appearance off.",
                state->hidden ? "off (base items)" : "on (by item level)");
            return true;
        }

        bool hidden;
        if (*mode == "on")
            hidden = false;
        else if (*mode == "off")
            hidden = true;
        else
        {
            handler->SendSysMessage("Use .appearance on or .appearance off.");
            return true;
        }

        state->hidden = hidden;
        state->known = true;
        uint32 const stored = hidden ? 1 : 0;
        player->UpdatePlayerSetting(SettingsSource, HiddenSetting, stored);
        PlayerSettingVector settings(1);
        settings[HiddenSetting].value = stored;
        CharacterDatabase.Execute(PlayerSettingsStore::PrepareReplaceStatement(player->GetGUID().GetCounter(),
            SettingsSource, settings));
        RefreshAll(player);

        if (!statGrowthConfig.GetConfigValue<bool>(StatGrowthConfigKey::MythicAppearanceEnabled))
            handler->SendSysMessage("Mythic+ gear looks are turned off on this realm.");
        else
            handler->PSendSysMessage("Mythic+ gear looks: {}.", hidden ? "off, your gear shows its base items" :
                "on, your gear shows its item level");
        return true;
    }
};
}

uint32 MythicAppearance::GetWeaponGlow(Player* player, Item const* item)
{
    if (!player || !IsGenerated(item) || item->GetTemplate()->Class != ITEM_CLASS_WEAPON || !IsShown(player))
        return 0;
    return FindTier(Glows, item->GetTemplate()->ItemLevel);
}

void AddMythicAppearanceScripts()
{
    new MythicAppearanceWorldScript();
    new MythicAppearancePlayerScript();
    new MythicAppearanceCommandScript();
}
