// Pestiféré (class 12) - server side of the plague tank.
//
// The spine: the class infects itself with up to three plagues, each of which gives something and takes
// something. Virulence (how many are carried, 0-3) scales all three, Contagion hands the enemy versions to
// the pack and keeps the carrier's own alive, and Détonation spends the rot the pack has accumulated.
//
// Spell data contract (rows generated by localTools/patchSinisterStrike.ps1; these are the slots the
// scripts drive - everything else about the spells is data, and the scripts do not touch it):
//   90200 Frappe putride     EFFECT_1 triggers Pourriture; Fossoyeur scales the hit and adds a stack
//   90202 Détonation         EFFECT_0 SPELL_EFFECT_SCHOOL_DAMAGE, caster-centred area (Thunder Clap layout)
//   90206 Détonation         EFFECT_0 SPELL_EFFECT_SCHOOL_DAMAGE on one enemy: Détonation en chaîne's jump
//   90207/90208 Sépulcre     EFFECT_0 SPELL_AURA_PERIODIC_DAMAGE, every tick dealt by the script
//   90211 Carapace nécrosée  EFFECT_0 SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, EFFECT_2 SPELL_AURA_MOD_RESISTANCE_PCT
//                            (EFFECT_1, the movement slow, is data only)
//   90213 Chair putride      EFFECT_0 SPELL_AURA_PERIODIC_HEAL
//   90215 Peste virulente    EFFECT_0 SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, EFFECT_1 SPELL_AURA_PERIODIC_DAMAGE
//   90256 Charnier ambulant  EFFECT_0 SPELL_EFFECT_DUMMY on every enemy within 10 yd
//   90265 Purge cathartique  EFFECT_0 SPELL_EFFECT_DUMMY on the caster
//   90268 Sépulcre           EFFECT_0 SPELL_AURA_SCHOOL_ABSORB, all schools, 8 sec
//   90243-90245 Mains putrides  a dummy aura that procs on off-hand hits (proc flags and chance are data)
//   90205 Pourriture         EFFECT_0 SPELL_AURA_PERIODIC_DAMAGE: each tick may grant Fièvre
//   90223 Flaque de bile     a dynamic object: EFFECT_0 SPELL_AURA_PERIODIC_DAMAGE,
//                            EFFECT_1 SPELL_AURA_MOD_DAMAGE_PERCENT_DONE
//   90224 Morsure fétide     one weapon damage effect, scaled by the Pourriture on the target
//   90225 Riposte purulente  one weapon damage effect, usable after a dodge, parry or block (aura state data)
//   90226 Carapace suintante EFFECT_0 SPELL_AURA_SCHOOL_ABSORB
//   90227 Bond putride       EFFECT_0 SPELL_EFFECT_CHARGE
//   90284 Vomissure          EFFECT_0 SPELL_EFFECT_SCHOOL_DAMAGE, cone
//   90287 Avatar de la peste EFFECT_0 SPELL_AURA_MOD_SCALE
// The three self plagues have no duration in data; this module sets it when the carrier leaves combat.

#include "Pestifere.h"

#include "Item.h"
#include "Log.h"
#include "ObjectAccessor.h"
#include "Player.h"
#include "PlayerScript.h"
#include "Random.h"
#include "ScriptMgr.h"
#include "SharedDefines.h"
#include "SpellAuraEffects.h"
#include "SpellAuras.h"
#include "SpellInfo.h"
#include "SpellScript.h"
#include "Unit.h"
#include "UnitScript.h"

#include <algorithm>
#include <vector>

using namespace Pestifere;

namespace
{
// -----------------------------------------------------------------------------------------------------------------
// Tuning
// -----------------------------------------------------------------------------------------------------------------

// Contagion (90201): its radius is the spell's own (see PestifereContagionSpellScript), so talents apply to it
// Threat added per enemy, per plague actually spread onto it. Contagion is the class's main threat tool.
constexpr float CONTAGION_THREAT_PER_PLAGUE = 90.0f;

// Détonation (90202): damage = base + (stacks * perStack) * (1 + bonus * plaguesConsumed) + what Sépulcre held
// Base and per-stack damage are shares of attack power, so the button keeps up while levelling.
constexpr float DETONATION_BASE_AP_COEFF = 0.15f;
constexpr float DETONATION_STACK_AP_COEFF = 0.12f;
// +50% per plague consumed on that enemy: a fully infected, fully rotten target is worth many times a fresh one
constexpr float DETONATION_PLAGUE_BONUS = 0.5f;
// Self-heal per enemy detonated, as a percentage of the caster's maximum health
constexpr float DETONATION_HEAL_PCT_PER_TARGET = 2.0f;
// Rage refunded per enemy detonated at the Pourriture cap - big booms fund the next build-up
constexpr uint32 DETONATION_RIPE_RAGE_REFUND = 5;
// Détonation en chaîne: how far outside the blast a jump reaches, from an enemy that exploded
constexpr float DETONATION_CHAIN_RADIUS = 8.0f;

// Charnier ambulant (90256): threat added to every enemy it reaches, on top of Contagion-style spreading
constexpr float CHARNIER_THREAT_PER_ENEMY = 350.0f;

// Purge cathartique (90265): % of maximum health healed per plague purged
constexpr uint32 PURGE_HEAL_PCT_PER_PLAGUE = 12;

// Sépulcre (90268): % of each hit held back and dealt later by the stored plague
constexpr uint32 SEPULCRE_HELD_PCT = 50;

// Pourriture (90205) and the enemy Peste virulente (90222): their 3 sec ticks deal a share of the target's maximum
// health, per stack for Pourriture, so they scale with whatever they rot. On a huge health pool (a boss) a tick is
// held to a share of the Pestiféré's attack power instead.
constexpr float POURRITURE_TICK_HEALTH_PCT = 1.0f;      // % of maximum health per stack per tick
constexpr float PESTE_ENEMY_TICK_HEALTH_PCT = 1.0f;     // % of maximum health per tick
constexpr float PLAGUE_TICK_AP_CAP = 0.15f;             // most a tick (a stack of Pourriture) deals, x attack power

// Flaque de bile (90223): damage of each 2 sec tick, as a share of attack power
constexpr float FLAQUE_TICK_AP_COEFF = 0.06f;

// Morsure fétide (90224): % more damage per Pourriture stack on the target
constexpr int32 MORSURE_DAMAGE_PER_STACK = 10;

// Riposte purulente (90225): nearby enemies it rots besides its target, and how far it reaches
constexpr uint32 RIPOSTE_EXTRA_TARGETS = 2;
constexpr float RIPOSTE_RADIUS = 8.0f;
// Riposte fétide: % more Riposte purulente damage per talent point
constexpr int32 RIPOSTE_FETIDE_DAMAGE_PER_POINT = 10;

// Carapace suintante (90226): % of maximum health absorbed, and more per plague carried
constexpr uint32 SUINTANTE_ABSORB_PCT_BASE = 4;
constexpr uint32 SUINTANTE_ABSORB_PCT_STEP = 3;

// Pandémie (90229): extra enemies each Frappe putride strikes, within this reach of the caster
constexpr uint32 PANDEMIE_EXTRA_TARGETS = 3;
constexpr float PANDEMIE_RADIUS = 5.0f;

// Vomissure (90284): damage to each enemy in the cone as a share of attack power, and the Pourriture it sows
constexpr float VOMISSURE_AP_COEFF = 0.6f;
constexpr uint8 VOMISSURE_ROT_STACKS = 2;

// Charognard: how far the rot of a dying enemy can jump
constexpr float CHAROGNARD_RADIUS = 10.0f;

// Carapace nécrosée (90211): mitigation plague
constexpr int32 CARAPACE_DAMAGE_REDUCTION_BASE = 4;     // % damage taken reduction at Virulence 1
constexpr int32 CARAPACE_DAMAGE_REDUCTION_STEP = 3;     // extra % per further plague carried
constexpr int32 CARAPACE_ARMOR_BASE = 10;               // % armor at Virulence 1
constexpr int32 CARAPACE_ARMOR_STEP = 10;               // extra % per further plague carried

// Chair putride (90213): healing plague
constexpr float CHAIR_HEAL_PCT_BASE = 0.6f;             // % of maximum health healed per tick at Virulence 1
constexpr float CHAIR_HEAL_PCT_STEP = 0.4f;             // extra % per further plague carried
constexpr uint32 CHAIR_HEALING_TAKEN_PENALTY = 20;      // % less healing received from others
constexpr uint32 CHAIR_ENEMY_HEALING_PENALTY = 20;      // % less healing received by an enemy carrying it

// Peste virulente (90215): damage plague
constexpr int32 PESTE_DAMAGE_DONE_BASE = 6;             // % damage done at Virulence 1
constexpr int32 PESTE_DAMAGE_DONE_STEP = 4;             // extra % per further plague carried
constexpr float PESTE_SELF_DAMAGE_PCT = 0.5f;           // % of maximum health per tick, before escalation
constexpr float PESTE_ESCALATION_STEP = 0.25f;          // +25% of that tick per tick spent as the only plague
constexpr uint32 PESTE_ESCALATION_MAX = 12;             // escalation cap, so it converges instead of exploding

// -----------------------------------------------------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------------------------------------------------

Player* GetPestifere(Unit* unit)
{
    Player* player = unit ? unit->ToPlayer() : nullptr;
    return IsPestifere(player) ? player : nullptr;
}

int32 ScaleByVirulence(uint8 virulence, int32 base, int32 step)
{
    return virulence ? base + step * int32(virulence - 1) : 0;
}

bool IsWieldingTwoHand(Player const* player)
{
    Item const* weapon = player->GetWeaponForAttack(BASE_ATTACK, true);
    return weapon && weapon->GetTemplate()->InventoryType == INVTYPE_2HWEAPON;
}

// The plague ticks Menace contagieuse turns into extra threat (Sépulcre's adds its own, see its aura script)
bool IsPlagueDamage(uint32 spellId)
{
    switch (spellId)
    {
        case SPELL_POURRITURE:
        case SPELL_CARAPACE_NECROSEE_ENEMY:
        case SPELL_CHAIR_PUTRIDE_ENEMY:
        case SPELL_PESTE_VIRULENTE_ENEMY:
            return true;
        default:
            return false;
    }
}

// Menace contagieuse: plague damage generates extra threat on the enemy it hurts
void AddPlagueThreat(Player* caster, Unit* target, uint32 damage, SpellInfo const* spellInfo)
{
    int32 const bonus = GetTalentValue(caster, TALENT_MENACE_CONTAGIEUSE);
    if (!bonus || !damage || !target->CanHaveThreatList())
        return;

    target->AddThreat(caster, float(damage) * float(bonus) / 100.0f, spellInfo->GetSchoolMask(), spellInfo);
}

// Adds stacks of Pourriture without a hit roll: the stroke that sows it already landed
void AddRot(Player* caster, Unit* target, uint8 stacks)
{
    if (!stacks)
        return;

    if (Aura* rot = target->GetAura(SPELL_POURRITURE, caster->GetGUID()))
    {
        rot->ModStackAmount(stacks);
        return;
    }

    if (Aura* rot = caster->AddAura(SPELL_POURRITURE, target); rot && stacks > 1)
        rot->ModStackAmount(stacks - 1);
}

// -----------------------------------------------------------------------------------------------------------------
// 90207 / 90208 Sépulcre - the plague of held-back damage, on its carrier and on the enemies it was handed to
// -----------------------------------------------------------------------------------------------------------------

// The spell data only gives it a slot: this script holds the damage still owed and deals it, a share per tick,
// spread over the ticks left. Each tick is exact - it was mitigated once when it was held back, so the carrier's
// damage reduction does not apply again - but shields still absorb it.
class PestifereSepulcreStoredAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereSepulcreStoredAuraScript);

public:
    // More damage held back: it joins what is owed, and the plague restarts its 12 sec
    void Store(uint32 damage)
    {
        _owed += damage;
        GetAura()->RefreshDuration();
    }

    // Handed to an enemy by Contagion: it owes what its carrier still owes
    void SetOwed(uint32 owed)
    {
        _owed = owed;
        GetAura()->RefreshDuration();
    }

    uint32 GetOwed() const { return _owed; }

private:
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        PreventDefaultAction();

        Unit* target = GetTarget();
        Unit* caster = GetCaster();
        if (!_owed || !target || !caster)
            return;

        // Ticks left including this one; the last one deals whatever remains
        int32 const amplitude = std::max(1, aurEff->GetAmplitude());
        uint32 const ticksLeft = uint32(std::max(0, GetAura()->GetDuration()) / amplitude) + 1;
        uint32 damage = (_owed + ticksLeft - 1) / ticksLeft;
        _owed -= std::min(damage, _owed);

        SpellInfo const* spellInfo = GetSpellInfo();
        DamageInfo damageInfo(caster, target, damage, spellInfo, spellInfo->GetSchoolMask(), DOT);
        Unit::CalcAbsorbResist(damageInfo);
        uint32 absorb = damageInfo.GetAbsorb();
        damage = damageInfo.GetDamage();
        Unit::DealDamageMods(target, damage, &absorb);

        uint32 const overkill = damage > target->GetHealth() ? damage - target->GetHealth() : 0;
        SpellPeriodicAuraLogInfo log(aurEff, damage, overkill, absorb, damageInfo.GetResist(), 0.0f, false);
        target->SendPeriodicAuraLog(&log);

        if (Player* pestifere = GetPestifere(caster); pestifere && target != caster)
            AddPlagueThreat(pestifere, target, damage, spellInfo);

        CleanDamage cleanDamage(0, absorb, BASE_ATTACK, MELEE_HIT_NORMAL);
        Unit::DealDamage(caster, target, damage, &cleanDamage, DOT, spellInfo->GetSchoolMask(), spellInfo, true);
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(PestifereSepulcreStoredAuraScript::HandlePeriodic, EFFECT_0,
            SPELL_AURA_PERIODIC_DAMAGE);
    }

    uint32 _owed = 0;
};

PestifereSepulcreStoredAuraScript* GetSepulcrePlague(Aura* aura)
{
    return aura ? aura->GetScript<PestifereSepulcreStoredAuraScript>("PestifereSepulcreStoredAuraScript") : nullptr;
}

// What Sépulcre still owes its carrier, 0 when it holds nothing
uint32 GetCarriedSepulcreOwed(Unit* unit)
{
    PestifereSepulcreStoredAuraScript const* plague =
        GetSepulcrePlague(unit->GetAura(SPELL_SEPULCRE_STORED, unit->GetGUID()));
    return plague ? plague->GetOwed() : 0;
}

// -----------------------------------------------------------------------------------------------------------------
// Spreading and detonating, shared by Contagion, Charnier ambulant and Détonation (and its chain)
// -----------------------------------------------------------------------------------------------------------------

struct SpreadResult
{
    uint8 applied = 0;
    uint8 refused = 0;
};

// Hands the enemy version of every plague the caster carries to `enemy`, Sépulcre's included
SpreadResult SpreadPlagues(Player* caster, Unit* enemy)
{
    SpreadResult result;
    for (Plague const& plague : Plagues)
    {
        if (!CarriesOwnPlague(caster, plague.selfSpellId))
            continue;

        if (caster->AddAura(plague.enemySpellId, enemy))
            ++result.applied;
        else
            ++result.refused;
    }

    // The enemy owes what the carrier still owes; the carrier keeps paying its own
    if (uint32 const owed = GetCarriedSepulcreOwed(caster))
    {
        if (PestifereSepulcreStoredAuraScript* copy =
            GetSepulcrePlague(caster->AddAura(SPELL_SEPULCRE_STORED_ENEMY, enemy)))
        {
            copy->SetOwed(owed);
            ++result.applied;
        }
        else
            ++result.refused;
    }

    return result;
}

bool CarriesAnyPlague(Player* caster)
{
    return GetVirulence(caster) || GetCarriedSepulcreOwed(caster);
}

// How much there is to reap on an enemy: stacks weigh most, then plagues. 0 when nothing was sown.
uint32 GetRipeness(Player* caster, Unit* target)
{
    ObjectGuid const casterGuid = caster->GetGUID();
    Aura const* rot = target->GetAura(SPELL_POURRITURE, casterGuid);
    uint32 ripeness = rot ? rot->GetStackAmount() * 10 : 0;

    for (Plague const& plague : Plagues)
        if (target->HasAura(plague.enemySpellId, casterGuid))
            ++ripeness;

    if (target->HasAura(SPELL_SEPULCRE_STORED_ENEMY, casterGuid))
        ++ripeness;

    return ripeness;
}

// Consumes what the caster sowed on the target and returns the explosion's damage, 0 when nothing was sown
uint32 Detonate(Player* caster, Unit* target, bool& ripe)
{
    ObjectGuid const casterGuid = caster->GetGUID();
    Aura* rot = target->GetAura(SPELL_POURRITURE, casterGuid);
    uint8 const stacks = rot ? rot->GetStackAmount() : 0;

    uint8 plagues = 0;
    for (Plague const& plague : Plagues)
        if (target->HasAura(plague.enemySpellId, casterGuid))
            ++plagues;

    // Sépulcre's plague counts as a plague consumed, and what it still owed goes off in the blast
    uint32 owed = 0;
    if (Aura* stored = target->GetAura(SPELL_SEPULCRE_STORED_ENEMY, casterGuid))
    {
        ++plagues;
        if (PestifereSepulcreStoredAuraScript const* plague = GetSepulcrePlague(stored))
            owed = plague->GetOwed();
    }

    ripe = stacks >= POURRITURE_MAX_STACKS;
    if (!stacks && !plagues)
        return 0;

    float const attackPower = caster->GetTotalAttackPowerValue(BASE_ATTACK);
    float const damage = attackPower * DETONATION_BASE_AP_COEFF +
        (float(stacks) * attackPower * DETONATION_STACK_AP_COEFF) * (1.0f + DETONATION_PLAGUE_BONUS * float(plagues)) +
        float(owed);

    // The rot is spent: the next detonation is only as big as the work put in between. An Avatar de la peste keeps
    // it: the pack goes on ripening while it lasts.
    if (!caster->HasAura(SPELL_AVATAR_DE_LA_PESTE))
        target->RemoveAura(SPELL_POURRITURE, casterGuid);
    for (Plague const& plague : Plagues)
        target->RemoveAura(plague.enemySpellId, casterGuid);
    target->RemoveAura(SPELL_SEPULCRE_STORED_ENEMY, casterGuid);

    return uint32(std::max(1.0f, damage));
}

// -----------------------------------------------------------------------------------------------------------------
// 90200 Frappe putride - Fossoyeur (two-hand: heavier, a second stack), Contagion galopante (may reset Contagion)
// and Pandémie (strikes 3 more enemies)
// -----------------------------------------------------------------------------------------------------------------

class PestifereFrappePutrideSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereFrappePutrideSpellScript);

    void HandleHit()
    {
        Player* caster = GetPestifere(GetCaster());
        Unit* target = GetHitUnit();
        if (!caster || !target)
            return;

        if (int32 const bonus = GetTalentValue(caster, TALENT_FOSSOYEUR); bonus && IsWieldingTwoHand(caster))
        {
            SetHitDamage(GetHitDamage() + int32(CalculatePct(GetHitDamage(), bonus)));
            // The strike's own stack comes from its trigger effect; this is the second one
            AddRot(caster, target, 1);
        }

        if (int32 const chance = GetTalentValue(caster, TALENT_CONTAGION_GALOPANTE); chance && roll_chance_i(chance))
            caster->RemoveSpellCooldown(SPELL_CONTAGION, true);

        // Pandémie: the same strike (without its cost or cooldown) lands on the enemies around
        if (!caster->HasAura(SPELL_PANDEMIE))
            return;

        uint32 struck = 0;
        for (Unit* enemy : GetEnemiesInRange(caster, PANDEMIE_RADIUS))
        {
            if (enemy == target)
                continue;

            caster->CastSpell(enemy, SPELL_FRAPPE_PUTRIDE_ECHO, true);
            if (++struck >= PANDEMIE_EXTRA_TARGETS)
                break;
        }
    }

    void Register() override
    {
        OnHit += SpellHitFn(PestifereFrappePutrideSpellScript::HandleHit);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90243-90245 Mains putrides - off-hand hits sow Pourriture (the proc chance per rank is in the spell data)
// -----------------------------------------------------------------------------------------------------------------

class PestifereMainsPutridesAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereMainsPutridesAuraScript);

    bool CheckProc(ProcEventInfo& eventInfo)
    {
        Unit* target = eventInfo.GetActionTarget();
        return GetPestifere(GetTarget()) && target && target != GetTarget() && target->IsAlive() &&
            eventInfo.GetDamageInfo();
    }

    void HandleProc(AuraEffect const* /*aurEff*/, ProcEventInfo& eventInfo)
    {
        PreventDefaultAction();
        if (Player* caster = GetPestifere(GetTarget()))
            AddRot(caster, eventInfo.GetActionTarget(), 1);
    }

    void Register() override
    {
        DoCheckProc += AuraCheckProcFn(PestifereMainsPutridesAuraScript::CheckProc);
        OnEffectProc += AuraEffectProcFn(PestifereMainsPutridesAuraScript::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90205 Pourriture - Fièvre: each tick may make the next Morsure fétide free and ready
// -----------------------------------------------------------------------------------------------------------------

class PestiferePourritureAuraScript : public AuraScript
{
    PrepareAuraScript(PestiferePourritureAuraScript);

    void HandlePeriodic(AuraEffect const* /*aurEff*/)
    {
        Player* caster = GetPestifere(GetCaster());
        if (!caster)
            return;

        int32 const chance = GetTalentValue(caster, TALENT_FIEVRE);
        if (!chance || !roll_chance_i(chance))
            return;

        caster->AddAura(SPELL_FIEVRE, caster);
        caster->RemoveSpellCooldown(SPELL_MORSURE_FETIDE, true);
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(PestiferePourritureAuraScript::HandlePeriodic, EFFECT_0,
            SPELL_AURA_PERIODIC_DAMAGE);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90224 Morsure fétide - the single-target threat strike, heavier for every Pourriture on the target
// -----------------------------------------------------------------------------------------------------------------

class PestifereMorsureFetideSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereMorsureFetideSpellScript);

    void HandleHit()
    {
        Player* caster = GetPestifere(GetCaster());
        Unit* target = GetHitUnit();
        if (!caster || !target)
            return;

        // It feeds on the rot without spending it: Détonation still gets every stack
        Aura const* rot = target->GetAura(SPELL_POURRITURE, caster->GetGUID());
        if (int32 const stacks = rot ? rot->GetStackAmount() : 0)
            SetHitDamage(GetHitDamage() + int32(CalculatePct(GetHitDamage(), stacks * MORSURE_DAMAGE_PER_STACK)));
    }

    // Fièvre made this one free: it is spent
    void HandleAfterCast()
    {
        if (Unit* caster = GetCaster())
            caster->RemoveAura(SPELL_FIEVRE);
    }

    void Register() override
    {
        OnHit += SpellHitFn(PestifereMorsureFetideSpellScript::HandleHit);
        AfterCast += SpellCastFn(PestifereMorsureFetideSpellScript::HandleAfterCast);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90225 Riposte purulente - the answer to a dodge or parry: a strike that rots its target and the enemies around
// -----------------------------------------------------------------------------------------------------------------

class PestifereRipostePurulenteSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereRipostePurulenteSpellScript);

    void HandleHit()
    {
        Player* caster = GetPestifere(GetCaster());
        Unit* target = GetHitUnit();
        if (!caster || !target)
            return;

        // Riposte fétide: more damage, and more enemies rotted
        int32 const points = GetTalentValue(caster, TALENT_RIPOSTE_FETIDE);
        if (points)
            SetHitDamage(GetHitDamage() +
                int32(CalculatePct(GetHitDamage(), points * RIPOSTE_FETIDE_DAMAGE_PER_POINT)));

        AddRot(caster, target, 1);

        uint32 const extraTargets = RIPOSTE_EXTRA_TARGETS + uint32(points);
        uint32 rotted = 0;
        for (Unit* enemy : GetEnemiesAround(caster, target, RIPOSTE_RADIUS))
        {
            if (enemy == target)
                continue;

            AddRot(caster, enemy, 1);
            if (++rotted >= extraTargets)
                break;
        }
    }

    void Register() override
    {
        OnHit += SpellHitFn(PestifereRipostePurulenteSpellScript::HandleHit);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90223 Flaque de bile - the pool at the caster's feet: damage and a stack of Pourriture on every tick, and Bile
// corrosive's damage reduction on whoever stands in it
// -----------------------------------------------------------------------------------------------------------------

class PestifereFlaqueDeBileAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereFlaqueDeBileAuraScript);

    void CalculateDamage(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        if (Unit* caster = GetCaster())
            amount = std::max<int32>(1, int32(caster->GetTotalAttackPowerValue(BASE_ATTACK) * FLAQUE_TICK_AP_COEFF));
    }

    void CalculateDamageDone(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        amount = -GetTalentValue(GetCaster(), TALENT_BILE_CORROSIVE);
    }

    void HandlePeriodic(AuraEffect const* /*aurEff*/)
    {
        Player* caster = GetPestifere(GetCaster());
        Unit* target = GetTarget();
        if (caster && target && target->IsAlive())
            AddRot(caster, target, 1);
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereFlaqueDeBileAuraScript::CalculateDamage, EFFECT_0,
            SPELL_AURA_PERIODIC_DAMAGE);
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereFlaqueDeBileAuraScript::CalculateDamageDone, EFFECT_1,
            SPELL_AURA_MOD_DAMAGE_PERCENT_DONE);
        OnEffectPeriodic += AuraEffectPeriodicFn(PestifereFlaqueDeBileAuraScript::HandlePeriodic, EFFECT_0,
            SPELL_AURA_PERIODIC_DAMAGE);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90226 Carapace suintante - the short defensive: an absorb that grows with Virulence (and Pus épais)
// -----------------------------------------------------------------------------------------------------------------

class PestifereCarapaceSuintanteAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereCarapaceSuintanteAuraScript);

    void CalculateAbsorb(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        Unit* owner = GetUnitOwner();
        if (!owner)
            return;

        uint32 const percent = SUINTANTE_ABSORB_PCT_BASE + SUINTANTE_ABSORB_PCT_STEP * GetVirulence(owner);
        uint32 absorb = CalculatePct(owner->GetMaxHealth(), percent);
        absorb += CalculatePct(absorb, GetTalentValue(owner, TALENT_PUS_EPAIS));
        amount = int32(absorb);
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereCarapaceSuintanteAuraScript::CalculateAbsorb, EFFECT_0,
            SPELL_AURA_SCHOOL_ABSORB);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90227 Bond putride - the leap lands with a stack of Pourriture (the rage is spell data)
// -----------------------------------------------------------------------------------------------------------------

class PestifereBondPutrideSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereBondPutrideSpellScript);

    void HandleHit()
    {
        Player* caster = GetPestifere(GetCaster());
        if (Unit* target = GetHitUnit(); caster && target)
            AddRot(caster, target, 1);
    }

    void Register() override
    {
        AfterHit += SpellHitFn(PestifereBondPutrideSpellScript::HandleHit);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90284 Vomissure - a cone of bile: heavy damage and two stacks of Pourriture on every enemy caught
// -----------------------------------------------------------------------------------------------------------------

class PestifereVomissureSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereVomissureSpellScript);

    void HandleDamage(SpellEffIndex /*effIndex*/)
    {
        Player* caster = GetPestifere(GetCaster());
        Unit* target = GetHitUnit();
        if (!caster || !target)
            return;

        SetHitDamage(std::max<int32>(1, int32(caster->GetTotalAttackPowerValue(BASE_ATTACK) * VOMISSURE_AP_COEFF)));
        AddRot(caster, target, VOMISSURE_ROT_STACKS);
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(PestifereVomissureSpellScript::HandleDamage, EFFECT_0,
            SPELL_EFFECT_SCHOOL_DAMAGE);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90287 Avatar de la peste - counts as one plague more while it lasts: the carried plagues rescale at once
// -----------------------------------------------------------------------------------------------------------------

class PestifereAvatarDeLaPesteAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereAvatarDeLaPesteAuraScript);

    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        RecalculatePlagues(GetUnitOwner());
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        RecalculatePlagues(GetUnitOwner());
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(PestifereAvatarDeLaPesteAuraScript::HandleApply, EFFECT_0,
            SPELL_AURA_MOD_SCALE, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(PestifereAvatarDeLaPesteAuraScript::HandleRemove, EFFECT_0,
            SPELL_AURA_MOD_SCALE, AURA_EFFECT_HANDLE_REAL);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90201 Contagion - hands the enemy version of every plague carried to the pack, refreshes the carrier's own
// -----------------------------------------------------------------------------------------------------------------

class PestifereContagionSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereContagionSpellScript);

    void HandleAfterCast()
    {
        Player* caster = GetPestifere(GetCaster());
        if (!caster || !CarriesAnyPlague(caster))
            return;

        SpellInfo const* spellInfo = GetSpellInfo();
        ObjectGuid const casterGuid = caster->GetGUID();

        // The spell's own area radius (effect 2, cloned from Pestilence: 10 yd). CalcRadius applies the caster's
        // radius modifiers, which is how the Miasme talent widens it; a fixed radius here would ignore them.
        float const radius = spellInfo->Effects[EFFECT_2].CalcRadius(caster);
        std::list<Unit*> const enemies = GetEnemiesInRange(caster, radius);
        uint32 applied = 0;
        uint32 refused = 0;

        for (Unit* enemy : enemies)
        {
            SpreadResult const spread = SpreadPlagues(caster, enemy);
            applied += spread.applied;
            refused += spread.refused;

            // Contagion also keeps the rot already on the pack alive, so a pack held long enough ripens
            if (Aura* rot = enemy->GetAura(SPELL_POURRITURE, casterGuid))
                rot->RefreshDuration();

            if (!spread.applied)
                continue;

            caster->SetInCombatWith(enemy);
            enemy->AddThreat(caster, CONTAGION_THREAT_PER_PLAGUE * float(spread.applied), SPELL_SCHOOL_MASK_NORMAL,
                spellInfo);
        }

        // Feeding the pack feeds the carrier: plagues never time out while Contagion keeps landing. Sépulcre's
        // plague is not refreshed: that would only stretch the damage it owes.
        for (Plague const& plague : Plagues)
            if (Aura* carried = caster->GetAura(plague.selfSpellId, casterGuid))
                carried->RefreshDuration();

        // How far a cast actually reached: the evidence for tuning the radius. Refused means an enemy in range
        // that did not take a plague (an immunity, or an aura the core would not apply).
        LOG_INFO("module", "Pestifere: {} cast Contagion ({:.1f} yd, Virulence {}): {} enemies in range, {} plagues "
            "applied, {} refused", caster->GetName(), radius, GetVirulence(caster), enemies.size(), applied, refused);
    }

    void Register() override
    {
        AfterCast += SpellCastFn(PestifereContagionSpellScript::HandleAfterCast);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90256 Charnier ambulant - infects everything around with every plague carried, and ripens it at once
// -----------------------------------------------------------------------------------------------------------------

class PestifereCharnierAmbulantSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereCharnierAmbulantSpellScript);

    void HandleHit(SpellEffIndex /*effIndex*/)
    {
        Player* caster = GetPestifere(GetCaster());
        Unit* enemy = GetHitUnit();
        if (!caster || !enemy)
            return;

        SpreadPlagues(caster, enemy);
        AddRot(caster, enemy, POURRITURE_MAX_STACKS);

        caster->SetInCombatWith(enemy);
        enemy->AddThreat(caster, CHARNIER_THREAT_PER_ENEMY, SPELL_SCHOOL_MASK_NORMAL, GetSpellInfo());
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(PestifereCharnierAmbulantSpellScript::HandleHit, EFFECT_0,
            SPELL_EFFECT_DUMMY);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90202 Détonation - consumes Pourriture stacks and plagues on the pack, heals per enemy detonated
// -----------------------------------------------------------------------------------------------------------------

class PestifereDetonationSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereDetonationSpellScript);

    void HandleDamage(SpellEffIndex effIndex)
    {
        Player* caster = GetPestifere(GetCaster());
        Unit* target = GetHitUnit();
        if (!caster || !target)
            return;

        _inBlast.insert(target->GetGUID());

        bool ripe = false;
        uint32 const damage = Detonate(caster, target, ripe);

        // Nothing sown on this one, nothing to reap: it is in the blast but takes none of it
        if (!damage)
        {
            PreventHitDefaultEffect(effIndex);
            PreventHitDamage();
            return;
        }

        SetHitDamage(int32(damage));
        _exploded.push_back(target->GetGUID());
        Count(ripe);
    }

    // Détonation en chaîne: the blast jumps to the ripest enemies just outside it, near one that exploded
    void Chain(Player* caster)
    {
        int32 const jumps = GetTalentValue(caster, TALENT_DETONATION_EN_CHAINE);
        if (!jumps || _exploded.empty())
            return;

        std::vector<std::pair<uint32, Unit*>> candidates;
        for (ObjectGuid const& guid : _exploded)
        {
            Unit* origin = ObjectAccessor::GetUnit(*caster, guid);
            if (!origin)
                continue;

            for (Unit* enemy : GetEnemiesAround(caster, origin, DETONATION_CHAIN_RADIUS))
            {
                if (!_inBlast.insert(enemy->GetGUID()).second)
                    continue;

                if (uint32 const ripeness = GetRipeness(caster, enemy))
                    candidates.emplace_back(ripeness, enemy);
            }
        }

        std::stable_sort(candidates.begin(), candidates.end(),
            [](auto const& left, auto const& right) { return left.first > right.first; });

        for (std::size_t index = 0; index < candidates.size() && index < std::size_t(jumps); ++index)
        {
            Unit* enemy = candidates[index].second;
            bool ripe = false;
            if (uint32 const damage = Detonate(caster, enemy, ripe))
            {
                caster->CastCustomSpell(SPELL_DETONATION_CHAIN, SPELLVALUE_BASE_POINT0, int32(damage), enemy,
                    TRIGGERED_FULL_MASK);
                Count(ripe);
            }
        }
    }

    void HandleAfterCast()
    {
        Player* caster = GetPestifere(GetCaster());
        if (!caster)
            return;

        Chain(caster);
        if (!_detonated)
            return;

        // Detonating a ripe pack is the class's biggest self-heal: AoE threat and survival are one button
        SpellInfo const* spellInfo = GetSpellInfo();
        uint32 const healPerTarget =
            uint32(float(caster->GetMaxHealth()) * DETONATION_HEAL_PCT_PER_TARGET / 100.0f);
        uint32 const healing = std::max<uint32>(1, healPerTarget * _detonated);
        HealInfo healInfo(caster, caster, healing, spellInfo, SpellSchoolMask(spellInfo->SchoolMask));
        caster->HealBySpell(healInfo);

        GiveRage(caster, _rageRefund);
    }

    void Count(bool ripe)
    {
        ++_detonated;
        if (ripe)
            _rageRefund += DETONATION_RIPE_RAGE_REFUND;
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(PestifereDetonationSpellScript::HandleDamage, EFFECT_0,
            SPELL_EFFECT_SCHOOL_DAMAGE);
        AfterCast += SpellCastFn(PestifereDetonationSpellScript::HandleAfterCast);
    }

private:
    GuidSet _inBlast;
    std::vector<ObjectGuid> _exploded;
    uint32 _detonated = 0;
    uint32 _rageRefund = 0;
};

// -----------------------------------------------------------------------------------------------------------------
// 90265 Purge cathartique - eats the carried plagues for a large heal: the escape valve, paid in mitigation
// -----------------------------------------------------------------------------------------------------------------

class PestiferePurgeCathartiqueSpellScript : public SpellScript
{
    PrepareSpellScript(PestiferePurgeCathartiqueSpellScript);

    SpellCastResult CheckCast()
    {
        return GetVirulence(GetCaster()) ? SPELL_CAST_OK : SPELL_FAILED_CASTER_AURASTATE;
    }

    void HandlePurge(SpellEffIndex /*effIndex*/)
    {
        Player* caster = GetPestifere(GetCaster());
        if (!caster)
            return;

        // The three plagues only: Sépulcre's damage is owed, and purging is not a way out of it
        uint32 purged = 0;
        for (Plague const& plague : Plagues)
        {
            if (!CarriesOwnPlague(caster, plague.selfSpellId))
                continue;

            caster->RemoveAura(plague.selfSpellId, caster->GetGUID());
            ++purged;
        }

        if (!purged)
            return;

        SpellInfo const* spellInfo = GetSpellInfo();
        uint32 const healing = CalculatePct(caster->GetMaxHealth(), PURGE_HEAL_PCT_PER_PLAGUE * purged);
        HealInfo healInfo(caster, caster, healing, spellInfo, SpellSchoolMask(spellInfo->SchoolMask));
        caster->HealBySpell(healInfo);
    }

    void Register() override
    {
        OnCheckCast += SpellCheckCastFn(PestiferePurgeCathartiqueSpellScript::CheckCast);
        OnEffectHitTarget += SpellEffectFn(PestiferePurgeCathartiqueSpellScript::HandlePurge, EFFECT_0,
            SPELL_EFFECT_DUMMY);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90268 Sépulcre - for 8 sec, half of every hit is held back into the stored plague instead of being taken
// -----------------------------------------------------------------------------------------------------------------

class PestifereSepulcreAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereSepulcreAuraScript);

    // Unlimited: the absorb itself decides how much of each hit it takes
    void CalculateAmount(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        amount = -1;
    }

    void Absorb(AuraEffect* /*aurEff*/, DamageInfo& damageInfo, uint32& absorbAmount)
    {
        absorbAmount = 0;

        // The held-back damage coming due is not held back a second time
        SpellInfo const* source = damageInfo.GetSpellInfo();
        if (source && source->Id == SPELL_SEPULCRE_STORED)
            return;

        absorbAmount = CalculatePct(damageInfo.GetDamage(), SEPULCRE_HELD_PCT);
    }

    void StoreAbsorbed(AuraEffect* /*aurEff*/, DamageInfo& /*damageInfo*/, uint32& absorbAmount)
    {
        Unit* owner = GetTarget();
        if (!absorbAmount || !owner)
            return;

        Aura* stored = owner->GetAura(SPELL_SEPULCRE_STORED, owner->GetGUID());
        if (!stored)
            stored = owner->AddAura(SPELL_SEPULCRE_STORED, owner);

        if (PestifereSepulcreStoredAuraScript* plague = GetSepulcrePlague(stored))
            plague->Store(absorbAmount);
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereSepulcreAuraScript::CalculateAmount, EFFECT_0,
            SPELL_AURA_SCHOOL_ABSORB);
        OnEffectAbsorb += AuraEffectAbsorbFn(PestifereSepulcreAuraScript::Absorb, EFFECT_0);
        AfterEffectAbsorb += AuraEffectAbsorbFn(PestifereSepulcreAuraScript::StoreAbsorbed, EFFECT_0);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90211 Carapace nécrosée - the mitigation plague (Croûte nécrosée and Résilience du porteur deepen it)
// -----------------------------------------------------------------------------------------------------------------

class PestifereCarapaceNecroseeAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereCarapaceNecroseeAuraScript);

    void CalculateDamageTaken(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
    {
        canBeRecalculated = true;

        Unit* owner = GetUnitOwner();
        uint8 const virulence = GetVirulence(owner);
        int32 reduction = ScaleByVirulence(virulence, CARAPACE_DAMAGE_REDUCTION_BASE, CARAPACE_DAMAGE_REDUCTION_STEP);
        // Croûte nécrosée: a further reduction per plague carried
        reduction += GetTalentValue(owner, TALENT_CROUTE_NECROSEE) * int32(virulence);
        // Résilience du porteur: carrying all three, this plague is among them, so it carries the bonus
        if (virulence >= uint8(Plagues.size()))
            reduction += GetTalentValue(owner, TALENT_RESILIENCE_DU_PORTEUR);

        amount = -reduction;
    }

    void CalculateArmor(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
    {
        canBeRecalculated = true;
        amount = ScaleByVirulence(GetVirulence(GetUnitOwner()), CARAPACE_ARMOR_BASE, CARAPACE_ARMOR_STEP);
    }

    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        Unit* owner = GetUnitOwner();
        RecalculatePlagues(owner);
        if (!owner)
            return;

        // The mitigation plague is the tank's presence: carrying it doubles the threat generated
        owner->AddAura(SPELL_CARAPACE_THREAT, owner);
        // Inoculated outside a fight: it starts running down at once, instead of staying on forever
        if (!owner->IsInCombat())
            SetPlagueExpiring(GetAura(), true);
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        Unit* owner = GetUnitOwner();
        RecalculatePlagues(owner, GetAura());
        if (owner)
            owner->RemoveAura(SPELL_CARAPACE_THREAT);
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereCarapaceNecroseeAuraScript::CalculateDamageTaken,
            EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN);
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereCarapaceNecroseeAuraScript::CalculateArmor,
            EFFECT_2, SPELL_AURA_MOD_RESISTANCE_PCT);
        AfterEffectApply += AuraEffectApplyFn(PestifereCarapaceNecroseeAuraScript::HandleApply,
            EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(PestifereCarapaceNecroseeAuraScript::HandleRemove,
            EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, AURA_EFFECT_HANDLE_REAL);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90213 Chair putride - the healing plague (its healing-taken penalty lives in PestifereUnitScript)
// -----------------------------------------------------------------------------------------------------------------

class PestifereChairPutrideAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereChairPutrideAuraScript);

    void CalculatePeriodicHeal(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
    {
        canBeRecalculated = true;

        Unit* owner = GetUnitOwner();
        uint8 const virulence = GetVirulence(owner);
        if (!virulence)
        {
            amount = 0;
            return;
        }

        float percent = CHAIR_HEAL_PCT_BASE + CHAIR_HEAL_PCT_STEP * float(virulence - 1);
        // Symbiose morbide: more healing per plague carried
        percent *= 1.0f + float(GetTalentValue(owner, TALENT_SYMBIOSE_MORBIDE) * virulence) / 100.0f;
        amount = std::max<int32>(1, int32(float(owner->GetMaxHealth()) * percent / 100.0f));
    }

    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        RecalculatePlagues(GetUnitOwner());
        // Inoculated outside a fight: it starts running down at once, instead of staying on forever
        if (Unit* owner = GetUnitOwner(); owner && !owner->IsInCombat())
            SetPlagueExpiring(GetAura(), true);
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        RecalculatePlagues(GetUnitOwner(), GetAura());
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereChairPutrideAuraScript::CalculatePeriodicHeal,
            EFFECT_0, SPELL_AURA_PERIODIC_HEAL);
        AfterEffectApply += AuraEffectApplyFn(PestifereChairPutrideAuraScript::HandleApply,
            EFFECT_0, SPELL_AURA_PERIODIC_HEAL, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(PestifereChairPutrideAuraScript::HandleRemove,
            EFFECT_0, SPELL_AURA_PERIODIC_HEAL, AURA_EFFECT_HANDLE_REAL);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90215 Peste virulente - the damage plague, whose self-damage escalates while it is carried alone
// -----------------------------------------------------------------------------------------------------------------

class PestiferePesteVirulenteAuraScript : public AuraScript
{
    PrepareAuraScript(PestiferePesteVirulenteAuraScript);

    void CalculateDamageDone(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
    {
        canBeRecalculated = true;
        amount = ScaleByVirulence(GetVirulence(GetUnitOwner()), PESTE_DAMAGE_DONE_BASE, PESTE_DAMAGE_DONE_STEP);
    }

    void CalculateSelfDamage(AuraEffect const* /*aurEff*/, int32& amount, bool& canBeRecalculated)
    {
        canBeRecalculated = true;

        Unit* owner = GetUnitOwner();
        uint8 const virulence = GetVirulence(owner);
        if (!virulence)
        {
            amount = 0;
            return;
        }

        // Carrying it alone is the punish, and the escalation only survives while nothing else is carried:
        // this is also how adding a second plague resets it, since that recalculates every plague
        if (virulence > 1)
            _escalation = 0;

        float multiplier = 1.0f + PESTE_ESCALATION_STEP * float(_escalation);
        // Porteur endurci: the carrier has learned to live with it
        multiplier *= 1.0f - float(GetTalentValue(owner, TALENT_PORTEUR_ENDURCI)) / 100.0f;
        amount = std::max<int32>(1,
            int32(float(owner->GetMaxHealth()) * PESTE_SELF_DAMAGE_PCT / 100.0f * multiplier));
    }

    void HandlePeriodic(AuraEffect const* /*aurEff*/)
    {
        if (GetVirulence(GetUnitOwner()) == 1)
            _escalation = std::min(_escalation + 1, PESTE_ESCALATION_MAX);
        else
            _escalation = 0;

        if (AuraEffect* selfDamage = GetAura()->GetEffect(EFFECT_1))
            selfDamage->RecalculateAmount(GetCaster());
    }

    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        RecalculatePlagues(GetUnitOwner());
        // Inoculated outside a fight: it starts running down at once, instead of staying on forever
        if (Unit* owner = GetUnitOwner(); owner && !owner->IsInCombat())
            SetPlagueExpiring(GetAura(), true);
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        RecalculatePlagues(GetUnitOwner(), GetAura());
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestiferePesteVirulenteAuraScript::CalculateDamageDone,
            EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE);
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestiferePesteVirulenteAuraScript::CalculateSelfDamage,
            EFFECT_1, SPELL_AURA_PERIODIC_DAMAGE);
        OnEffectPeriodic += AuraEffectPeriodicFn(PestiferePesteVirulenteAuraScript::HandlePeriodic,
            EFFECT_1, SPELL_AURA_PERIODIC_DAMAGE);
        AfterEffectApply += AuraEffectApplyFn(PestiferePesteVirulenteAuraScript::HandleApply,
            EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(PestiferePesteVirulenteAuraScript::HandleRemove,
            EFFECT_0, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, AURA_EFFECT_HANDLE_REAL);
    }

private:
    // Ticks spent as the carrier's only plague; reset the moment a second plague joins it
    uint32 _escalation = 0;
};

// -----------------------------------------------------------------------------------------------------------------
// Damage, threat and healing the spell data cannot express
// -----------------------------------------------------------------------------------------------------------------

class PestifereUnitScript : public UnitScript
{
public:
    PestifereUnitScript() : UnitScript("PestifereUnitScript", true, {
        UNITHOOK_MODIFY_HEAL_RECEIVED,
        UNITHOOK_MODIFY_PERIODIC_DAMAGE_AURAS_TICK,
        UNITHOOK_ON_BEFORE_ROLL_MELEE_OUTCOME_AGAINST
    }) { }

    // A killing blow, seen before it lands: Charognard passes the victim's rot on, Rigor mortis saves a carrier.
    // Then Rage fielleuse and Métabolisme nécrotique turn the damage a Pestiféré takes into rage. The core already
    // pays the normal rage for a hit from someone else, and none for the carrier's own plagues.
    uint32 DealDamage(Unit* attacker, Unit* victim, uint32 damage, DamageEffectType damagetype) override
    {
        if (!victim || !damage)
            return damage;

        if (damage >= victim->GetHealth())
            PassRotOn(victim);

        Player* pestifere = GetPestifere(victim);
        if (!pestifere)
            return damage;

        if (damage >= pestifere->GetHealth() && CheatDeath(pestifere))
            damage = pestifere->GetHealth() - 1;

        int32 share = 0;
        if (attacker != victim)
            share = GetTalentValue(pestifere, TALENT_RAGE_FIELLEUSE);
        else if (damagetype == DOT)
            share = GetTalentValue(pestifere, TALENT_METABOLISME_NECROTIQUE);

        if (share)
            GiveRagePoints(pestifere, GetRageFromDamageTaken(pestifere, damage) * float(share) / 100.0f);

        return damage;
    }

    // Hôte parfait: every plague carried makes the carrier harder to hit squarely
    void OnBeforeRollMeleeOutcomeAgainst(Unit const* /*attacker*/, Unit const* victim, WeaponAttackType /*attType*/,
        int32& /*attackerMaxSkillValueForLevel*/, int32& /*victimMaxSkillValueForLevel*/,
        int32& /*attackerWeaponSkill*/, int32& /*victimDefenseSkill*/, int32& /*crit_chance*/, int32& /*miss_chance*/,
        int32& /*dodge_chance*/, int32& parry_chance, int32& /*block_chance*/) override
    {
        Player const* pestifere = victim ? victim->ToPlayer() : nullptr;
        if (!IsPestifere(pestifere))
            return;

        // The roll counts in hundredths of a percent
        parry_chance += GetTalentValue(pestifere, TALENT_HOTE_PARFAIT) * int32(GetVirulence(pestifere)) * 100;
    }

    // Pourriture and the enemy Peste virulente deal a share of the target's health (their spell data carries none),
    // then Menace contagieuse makes every plague tick on an enemy generate extra threat
    void ModifyPeriodicDamageAurasTick(Unit* target, Unit* attacker, uint32& damage,
        SpellInfo const* spellInfo) override
    {
        Player* pestifere = GetPestifere(attacker);
        if (!pestifere || !target || target == attacker || !spellInfo || !IsPlagueDamage(spellInfo->Id))
            return;

        float healthPct = 0.0f;
        uint8 stacks = 1;
        if (spellInfo->Id == SPELL_POURRITURE)
        {
            healthPct = POURRITURE_TICK_HEALTH_PCT;
            if (Aura const* rot = target->GetAura(SPELL_POURRITURE, pestifere->GetGUID()))
                stacks = rot->GetStackAmount();
        }
        else if (spellInfo->Id == SPELL_PESTE_VIRULENTE_ENEMY)
            healthPct = PESTE_ENEMY_TICK_HEALTH_PCT;

        if (healthPct > 0.0f)
        {
            float const perStack = std::min(float(target->GetMaxHealth()) * healthPct / 100.0f,
                pestifere->GetTotalAttackPowerValue(BASE_ATTACK) * PLAGUE_TICK_AP_CAP);
            damage = std::max<uint32>(1, uint32(perStack * float(stacks)));
        }

        AddPlagueThreat(pestifere, target, damage, spellInfo);
    }

    void ModifyHealReceived(Unit* target, Unit* healer, uint32& heal, SpellInfo const* /*spellInfo*/) override
    {
        if (!heal || !target || target == healer)
            return;

        // Chair putride carried: healing from others is rotten; the plague's own ticks keep the carrier alive
        if (CarriesOwnPlague(target, SPELL_CHAIR_PUTRIDE))
            heal -= heal * CHAIR_HEALING_TAKEN_PENALTY / 100;

        // Chair putride handed to an enemy: its healers get less out of it too
        if (target->HasAura(SPELL_CHAIR_PUTRIDE_ENEMY))
            heal -= heal * CHAIR_ENEMY_HEALING_PENALTY / 100;
    }

private:
    // Charognard: a share of a dying enemy's Pourriture jumps to the nearest enemy of the Pestiféré who sowed it
    static void PassRotOn(Unit* victim)
    {
        Aura const* rot = victim->GetAura(SPELL_POURRITURE);
        Player* caster = rot ? GetPestifere(rot->GetCaster()) : nullptr;
        int32 const share = GetTalentValue(caster, TALENT_CHAROGNARD);
        if (!share)
            return;

        uint8 const stacks = uint8((rot->GetStackAmount() * share + 99) / 100);
        Unit* nearest = nullptr;
        float nearestDistance = 0.0f;
        for (Unit* enemy : GetEnemiesAround(caster, victim, CHAROGNARD_RADIUS))
        {
            float const distance = victim->GetDistance(enemy);
            if (enemy != victim && (!nearest || distance < nearestDistance))
            {
                nearest = enemy;
                nearestDistance = distance;
            }
        }

        if (nearest)
            AddRot(caster, nearest, stacks);
    }

    // Rigor mortis: the blow leaves the carrier at 1 health and eats its plagues instead, once every 3 min
    static bool CheatDeath(Player* pestifere)
    {
        if (!GetTalentValue(pestifere, TALENT_RIGOR_MORTIS) || pestifere->HasAura(SPELL_RIGOR_MORTIS_COOLDOWN))
            return false;

        for (Plague const& plague : Plagues)
            pestifere->RemoveAura(plague.selfSpellId, pestifere->GetGUID());

        pestifere->AddAura(SPELL_RIGOR_MORTIS_COOLDOWN, pestifere);
        return true;
    }
};

// -----------------------------------------------------------------------------------------------------------------
// Levelling, talents and decay - the class has no trainer, and its plagues do not outlive the fight
// -----------------------------------------------------------------------------------------------------------------

class PestiferePlayerScript : public PlayerScript
{
public:
    PestiferePlayerScript() : PlayerScript("PestiferePlayerScript", {
        PLAYERHOOK_ON_LOGIN,
        PLAYERHOOK_ON_LEVEL_CHANGED,
        PLAYERHOOK_ON_PLAYER_ENTER_COMBAT,
        PLAYERHOOK_ON_PLAYER_LEAVE_COMBAT,
        PLAYERHOOK_ON_PLAYER_LEARN_TALENTS,
        PLAYERHOOK_ON_TALENTS_RESET
    }) { }

    void OnPlayerLogin(Player* player) override
    {
        LearnUnlockedAbilities(player);
    }

    void OnPlayerLevelChanged(Player* player, uint8 oldLevel) override
    {
        if (player->GetLevel() > oldLevel)
            LearnUnlockedAbilities(player);
    }

    // Back in a fight: the plagues are carried again for as long as it lasts
    void OnPlayerEnterCombat(Player* player, Unit* /*enemy*/) override
    {
        SetCarriedPlaguesExpiring(player, false);
    }

    // Out of the fight, the plagues run down: arrive at the next pack in time and you are still sick, wait
    // too long and you re-buy them at full price with no rage - the class's punish for losing the pack
    void OnPlayerLeaveCombat(Player* player) override
    {
        SetCarriedPlaguesExpiring(player, true);
    }

    // Several talents change what the carried plagues are worth: rescale them the moment the tree changes
    void OnPlayerLearnTalents(Player* player, uint32 /*talentId*/, uint32 /*talentRank*/, uint32 /*spellId*/) override
    {
        if (IsPestifere(player))
            RecalculatePlagues(player);
    }

    void OnPlayerTalentsReset(Player* player, bool /*noCost*/) override
    {
        if (IsPestifere(player))
            RecalculatePlagues(player);
    }
};
}

void AddPestifereScripts()
{
    new PestifereUnitScript();
    new PestiferePlayerScript();
    RegisterSpellScript(PestifereFrappePutrideSpellScript);
    RegisterSpellScript(PestiferePourritureAuraScript);
    RegisterSpellScript(PestifereMorsureFetideSpellScript);
    RegisterSpellScript(PestifereRipostePurulenteSpellScript);
    RegisterSpellScript(PestifereFlaqueDeBileAuraScript);
    RegisterSpellScript(PestifereCarapaceSuintanteAuraScript);
    RegisterSpellScript(PestifereBondPutrideSpellScript);
    RegisterSpellScript(PestifereVomissureSpellScript);
    RegisterSpellScript(PestifereAvatarDeLaPesteAuraScript);
    RegisterSpellScript(PestifereContagionSpellScript);
    RegisterSpellScript(PestifereCharnierAmbulantSpellScript);
    RegisterSpellScript(PestifereDetonationSpellScript);
    RegisterSpellScript(PestiferePurgeCathartiqueSpellScript);
    RegisterSpellScript(PestifereSepulcreAuraScript);
    RegisterSpellScript(PestifereSepulcreStoredAuraScript);
    RegisterSpellScript(PestifereMainsPutridesAuraScript);
    RegisterSpellScript(PestifereCarapaceNecroseeAuraScript);
    RegisterSpellScript(PestifereChairPutrideAuraScript);
    RegisterSpellScript(PestiferePesteVirulenteAuraScript);
}
