// Pestiféré (class 12) - the healer tree "Sangsue" (.agents/plans/pestifere/pestifere-healer.DESIGN.md).
//
// The healer never casts: its melee hits trade their damage for healing (Transfusion). Once a hit's damage is final
// the most injured group member is found, and the share of the hit that covers what it is missing heals it instead
// of being dealt; the combat log shows that share absorbed. A group at full health takes nothing: every hit is
// damage. Every active picks its ally itself.
//
// Spell data contract (rows generated by localTools/patchSinisterStrike.ps1):
//   90300 Transfusion         the talent rank, a dummy aura the damage hook reads
//   90301 Transfusion         never cast: the spell Transfusion's healing is logged under
//   90302 Sangsue             EFFECT_0 weapon damage, EFFECT_1 SPELL_AURA_PERIODIC_DAMAGE on the enemy (the leech)
//   90303 Saignée             one weapon damage effect; the trade reads its id
//   90304 Absorption morbide  EFFECT_0 SPELL_EFFECT_DUMMY on the caster
//   90305 Don de sang         EFFECT_0 SPELL_EFFECT_DUMMY on the caster
//   90306 Symbiote            EFFECT_0 SPELL_EFFECT_DUMMY on the caster; puts 90307 on the chosen ally
//   90307 Symbiote            EFFECT_0 dummy, EFFECT_1 SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN (Sang de l'hôte)
//   90308 Pestilence salvatrice  a dummy aura on the caster the trade reads
//   90309 Coagulation         EFFECT_0 SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN on the ally healed
//   90310 Réserve de sang     a dummy aura on the caster while hits are banked
//   90311 Contagion bénigne   never cast: names the healing Contagion gives (PestifereScripts.cpp)
//   90312 Spores              EFFECT_0 SPELL_AURA_PERIODIC_HEAL on the ally (a proc of Transfusion)
//   90313 / 90314             never cast: name the Pustule éclatante and Essaim procs' healing
//   90315 Brume pestilentielle   EFFECT_0 SPELL_EFFECT_DUMMY on the caster; puts 90316 on the group around
//   90316 Brume pestilentielle   EFFECT_0 SPELL_AURA_PERIODIC_HEAL on a group member
//   90317 Caillot             EFFECT_0 SPELL_AURA_SCHOOL_ABSORB on the Symbiote's bearer, its amount set here
//   90318 Hémostase           a dummy aura on the healer, a stack per hit left to triple

#include "Pestifere.h"

#include "GameTime.h"
#include "Group.h"
#include "ObjectAccessor.h"
#include "Player.h"
#include "PlayerScript.h"
#include "Random.h"
#include "ScriptMgr.h"
#include "SharedDefines.h"
#include "SpellAuraEffects.h"
#include "SpellAuras.h"
#include "SpellInfo.h"
#include "SpellMgr.h"
#include "SpellScript.h"
#include "ThreatManager.h"
#include "Unit.h"
#include "UnitScript.h"

#include <algorithm>
#include <cmath>

using namespace Pestifere;

namespace
{
// -----------------------------------------------------------------------------------------------------------------
// Tuning
// -----------------------------------------------------------------------------------------------------------------

// Healing per point of damage traded, before talents
constexpr float TRANSFUSION_HEAL_RATIO = 1.0f;
// Healing threat per point restored, as for any heal
constexpr float HEALING_THREAT = 0.5f;
// Saignée's trade reaches this many injured allies, Pestilence salvatrice's this many (and doubles the healing)
constexpr std::size_t SAIGNEE_TARGETS = 3;
constexpr std::size_t PESTILENCE_TARGETS = 5;
constexpr float PESTILENCE_HEAL_MULTIPLIER = 2.0f;
// Réserve de sang holds at most this share of the healer's maximum health
constexpr uint32 RESERVE_MAX_HEALTH_PCT = 20;
// Symbiote copies this share of Transfusion healing without Symbiose parfaite
constexpr int32 SYMBIOTE_BASE_PCT = 25;
// How far from the healer the Symbiote's bearer still gets its share
constexpr float SYMBIOTE_RANGE = 100.0f;

// Sangsue (90302): each 2 sec drain as a share of attack power, and the healing per point drained
constexpr float SANGSUE_TICK_AP_COEFF = 0.10f;
constexpr float SANGSUE_HEAL_RATIO = 1.5f;
// Sangsue prolifère: how far the leech can jump from the enemy that died
constexpr float SANGSUE_JUMP_RADIUS = 10.0f;

// Absorption morbide (90304): % of maximum health healed per effect drawn out
constexpr uint32 ABSORPTION_HEAL_PCT_PER_EFFECT = 5;

// Don de sang (90305): % of the caster's maximum health paid, % of the ally's restored
constexpr uint32 DON_DE_SANG_COST_PCT = 8;
constexpr uint32 DON_DE_SANG_HEAL_PCT = 25;

// Triage: an ally under this health percentage is healed more
constexpr int32 TRIAGE_HEALTH_PCT = 35;

// Transfusion's procs, rolled on every melee hit while someone is injured. They heal on top of the trade (and
// before it, so the trade only buys what they left missing).
// Spores (90312): % chance, and each 2 sec tick of the 10 sec heal over time as a share of attack power
constexpr int32 SPORES_CHANCE = 25;
constexpr float SPORES_TICK_AP_COEFF = 0.12f;
// Pustule éclatante (90313): % chance, the heal on the most injured ally as a share of attack power, and the share
// of it that splashes on the group members around that ally
constexpr int32 PUSTULE_CHANCE = 10;
constexpr float PUSTULE_AP_COEFF = 0.8f;
constexpr uint32 PUSTULE_SPLASH_PCT = 40;
constexpr float PUSTULE_SPLASH_RADIUS = 10.0f;
// Essaim (90314): % chance, each heal as a share of attack power, and the bounces after the first ally
constexpr int32 ESSAIM_CHANCE = 10;
constexpr float ESSAIM_AP_COEFF = 0.3f;
constexpr uint32 ESSAIM_BOUNCES = 2;
constexpr Milliseconds ESSAIM_BOUNCE_DELAY = 400ms;

// Brume pestilentielle (90315): reach, and % of maximum health each 2 sec tick of its 12 sec heal over time restores
constexpr float BRUME_RANGE = 30.0f;
constexpr float BRUME_TICK_HEALTH_PCT = 2.0f;

// Burst healing (pestifere-healer.DESIGN.md section 6): the answers to a tank buster and to a short AoE pulse.
// Caillot (90317): this share of all the healer's healing forms an absorb on the Symbiote's bearer, up to this share
// of the bearer's maximum health
constexpr uint32 CAILLOT_HEALING_SHARE_PCT = 20;
constexpr uint32 CAILLOT_MAX_HEALTH_PCT = 15;
// Hémostase (90318): an ally under this health percentage makes the healer's next hits heal this many times as much,
// that many hits, at most once in that long
constexpr int32 EMERGENCY_HEALTH_PCT = 35;
constexpr float HEMOSTASE_HEAL_MULTIPLIER = 3.0f;
constexpr uint8 HEMOSTASE_CHARGES = 3;
constexpr uint32 HEMOSTASE_COOLDOWN_MS = 20 * IN_MILLISECONDS;
// Brume pestilentielle: % of maximum health healed at once, before its heal over time
constexpr uint32 BRUME_INSTANT_HEALTH_PCT = 10;
// Don de sang: % of maximum health restored to an ally under EMERGENCY_HEALTH_PCT (DON_DE_SANG_HEAL_PCT otherwise)
constexpr uint32 DON_DE_SANG_EMERGENCY_HEAL_PCT = 40;

// No cap on how many injured allies a lookup returns (a raid is 40)
constexpr std::size_t ANY_NUMBER_OF_ALLIES = 40;

// SpellVisualKit ids played on the ally a proc heals (the procs are never cast, so they carry no visual of their own).
// All plague and ooze kits from Icecrown Citadel's Plagueworks (Festergut, Rotface, Putricide): nothing holy.
constexpr uint32 KIT_SPORES = 13730;         // Festergut's Gaseous Blight spore burst
constexpr uint32 KIT_PUSTULE = 14119;        // Festergut's Gastric Explosion gas nova
constexpr uint32 KIT_PUSTULE_SPLASH = 14079; // Rotface's Expunged Gas impact
constexpr uint32 KIT_ESSAIM = 276;           // Hell Rot's disease cloud, as the swarm lands
constexpr uint32 KIT_BRUME = 13933;          // Putricide's Choking Gas spore impact
// The same for the healing that comes from hits and actives: every heal is heard where it lands
constexpr uint32 KIT_TRANSFUSION = 14045;    // Putricide's Slime Puddle spore impact (low volume: it plays often)
constexpr uint32 KIT_SANGSUE = 13595;        // Rotface's Weak Radiating Ooze impact (low volume)
constexpr uint32 KIT_DON_DE_SANG = 10287;    // Death Pact's target burst
constexpr uint32 KIT_ABSORPTION = 3031;      // Malleable Goo's poison cloud
constexpr uint32 KIT_SYMBIOTE = 14148;       // Putricide's Mutated Plague impact
// Transfusion trades on every hit (two weapons, Pandémie's echoes): its kit plays at most this often per healer
constexpr uint32 TRANSFUSION_KIT_INTERVAL_MS = 800;

// -----------------------------------------------------------------------------------------------------------------
// Per-healer state, kept on the player (map updates run in parallel, so no shared table)
// -----------------------------------------------------------------------------------------------------------------

struct HealerData : public DataMap::Base
{
    // Réserve de sang: healing banked while nobody needed it
    uint32 reserve = 0;
    // The ally carrying this healer's Symbiote
    ObjectGuid symbioteBearer;
    // Game time of the last Transfusion kit played (see TRANSFUSION_KIT_INTERVAL_MS)
    uint32 lastTransfusionKit = 0;
    // Game time from which Hémostase may trigger again
    uint32 hemostaseReadyAt = 0;
};

HealerData* GetHealerData(Player* healer)
{
    return healer->CustomData.GetDefault<HealerData>("PestifereHealer");
}

Player* AsPestifere(Unit* unit)
{
    Player* player = unit ? unit->ToPlayer() : nullptr;
    return IsPestifere(player) ? player : nullptr;
}

// Transfusion works for a healer who learned it, and sleeps while it carries the tank plague: a tank that took
// points in this tree keeps its damage, which is its threat
bool IsTransfusionActive(Player const* healer)
{
    return GetTalentValue(healer, TALENT_TRANSFUSION) && !CarriesOwnPlague(healer, SPELL_CARAPACE_NECROSEE);
}

uint32 GetMissingHealth(Unit const* unit)
{
    return unit->GetMaxHealth() - std::min(unit->GetHealth(), unit->GetMaxHealth());
}

void ClearReserve(Player* healer)
{
    GetHealerData(healer)->reserve = 0;
    healer->RemoveAura(SPELL_RESERVE_DE_SANG);
}

// The Symbiote's bearer, when it still carries this healer's symbiote and is close enough to share
Unit* GetSymbioteBearer(Player* healer)
{
    ObjectGuid const guid = GetHealerData(healer)->symbioteBearer;
    if (!guid)
        return nullptr;

    Unit* bearer = ObjectAccessor::GetUnit(*healer, guid);
    if (!bearer || !bearer->IsAlive() || !bearer->HasAura(SPELL_SYMBIOTE_AURA, healer->GetGUID()) ||
        !healer->IsWithinDistInMap(bearer, SYMBIOTE_RANGE))
        return nullptr;

    return bearer;
}

// Caillot: part of any healing the healer does thickens the absorb on its Symbiote's bearer, up to a cap
void FeedCaillot(Player* healer, uint32 healing)
{
    Unit* bearer = GetSymbioteBearer(healer);
    uint32 const add = CalculatePct(healing, CAILLOT_HEALING_SHARE_PCT);
    if (!bearer || !add)
        return;

    Aura* clot = bearer->GetAura(SPELL_CAILLOT, healer->GetGUID());
    if (!clot)
        clot = healer->AddAura(SPELL_CAILLOT, bearer);
    AuraEffect* absorb = clot ? clot->GetEffect(EFFECT_0) : nullptr;
    if (!absorb)
        return;

    int32 const cap = int32(CalculatePct(bearer->GetMaxHealth(), CAILLOT_MAX_HEALTH_PCT));
    int32 const amount = std::min<int32>(cap, absorb->GetAmount() + int32(add));
    if (amount != absorb->GetAmount())
        absorb->ChangeAmount(amount);
    clot->RefreshDuration();
}

// Hémostase: the most injured ally is in danger, the next hits heal three times as much
void TriggerHemostase(Player* healer, HealerData* data, Unit const* mostInjured)
{
    uint32 const now = GameTime::GetGameTimeMS().count();
    if (!mostInjured->HealthBelowPct(EMERGENCY_HEALTH_PCT) || now < data->hemostaseReadyAt ||
        healer->HasAura(SPELL_HEMOSTASE))
        return;

    if (Aura* burst = healer->AddAura(SPELL_HEMOSTASE, healer))
    {
        burst->SetStackAmount(HEMOSTASE_CHARGES);
        data->hemostaseReadyAt = now + HEMOSTASE_COOLDOWN_MS;
    }
}

// Everything a Transfusion heal sets off once it landed: Coagulation on each ally healed, the Symbiote's copy,
// Sang partagé's share for the healer and Cœur battant's splash on the next injured ally
void AfterTransfusion(Player* healer, std::vector<Unit*> const& healed, uint32 healing)
{
    if (!healing)
        return;

    if (GetTalentValue(healer, TALENT_COAGULATION))
        for (Unit* ally : healed)
            healer->AddAura(SPELL_COAGULATION, ally);

    uint32 givenToOthers = 0;
    Unit* bearer = GetSymbioteBearer(healer);
    bool bearerHealed = false;
    for (Unit* ally : healed)
    {
        if (ally != healer)
            givenToOthers += healing / uint32(healed.size());
        if (ally == bearer)
            bearerHealed = true;
    }

    if (int32 const splash = GetTalentValue(healer, TALENT_COEUR_BATTANT))
    {
        std::vector<Unit*> const next = GetInjuredAllies(healer, HEAL_RANGE, healed.size() + 1);
        for (Unit* ally : next)
        {
            if (std::find(healed.begin(), healed.end(), ally) != healed.end())
                continue;

            HealAlly(healer, ally, CalculatePct(healing, splash), SPELL_TRANSFUSION_HEAL);
            break;
        }
    }

    if (bearer && !bearerHealed)
    {
        int32 const share = GetTalentValue(healer, TALENT_SYMBIOSE_PARFAITE);
        HealAlly(healer, bearer, CalculatePct(healing, share ? share : SYMBIOTE_BASE_PCT), SPELL_SYMBIOTE_AURA);
    }

    if (int32 const share = GetTalentValue(healer, TALENT_SANG_PARTAGE); share && givenToOthers)
        HealAlly(healer, healer, CalculatePct(givenToOthers, share), SPELL_TRANSFUSION_HEAL);
}

// -----------------------------------------------------------------------------------------------------------------
// Transfusion's procs: Spores, Pustule éclatante and Essaim
// -----------------------------------------------------------------------------------------------------------------

float GetAttackPower(Player* healer)
{
    return healer->GetTotalAttackPowerValue(BASE_ATTACK);
}

// Spores on the most injured ally that does not carry this healer's yet (else the most injured, refreshed)
void ProcSpores(Player* healer)
{
    std::vector<Unit*> const injured = GetInjuredAllies(healer, HEAL_RANGE, ANY_NUMBER_OF_ALLIES);
    if (injured.empty())
        return;

    Unit* target = injured.front();
    for (Unit* ally : injured)
    {
        if (!ally->HasAura(SPELL_SPORES, healer->GetGUID()))
        {
            target = ally;
            break;
        }
    }

    if (healer->AddAura(SPELL_SPORES, target))
        target->SendPlaySpellVisual(KIT_SPORES);
}

// A pustule bursts on the most injured ally and splashes the group members around it
void ProcPustule(Player* healer)
{
    std::vector<Unit*> const injured = GetInjuredAllies(healer, HEAL_RANGE, 1);
    if (injured.empty())
        return;

    Unit* target = injured.front();
    uint32 const healing = uint32(GetAttackPower(healer) * PUSTULE_AP_COEFF);
    HealAlly(healer, target, healing, SPELL_PUSTULE);
    target->SendPlaySpellVisual(KIT_PUSTULE);

    // Pustules multiples: +25% splash per point
    uint32 splash = CalculatePct(healing, PUSTULE_SPLASH_PCT);
    splash += CalculatePct(splash, 25 * GetTalentValue(healer, TALENT_PUSTULES_MULTIPLES) / 4);
    for (Unit* ally : GetGroupMembersInRange(healer, HEAL_RANGE))
    {
        if (ally == target || !target->IsWithinDistInMap(ally, PUSTULE_SPLASH_RADIUS) || ally->IsFullHealth())
            continue;

        HealAlly(healer, ally, splash, SPELL_PUSTULE);
        ally->SendPlaySpellVisual(KIT_PUSTULE_SPLASH);
    }
}

// The swarm heals the most injured ally, then jumps to the next most injured one (never straight back), a bounce
// every 400 ms
void EssaimJump(Player* healer, ObjectGuid previous, uint32 jumpsLeft)
{
    if (!healer->IsInWorld() || !healer->IsAlive())
        return;

    Unit* target = nullptr;
    for (Unit* ally : GetInjuredAllies(healer, HEAL_RANGE, ANY_NUMBER_OF_ALLIES))
    {
        if (ally->GetGUID() != previous)
        {
            target = ally;
            break;
        }
    }
    if (!target)
        return;

    HealAlly(healer, target, uint32(GetAttackPower(healer) * ESSAIM_AP_COEFF), SPELL_ESSAIM);
    target->SendPlaySpellVisual(KIT_ESSAIM);

    if (!jumpsLeft)
        return;

    // The event belongs to the healer, so it never outlives it
    ObjectGuid const healed = target->GetGUID();
    healer->m_Events.AddEventAtOffset([healer, healed, jumpsLeft]()
    {
        EssaimJump(healer, healed, jumpsLeft - 1);
    }, ESSAIM_BOUNCE_DELAY);
}

void RollProcs(Player* healer)
{
    if (roll_chance_i(SPORES_CHANCE + GetTalentValue(healer, TALENT_SPORES_FERTILES)))
        ProcSpores(healer);

    if (roll_chance_i(PUSTULE_CHANCE + GetTalentValue(healer, TALENT_PUSTULES_MULTIPLES)))
        ProcPustule(healer);

    if (roll_chance_i(ESSAIM_CHANCE))
        EssaimJump(healer, ObjectGuid::Empty, ESSAIM_BOUNCES + uint32(GetTalentValue(healer, TALENT_ESSAIM_VORACE)));
}

// -----------------------------------------------------------------------------------------------------------------
// Transfusion - the trade, on every melee hit of the healer
// -----------------------------------------------------------------------------------------------------------------

class PestifereHealerUnitScript : public UnitScript
{
public:
    PestifereHealerUnitScript() : UnitScript("PestifereHealerUnitScript", true, {
        UNITHOOK_MODIFY_FINAL_DAMAGE
    }) { }

    void ModifyFinalDamage(Unit* attacker, Unit* victim, uint32& damage, uint32& absorb,
        SpellInfo const* spellInfo) override
    {
        Player* healer = AsPestifere(attacker);
        if (!healer || !victim || victim == attacker || !damage || !IsTransfusionActive(healer))
            return;

        // Hitting is what heals: auto attacks and melee abilities, not the plagues' blasts
        if (spellInfo && spellInfo->DmgClass != SPELL_DAMAGE_CLASS_MELEE)
            return;

        // The procs first: the trade then only buys what they left missing
        RollProcs(healer);

        bool const pestilence = healer->HasAura(SPELL_PESTILENCE_SALVATRICE);
        std::size_t maxTargets = 1;
        if (pestilence)
            maxTargets = PESTILENCE_TARGETS;
        else if (spellInfo && spellInfo->Id == SPELL_SAIGNEE)
            maxTargets = SAIGNEE_TARGETS;

        HealerData* data = GetHealerData(healer);
        std::vector<Unit*> const allies = GetInjuredAllies(healer, HEAL_RANGE, maxTargets);
        if (allies.empty())
        {
            Bank(healer, data, damage);
            return;
        }

        float ratio = TRANSFUSION_HEAL_RATIO
            * (1.0f + float(GetTalentValue(healer, TALENT_TRANSFUSION_VIGOUREUSE)) / 100.0f);
        if (spellInfo && (spellInfo->Id == SPELL_FRAPPE_PUTRIDE || spellInfo->Id == SPELL_FRAPPE_PUTRIDE_ECHO))
            ratio *= 1.0f + float(GetTalentValue(healer, TALENT_HEMOPHAGIE)) / 100.0f;
        if (pestilence)
            ratio *= PESTILENCE_HEAL_MULTIPLIER;

        // Hémostase: an ally in danger, the next hits heal three times as much (a charge per hit)
        TriggerHemostase(healer, data, allies.front());
        if (Aura* burst = healer->GetAura(SPELL_HEMOSTASE))
        {
            ratio *= HEMOSTASE_HEAL_MULTIPLIER;
            burst->ModStackAmount(-1);
        }

        uint64 need = 0;
        for (Unit* ally : allies)
            need += GetMissingHealth(ally);

        // The reserve pays first; what it does not cover is bought with the hit
        uint32 const fromReserve = uint32(std::min<uint64>(data->reserve, need));
        if (data->reserve)
        {
            data->reserve -= fromReserve;
            if (!data->reserve)
                healer->RemoveAura(SPELL_RESERVE_DE_SANG);
        }
        need -= fromReserve;

        uint32 const traded = uint32(std::min<uint64>(damage, uint64(std::ceil(float(need) / ratio))));
        damage -= traded;
        absorb += traded;

        uint32 const healing = uint32(float(traded) * ratio) + fromReserve;
        if (!healing)
            return;

        HealByNeed(healer, allies, healing, SPELL_TRANSFUSION_HEAL);
        AfterTransfusion(healer, allies, healing);

        uint32 const now = GameTime::GetGameTimeMS().count();
        if (now - data->lastTransfusionKit >= TRANSFUSION_KIT_INTERVAL_MS)
        {
            data->lastTransfusionKit = now;
            for (Unit* ally : allies)
                ally->SendPlaySpellVisual(KIT_TRANSFUSION);
        }
    }

private:
    // Réserve de sang: nobody needs healing, so a share of the hit is banked for the next trade
    static void Bank(Player* healer, HealerData* data, uint32 damage)
    {
        int32 const share = GetTalentValue(healer, TALENT_RESERVE_DE_SANG);
        if (!share)
            return;

        uint32 const cap = CalculatePct(healer->GetMaxHealth(), RESERVE_MAX_HEALTH_PCT);
        data->reserve = std::min(cap, data->reserve + CalculatePct(damage, share));
        if (data->reserve && !healer->HasAura(SPELL_RESERVE_DE_SANG))
            healer->AddAura(SPELL_RESERVE_DE_SANG, healer);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90302 Sangsue - the leech: every drain heals the most injured ally, on top of its damage
// -----------------------------------------------------------------------------------------------------------------

class PestifereSangsueAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereSangsueAuraScript);

    void CalculateDrain(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        if (Unit* caster = GetCaster())
            amount = std::max<int32>(1, int32(caster->GetTotalAttackPowerValue(BASE_ATTACK) * SANGSUE_TICK_AP_COEFF));
    }

    void HandlePeriodic(AuraEffect const* aurEff)
    {
        Player* healer = AsPestifere(GetCaster());
        if (!healer || !healer->IsAlive())
            return;

        std::vector<Unit*> const allies = GetInjuredAllies(healer, HEAL_RANGE, 1);
        if (allies.empty())
            return;

        float healing = float(aurEff->GetAmount()) * SANGSUE_HEAL_RATIO;
        healing *= 1.0f + float(GetTalentValue(healer, TALENT_SANGSUE_GEANTE)) / 100.0f;
        HealByNeed(healer, allies, uint32(healing), SPELL_SANGSUE);
        allies.front()->SendPlaySpellVisual(KIT_SANGSUE);
    }

    // Sangsue prolifère: the leech of an enemy that died may jump to the nearest one, with the time it had left
    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        if (GetTargetApplication()->GetRemoveMode() != AURA_REMOVE_BY_DEATH)
            return;

        Player* healer = AsPestifere(GetCaster());
        int32 const chance = GetTalentValue(healer, TALENT_SANGSUE_PROLIFERE);
        int32 const duration = GetAura()->GetDuration();
        if (!chance || duration <= 0 || !roll_chance_i(chance))
            return;

        Unit* dead = GetTarget();
        Unit* nearest = nullptr;
        float nearestDistance = 0.0f;
        for (Unit* enemy : GetEnemiesAround(healer, dead, SANGSUE_JUMP_RADIUS))
        {
            if (enemy == dead || enemy->HasAura(SPELL_SANGSUE, healer->GetGUID()))
                continue;

            float const distance = dead->GetDistance(enemy);
            if (!nearest || distance < nearestDistance)
            {
                nearest = enemy;
                nearestDistance = distance;
            }
        }

        if (!nearest)
            return;

        if (Aura* leech = healer->AddAura(SPELL_SANGSUE, nearest))
            leech->SetDuration(duration);
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereSangsueAuraScript::CalculateDrain, EFFECT_1,
            SPELL_AURA_PERIODIC_DAMAGE);
        OnEffectPeriodic += AuraEffectPeriodicFn(PestifereSangsueAuraScript::HandlePeriodic, EFFECT_1,
            SPELL_AURA_PERIODIC_DAMAGE);
        AfterEffectRemove += AuraEffectRemoveFn(PestifereSangsueAuraScript::HandleRemove, EFFECT_1,
            SPELL_AURA_PERIODIC_DAMAGE, AURA_EFFECT_HANDLE_REAL);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90304 Absorption morbide - draws a disease and a poison out of the most injured ally carrying one
// -----------------------------------------------------------------------------------------------------------------

class PestifereAbsorptionMorbideSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereAbsorptionMorbideSpellScript);

    static constexpr std::array<DispelType, 2> Drawn = { DISPEL_DISEASE, DISPEL_POISON };

    // One effect of that dispel type the ally carries and the healer may draw out, if any
    static Aura* FindDrawable(Player* healer, Unit* ally, DispelType type, SpellInfo const* spellInfo)
    {
        DispelChargesList dispellable;
        ally->GetDispellableAuraList(healer, SpellInfo::GetDispelMask(type), dispellable, spellInfo);
        return dispellable.empty() ? nullptr : dispellable.front().first;
    }

    Unit* FindTarget(Player* healer)
    {
        std::vector<Unit*> allies = GetGroupMembersInRange(healer, HEAL_RANGE);
        std::stable_sort(allies.begin(), allies.end(),
            [](Unit const* left, Unit const* right) { return left->GetHealthPct() < right->GetHealthPct(); });

        for (Unit* ally : allies)
            for (DispelType type : Drawn)
                if (FindDrawable(healer, ally, type, GetSpellInfo()))
                    return ally;

        return nullptr;
    }

    SpellCastResult CheckCast()
    {
        Player* healer = AsPestifere(GetCaster());
        return healer && FindTarget(healer) ? SPELL_CAST_OK : SPELL_FAILED_NOTHING_TO_DISPEL;
    }

    void HandleDraw(SpellEffIndex /*effIndex*/)
    {
        Player* healer = AsPestifere(GetCaster());
        Unit* ally = healer ? FindTarget(healer) : nullptr;
        if (!ally)
            return;

        uint32 drawn = 0;
        for (DispelType type : Drawn)
        {
            if (Aura* aura = FindDrawable(healer, ally, type, GetSpellInfo()))
            {
                ally->RemoveAurasDueToSpellByDispel(aura->GetId(), GetSpellInfo()->Id, aura->GetCasterGUID(), healer);
                ++drawn;
            }
        }

        if (drawn)
        {
            HealAlly(healer, ally, CalculatePct(ally->GetMaxHealth(), ABSORPTION_HEAL_PCT_PER_EFFECT * drawn),
                GetSpellInfo()->Id);
            ally->SendPlaySpellVisual(KIT_ABSORPTION);
        }
    }

    void Register() override
    {
        OnCheckCast += SpellCheckCastFn(PestifereAbsorptionMorbideSpellScript::CheckCast);
        OnEffectHitTarget += SpellEffectFn(PestifereAbsorptionMorbideSpellScript::HandleDraw, EFFECT_0,
            SPELL_EFFECT_DUMMY);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90305 Don de sang - health for health: the caster pays, the most injured ally (never the caster) is restored
// -----------------------------------------------------------------------------------------------------------------

class PestifereDonDeSangSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereDonDeSangSpellScript);

    SpellCastResult CheckCast()
    {
        Player* healer = AsPestifere(GetCaster());
        if (!healer || GetInjuredAllies(healer, HEAL_RANGE, 1, healer).empty())
            return SPELL_FAILED_NO_VALID_TARGETS;

        return SPELL_CAST_OK;
    }

    void HandleGift(SpellEffIndex /*effIndex*/)
    {
        Player* healer = AsPestifere(GetCaster());
        if (!healer)
            return;

        std::vector<Unit*> const allies = GetInjuredAllies(healer, HEAL_RANGE, 1, healer);
        if (allies.empty())
            return;

        // Donneur universel: the gift costs less, or nothing. It never kills the giver.
        uint32 cost = CalculatePct(healer->GetMaxHealth(), DON_DE_SANG_COST_PCT);
        cost -= CalculatePct(cost, std::min(100, GetTalentValue(healer, TALENT_DONNEUR_UNIVERSEL)));
        cost = std::min(cost, healer->GetHealth() - 1);
        if (cost)
            healer->ModifyHealth(-int32(cost));

        // An ally in danger gets more of it
        Unit* ally = allies.front();
        uint32 const percent = ally->HealthBelowPct(EMERGENCY_HEALTH_PCT) ? DON_DE_SANG_EMERGENCY_HEAL_PCT :
            DON_DE_SANG_HEAL_PCT;
        HealAlly(healer, ally, CalculatePct(ally->GetMaxHealth(), percent), GetSpellInfo()->Id);
        ally->SendPlaySpellVisual(KIT_DON_DE_SANG);
    }

    void Register() override
    {
        OnCheckCast += SpellCheckCastFn(PestifereDonDeSangSpellScript::CheckCast);
        OnEffectHitTarget += SpellEffectFn(PestifereDonDeSangSpellScript::HandleGift, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90296 Jet de sang - the healer's reach: a spit at an enemy 30 yards off, its damage turned into healing
// -----------------------------------------------------------------------------------------------------------------

// Weapon damage it deals, and how much of that the most injured ally gets back
constexpr float JET_DE_SANG_WEAPON_SCALE = 1.2f;
constexpr uint32 JET_DE_SANG_HEAL_PCT = 150;

class PestifereJetDeSangSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereJetDeSangSpellScript);

    void HandleHit()
    {
        Player* healer = AsPestifere(GetCaster());
        if (!healer)
            return;
        SetHitDamage(std::max<int32>(1, int32(float(healer->CalculateDamage(BASE_ATTACK, false, true)) *
            JET_DE_SANG_WEAPON_SCALE)));
    }

    void HandleAfterHit()
    {
        Player* healer = AsPestifere(GetCaster());
        if (!healer || GetHitDamage() <= 0)
            return;

        // Veines ouvertes
        uint32 heal = CalculatePct(uint32(GetHitDamage()), JET_DE_SANG_HEAL_PCT);
        heal += CalculatePct(heal, GetTalentValue(healer, TALENT_VEINES_OUVERTES));
        // Sang projeté: the second most injured gets its share too
        int32 const splash = GetTalentValue(healer, TALENT_SANG_PROJETE);
        std::vector<Unit*> const allies = GetInjuredAllies(healer, HEAL_RANGE, splash ? 2 : 1);
        for (std::size_t index = 0; index < allies.size(); ++index)
            HealAlly(healer, allies[index], index == 0 ? heal : CalculatePct(heal, splash), GetSpellInfo()->Id);
    }

    void HandleAfterCast()
    {
        // Crachat d'urgence
        if (Player* healer = AsPestifere(GetCaster()))
            if (int32 const cut = GetTalentValue(healer, TALENT_CRACHAT_URGENCE))
                healer->ModifySpellCooldown(GetSpellInfo()->Id,
                    -int32(CalculatePct(GetSpellInfo()->RecoveryTime, cut)));
    }

    void Register() override
    {
        OnHit += SpellHitFn(PestifereJetDeSangSpellScript::HandleHit);
        AfterHit += SpellHitFn(PestifereJetDeSangSpellScript::HandleAfterHit);
        AfterCast += SpellCastFn(PestifereJetDeSangSpellScript::HandleAfterCast);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90297 Poussée de sang - the healer's burst: an instant heal, then three hits that heal three times as much
// -----------------------------------------------------------------------------------------------------------------

constexpr uint32 POUSSEE_DE_SANG_HEAL_PCT = 20;

class PestiferePousseeDeSangSpellScript : public SpellScript
{
    PrepareSpellScript(PestiferePousseeDeSangSpellScript);

    void HandleSurge(SpellEffIndex /*effIndex*/)
    {
        Player* healer = AsPestifere(GetCaster());
        if (!healer)
            return;

        std::vector<Unit*> const allies = GetInjuredAllies(healer, HEAL_RANGE, 1);
        if (!allies.empty())
        {
            Unit* ally = allies.front();
            HealAlly(healer, ally, CalculatePct(ally->GetMaxHealth(), POUSSEE_DE_SANG_HEAL_PCT), GetSpellInfo()->Id);
            ally->SendPlaySpellVisual(KIT_DON_DE_SANG);
        }

        // Hémostase, whenever it was last triggered
        if (Aura* burst = healer->AddAura(SPELL_HEMOSTASE, healer))
            burst->SetStackAmount(HEMOSTASE_CHARGES);
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(PestiferePousseeDeSangSpellScript::HandleSurge, EFFECT_0,
            SPELL_EFFECT_DUMMY);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90306 Symbiote - bound to the friendly target, or else to whoever is tanking; one at a time
// -----------------------------------------------------------------------------------------------------------------

class PestifereSymbioteSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereSymbioteSpellScript);

    static Unit* ChooseBearer(Player* healer)
    {
        std::vector<Unit*> const members = GetGroupMembersInRange(healer, HEAL_RANGE);

        // The player's own choice first: a friendly group member (or itself) it has selected
        if (Unit* selected = healer->GetSelectedUnit())
            if (std::find(members.begin(), members.end(), selected) != members.end())
                return selected;

        // Else whoever the enemies are on: the member with the most attackers, then the most injured
        Unit* bearer = nullptr;
        for (Unit* member : members)
        {
            if (!bearer)
            {
                bearer = member;
                continue;
            }

            std::size_t const attackers = member->getAttackers().size();
            std::size_t const bearerAttackers = bearer->getAttackers().size();
            if (attackers > bearerAttackers ||
                (attackers == bearerAttackers && member->GetHealthPct() < bearer->GetHealthPct()))
                bearer = member;
        }
        return bearer;
    }

    void HandleBind(SpellEffIndex /*effIndex*/)
    {
        Player* healer = AsPestifere(GetCaster());
        Unit* bearer = healer ? ChooseBearer(healer) : nullptr;
        if (!bearer)
            return;

        HealerData* data = GetHealerData(healer);
        if (data->symbioteBearer && data->symbioteBearer != bearer->GetGUID())
            if (Unit* previous = ObjectAccessor::GetUnit(*healer, data->symbioteBearer))
                previous->RemoveAura(SPELL_SYMBIOTE_AURA, healer->GetGUID());

        healer->AddAura(SPELL_SYMBIOTE_AURA, bearer);
        data->symbioteBearer = bearer->GetGUID();
        bearer->SendPlaySpellVisual(KIT_SYMBIOTE);
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(PestifereSymbioteSpellScript::HandleBind, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
};

// 90307 Symbiote on its bearer - Sang de l'hôte's damage reduction
class PestifereSymbioteAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereSymbioteAuraScript);

    void CalculateReduction(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        amount = -GetTalentValue(GetCaster(), TALENT_SANG_DE_L_HOTE);
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereSymbioteAuraScript::CalculateReduction, EFFECT_1,
            SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN);
    }
};

// 90309 Coagulation on an ally Transfusion healed
class PestifereCoagulationAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereCoagulationAuraScript);

    void CalculateReduction(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        amount = -GetTalentValue(GetCaster(), TALENT_COAGULATION);
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereCoagulationAuraScript::CalculateReduction, EFFECT_0,
            SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN);
    }
};

// 90312 Spores - each tick sized from the healer's attack power
class PestifereSporesAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereSporesAuraScript);

    void CalculateTick(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        if (Unit* caster = GetCaster())
            amount = std::max<int32>(1, int32(caster->GetTotalAttackPowerValue(BASE_ATTACK) * SPORES_TICK_AP_COEFF));
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereSporesAuraScript::CalculateTick, EFFECT_0,
            SPELL_AURA_PERIODIC_HEAL);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// 90315 Brume pestilentielle - a heal over time on every group member around
// -----------------------------------------------------------------------------------------------------------------

class PestifereBrumeSpellScript : public SpellScript
{
    PrepareSpellScript(PestifereBrumeSpellScript);

    void HandleMist(SpellEffIndex /*effIndex*/)
    {
        Player* healer = AsPestifere(GetCaster());
        if (!healer)
            return;

        // A burst at once for the pulse that just hit, then the heal over time
        for (Unit* ally : GetGroupMembersInRange(healer, BRUME_RANGE))
        {
            HealAlly(healer, ally, CalculatePct(ally->GetMaxHealth(), BRUME_INSTANT_HEALTH_PCT),
                SPELL_BRUME_PESTILENTIELLE);
            if (healer->AddAura(SPELL_BRUME_HOT, ally))
                ally->SendPlaySpellVisual(KIT_BRUME);
        }
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(PestifereBrumeSpellScript::HandleMist, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
};

// 90316 Brume pestilentielle on a group member - each tick a share of that member's maximum health
class PestifereBrumeAuraScript : public AuraScript
{
    PrepareAuraScript(PestifereBrumeAuraScript);

    void CalculateTick(AuraEffect const* /*aurEff*/, int32& amount, bool& /*canBeRecalculated*/)
    {
        if (Unit* owner = GetUnitOwner())
            amount = std::max<int32>(1, int32(float(owner->GetMaxHealth()) * BRUME_TICK_HEALTH_PCT / 100.0f));
    }

    void Register() override
    {
        DoEffectCalcAmount += AuraEffectCalcAmountFn(PestifereBrumeAuraScript::CalculateTick, EFFECT_0,
            SPELL_AURA_PERIODIC_HEAL);
    }
};

// -----------------------------------------------------------------------------------------------------------------
// The reserve does not outlive the fight
// -----------------------------------------------------------------------------------------------------------------

class PestifereHealerPlayerScript : public PlayerScript
{
public:
    PestifereHealerPlayerScript() : PlayerScript("PestifereHealerPlayerScript", {
        PLAYERHOOK_ON_PLAYER_LEAVE_COMBAT
    }) { }

    void OnPlayerLeaveCombat(Player* player) override
    {
        if (IsPestifere(player))
            ClearReserve(player);
    }
};
}

namespace Pestifere
{
std::vector<Unit*> GetGroupMembersInRange(Player* healer, float range)
{
    std::vector<Unit*> members;
    if (!healer)
        return members;

    auto consider = [healer, range, &members](Player* member)
    {
        if (!member || !member->IsAlive() || !member->IsInWorld() || member->IsInFlight())
            return;

        if (member != healer &&
            (!healer->IsWithinDistInMap(member, range) || !healer->IsWithinLOSInMap(member) ||
             !healer->IsFriendlyTo(member)))
            return;

        members.push_back(member);
    };

    Group* group = healer->GetGroup();
    if (!group)
    {
        consider(healer);
        return members;
    }

    for (GroupReference* reference = group->GetFirstMember(); reference; reference = reference->next())
        consider(reference->GetSource());

    // The healer always counts, even if the group lookup missed it (a subgroup edge case)
    if (std::find(members.begin(), members.end(), healer) == members.end())
        consider(healer);

    return members;
}

std::vector<Unit*> GetInjuredAllies(Player* healer, float range, std::size_t maxCount, Unit const* exclude)
{
    std::vector<Unit*> injured;
    for (Unit* member : GetGroupMembersInRange(healer, range))
        if (member != exclude && GetMissingHealth(member))
            injured.push_back(member);

    // Most injured first; between equals, the one missing more health
    std::stable_sort(injured.begin(), injured.end(), [](Unit const* left, Unit const* right)
    {
        float const leftPct = left->GetHealthPct();
        float const rightPct = right->GetHealthPct();
        if (leftPct != rightPct)
            return leftPct < rightPct;
        return GetMissingHealth(left) > GetMissingHealth(right);
    });

    if (injured.size() > maxCount)
        injured.resize(maxCount);

    return injured;
}

uint32 HealAlly(Player* healer, Unit* target, uint32 amount, uint32 spellId)
{
    SpellInfo const* spellInfo = sSpellMgr->GetSpellInfo(spellId);
    if (!healer || !target || !amount || !spellInfo || !target->IsAlive())
        return 0;

    if (int32 const bonus = GetTalentValue(healer, TALENT_TRIAGE); bonus && target->HealthBelowPct(TRIAGE_HEALTH_PCT))
        amount += CalculatePct(amount, bonus);

    amount = target->SpellHealingBonusTaken(healer, spellInfo, amount, HEAL);
    // Caillot: every heal the healer gives also thickens the absorb on its Symbiote's bearer, overhealing included
    FeedCaillot(healer, amount);
    HealInfo healInfo(healer, target, amount, spellInfo, spellInfo->GetSchoolMask());
    int32 const gain = healer->HealBySpell(healInfo);
    if (gain > 0)
        target->GetThreatMgr().ForwardThreatForAssistingMe(healer, float(gain) * HEALING_THREAT, spellInfo);

    return uint32(std::max(0, gain));
}

uint32 HealByNeed(Player* healer, std::vector<Unit*> const& allies, uint32 amount, uint32 spellId)
{
    uint32 restored = 0;
    for (std::size_t index = 0; index < allies.size() && amount; ++index)
    {
        Unit* ally = allies[index];
        uint32 const share = index + 1 == allies.size() ? amount : std::min(amount, GetMissingHealth(ally));
        amount -= share;
        restored += HealAlly(healer, ally, share, spellId);
    }
    return restored;
}
}

void AddPestifereHealerScripts()
{
    new PestifereHealerUnitScript();
    new PestifereHealerPlayerScript();
    RegisterSpellScript(PestifereSangsueAuraScript);
    RegisterSpellScript(PestifereAbsorptionMorbideSpellScript);
    RegisterSpellScript(PestifereDonDeSangSpellScript);
    RegisterSpellScript(PestifereJetDeSangSpellScript);
    RegisterSpellScript(PestiferePousseeDeSangSpellScript);
    RegisterSpellScript(PestifereSymbioteSpellScript);
    RegisterSpellScript(PestifereSymbioteAuraScript);
    RegisterSpellScript(PestifereCoagulationAuraScript);
    RegisterSpellScript(PestifereSporesAuraScript);
    RegisterSpellScript(PestifereBrumeSpellScript);
    RegisterSpellScript(PestifereBrumeAuraScript);
}
