-- Details keeps its own class tables, keyed by class token, and reads them with unpack(). A class it has
-- never heard of returns nil there, which is the error players see on every bar update:
--   classe_damage.lua:330: bad argument #1 to 'unpack' (table expected, got nil)
--
-- The server's custom classes are listed in the global CustomClasses (Interface\FrameXML\CustomClasses.lua,
-- generated by localTools/customClasses). This registers each of them with Details.
--
-- class_colors and class_coords live in Details' profile, and Details:ApplyProfile replaces them with fresh
-- copies every time it runs (at load, on a profile switch, from several option paths). Patching the tables
-- once is therefore undone by the next profile application. Instead:
--   1. the classes go into Details' default profile, which ApplyProfile merges into every saved profile, so
--      Details carries them itself;
--   2. every ApplyProfile is followed by a pass that restores them on the fresh tables;
--   3. the tables get a fallback to their "UNKNOW" entry, so a class Details does not know - a future custom
--      class, before this addon learns of it - shows as unknown instead of erroring.
--
-- Details reads four class- or spec-keyed tables through unpack(): class_colors, class_coords,
-- class_specs_coords, and Blizzard's CLASS_ICON_TCOORDS (registered by Interface\FrameXML\CustomClassesUI.lua,
-- and guarded by Details itself). This covers the other three.
--
-- Specs: DetailsFramework.GetSpecializationInfo answers 0 for a class it has no spec ids for. Details treats 0
-- as "no spec" everywhere but one place (core\gears.lua), which caches it as the player's spec; the player
-- then counts as having spec 0, and the spec icon lookup fails. Answering nil instead of 0 follows the
-- convention the rest of Details already uses, and lets the class icon show as it does for any spec-less player.

-- Coordinates to fall back on when a key is missing. The spec icon sheet has no "unknown" cell: its transparent
-- corner draws nothing, which is better than an error for a spec-less player saved by an older version.
local FALLBACKS = {
    class_colors = function(self) return rawget(self, "UNKNOW") end,
    class_coords = function(self) return rawget(self, "UNKNOW") end,
    class_specs_coords = function() return { 1, 1, 1, 1 } end,
}

local function addFallback(name, classTable)
    if type(classTable) ~= "table" or getmetatable(classTable) then
        return
    end

    setmetatable(classTable, { __index = FALLBACKS[name] })
end

-- A spec of 0 cached by an older version would keep the player on the empty spec icon
local function forgetEmptySpecs()
    if type(_detalhes.cached_specs) ~= "table" then
        return
    end
    for guid, spec in pairs(_detalhes.cached_specs) do
        if spec == 0 then
            _detalhes.cached_specs[guid] = nil
        end
    end
end

-- The texture coordinates of the class in Details' 4x4 class icon sheet. The patcher paints the class's icon
-- into one of the sheet's free cells, whole or a quadrant of it (localTools/interface/buildDetailsClassIcons.py:
-- { column, row } or { column, row, quadrant }, 0 top left to 3 bottom right); without one, the unknown cell
-- keeps the bar correct.
local function iconCoords(class)
    local cell = class.detailsCell
    if not cell then
        return { 0.75, 1, 0.75, 1 }
    end
    local left, top, size = cell[1] / 4, cell[2] / 4, 1 / 4
    if cell[3] then
        size = 1 / 8
        left = left + (cell[3] % 2) * size
        top = top + math.floor(cell[3] / 2) * size
    end
    return { left, left + size, top, top + size }
end

-- Writes the custom classes into one set of class tables.
--
-- The colour is always written, never "kept if already there". class_colors is saved in Details' profile, so
-- the first colour a custom class was ever registered with was written into every player's SavedVariables -
-- and a keep-if-present check then preserved that first colour forever. When the Oathblade moved from its
-- warrior tan to bright blue, Details went on drawing tan for anyone who had logged in before. The class
-- colour is the server's to decide, and CustomClasses is where it is decided.
local function addClasses(colors, coords)
    if not CustomClasses then
        return
    end

    for _, class in pairs(CustomClasses) do
        if type(colors) == "table" then
            colors[class.token] = { class.color[1], class.color[2], class.color[3] }
        end
        if type(coords) == "table" then
            coords[class.token] = iconCoords(class)
        end
    end
end

-- A custom class's specializations: Details knows a spec by a number, and draws its icon from the 8x8 spec sheet at
-- class_specs_coords[spec id]. The patcher paints each spec into a free cell (buildDetailsClassIcons.py, from the
-- class's detailsSpecs); its id is class id * 100 + tab + 1, clear of every Blizzard spec id.
local function CustomSpecId(classId, tab)
    local class = CustomClasses and CustomClasses[classId]
    if class and class.specCells and class.specCells[tab + 1] then
        return classId * 100 + tab + 1
    end
    return nil
end

local function addSpecs(specCoords)
    if type(specCoords) ~= "table" or not CustomClasses then
        return
    end
    for classId, class in pairs(CustomClasses) do
        for index, cell in ipairs(class.specCells or {}) do
            local left, top = cell[1] / 8, cell[2] / 8
            specCoords[classId * 100 + index] = { left, left + 1 / 8, top, top + 1 / 8 }
        end
    end
end

-- The tables Details reads at runtime, whatever profile they came from
local function applyToLiveTables()
    addClasses(_detalhes.class_colors, _detalhes.class_coords)
    addSpecs(_detalhes.class_specs_coords)
    for name in pairs(FALLBACKS) do
        addFallback(name, _detalhes[name])
    end
    forgetEmptySpecs()
end

if not _detalhes then
    return
end

-- Tables Details builds once at load and never replaces
if CustomClasses then
    for classId, class in pairs(CustomClasses) do
        if _detalhes.player_class then
            _detalhes.player_class[class.token] = true
        end
        if _detalhes.classstring_to_classid then
            _detalhes.classstring_to_classid[class.token] = classId
        end
        -- A spec's class: Details sets an actor's class from its spec
        if _detalhes.SpecIDToClass then
            for index in ipairs(class.specCells or {}) do
                _detalhes.SpecIDToClass[classId * 100 + index] = class.token
            end
        end
    end
end

-- No spec is nil, not 0 (see the header). Every caller already accepts nil.
local framework = DetailsFramework
if framework and framework.GetSpecializationInfo then
    local getSpecializationInfo = framework.GetSpecializationInfo
    framework.GetSpecializationInfo = function(...)
        local specId = getSpecializationInfo(...)
        if specId == 0 then
            return nil
        end
        return specId
    end
end

-- 1. Details' defaults: ApplyProfile copies any key a saved profile lacks from here
local defaults = _detalhes.default_profile
if defaults then
    addClasses(defaults.class_colors, defaults.class_coords)
    addSpecs(defaults.class_specs_coords)
end

-- 2. Every profile application replaces the live tables: restore the classes on the fresh copies
hooksecurefunc(_detalhes, "ApplyProfile", applyToLiveTables)

-- 3. A profile may already have been applied before this addon loaded
applyToLiveTables()

-- Damage through allies ----------------------------------------------------------------------------------------------
--
-- A support class deals part of its damage as a share of its allies' hits (the Barbarian's Écho ancestral): its own
-- in the meter, but not its own doing. Those spells (CustomClasses[...].supportSpells, from classes.json) are shown
-- apart wherever Details lists spells: in the support colour, tagged, with the support badge as their icon. Details
-- rebuilds its spell cache from SpellOverwrite (ClearSpellCache): they go in there, and onto the cache in use.
local SUPPORT_ICON = [[Interface\TalentTree\role-support]]
local SUPPORT_TAG = GetLocale() == "frFR" and "via alliés" or "via allies"

local function supportSpellEntry(spellId)
    local name = GetSpellInfo(spellId)
    if not name then
        return nil
    end
    return { name = "|cffb48cff" .. name .. " (" .. SUPPORT_TAG .. ")|r", icon = SUPPORT_ICON }
end

local function addSupportSpells()
    if not CustomClasses then
        return
    end
    for _, class in pairs(CustomClasses) do
        for _, spellId in ipairs(class.supportSpells or {}) do
            local entry = supportSpellEntry(spellId)
            if entry then
                if type(_detalhes.SpellOverwrite) == "table" then
                    _detalhes.SpellOverwrite[spellId] = entry
                end
                if type(_detalhes.spellcache) == "table" then
                    rawset(_detalhes.spellcache, spellId, { entry.name, 1, entry.icon })
                end
            end
        end
    end
end

addSupportSpells()
if type(_detalhes.ClearSpellCache) == "function" then
    hooksecurefunc(_detalhes, "ClearSpellCache", addSupportSpells)
end

-- Real specs ---------------------------------------------------------------------------------------------------------
--
-- Details finds a spec on its own: from WotLK talent points, else from the spells it sees cast. Neither works for the
-- classes whose talents were rebuilt (their WotLK talent points are always 0, their spells are not the stock ones it
-- looks for), so it guessed, often wrong. The server knows every group member's spec, bots included, and whispers it
-- (mod-playerbots GroupSpecSync.cpp):
--   GroupSpec  S <tab> <guid> <tab> <class id> <tab> <spec tab, 0-based>
-- A spec known that way is the only one Details gets for that player: it is written into its cache and onto the
-- players already in the meter, guessing is skipped for them, and it is put back whenever Details wipes or re-tracks
-- its cache. A custom class gets the ids CustomSpecId gives its specs, when it has spec icons (else its class icon).

-- Class ids to Details' class tokens (the stock classes only: Details has no spec ids for the others)
local CLASS_TOKENS = {
    [1] = "WARRIOR", [2] = "PALADIN", [3] = "HUNTER", [4] = "ROGUE", [5] = "PRIEST", [6] = "DEATHKNIGHT",
    [7] = "SHAMAN", [8] = "MAGE", [9] = "WARLOCK", [11] = "DRUID",
}
-- Details lists four druid specs (feral and guardian apart); the third talent tab is restoration
local DRUID_SPECS = { 102, 103, 105 }

local realSpecs = {}

local function SpecIdOf(classId, tab)
    local token = CLASS_TOKENS[classId]
    if not token then
        return CustomSpecId(classId, tab)
    end
    if token == "DRUID" then
        return DRUID_SPECS[tab + 1]
    end
    local specId = framework and framework.GetSpecializationID and framework.GetSpecializationID(token, tab + 1)
    return specId ~= 0 and specId or nil
end

-- A spec onto every copy of that player in the meter: the current fight's and the overall one
local function ApplySpec(guid, specId)
    if type(_detalhes.cached_specs) == "table" then
        _detalhes.cached_specs[guid] = specId
    end
    for _, combat in ipairs({ _detalhes.tabela_vigente, _detalhes.tabela_overall }) do
        if type(combat) == "table" then
            for attribute = 1, 4 do
                local container = combat[attribute]
                if type(container) == "table" and container._ActorTable then
                    for _, actor in ipairs(container._ActorTable) do
                        if actor.serial == guid and actor.spec ~= specId then
                            actor.spec = specId
                        end
                    end
                end
            end
        end
    end
end

local function ApplyAll()
    for guid, specId in pairs(realSpecs) do
        ApplySpec(guid, specId)
    end
end

-- Guessing, only for the players the server has not told us about
for _, name in ipairs({ "GuessSpec", "ReGuessSpec" }) do
    local guess = _detalhes[name]
    if type(guess) == "function" then
        _detalhes[name] = function(self, t, ...)
            local actor = type(t) == "table" and t[1]
            local specId = actor and actor.serial and realSpecs[actor.serial]
            if specId then
                actor.spec = specId
                if type(_detalhes.cached_specs) == "table" then
                    _detalhes.cached_specs[actor.serial] = specId
                end
                return specId
            end
            return guess(self, t, ...)
        end
    end
end

-- Details wipes its cache (ResetSpecCache) and re-reads it from spells and talents (TrackSpecsNow): the real specs
-- go back on after
for _, name in ipairs({ "ResetSpecCache", "TrackSpecsNow" }) do
    if type(_detalhes[name]) == "function" then
        hooksecurefunc(_detalhes, name, ApplyAll)
    end
end

local specListener = CreateFrame("Frame")
specListener:RegisterEvent("CHAT_MSG_ADDON")
specListener:SetScript("OnEvent", function(_, _, prefix, message, _, sender)
    if prefix ~= "GroupSpec" or sender ~= UnitName("player") then
        return
    end
    local kind, guid, classId, tab = strsplit("\t", message)
    if kind ~= "S" or not guid then
        return
    end
    local specId = SpecIdOf(tonumber(classId), tonumber(tab) or 0)
    if specId then
        realSpecs[guid] = specId
        ApplySpec(guid, specId)
    end
end)

-- Anything that still slips past (a talent library callback writing the cache): corrected every few seconds
local elapsedSinceApply = 0
specListener:SetScript("OnUpdate", function(_, elapsed)
    elapsedSinceApply = elapsedSinceApply + elapsed
    if elapsedSinceApply >= 3 then
        elapsedSinceApply = 0
        ApplyAll()
    end
end)
