-- Details keeps its own class tables, keyed by class token, and reads them with unpack(). A class it has
-- never heard of returns nil there, which is the error players see on every bar update:
--   classe_damage.lua:330: bad argument #1 to 'unpack' (table expected, got nil)
--
-- The server's custom classes are listed in the global CustomClasses (Interface\FrameXML\CustomClasses.lua,
-- generated by localTools/customClasses). This registers each of them with Details.
--
-- class_colors and class_coords live in Details' profile, and Details:ApplyProfile replaces them with fresh
-- copies every time it runs (at load, on a profile switch, from several option paths). Patching the tables
-- once is therefore undone by the next profile application. Instead:
--   1. the classes go into Details' default profile, which ApplyProfile merges into every saved profile, so
--      Details carries them itself;
--   2. every ApplyProfile is followed by a pass that restores them on the fresh tables;
--   3. the tables get a fallback to their "UNKNOW" entry, so a class Details does not know - a future custom
--      class, before this addon learns of it - shows as unknown instead of erroring.
--
-- Details reads four class- or spec-keyed tables through unpack(): class_colors, class_coords,
-- class_specs_coords, and Blizzard's CLASS_ICON_TCOORDS (registered by Interface\FrameXML\CustomClassesUI.lua,
-- and guarded by Details itself). This covers the other three.
--
-- Specs: DetailsFramework.GetSpecializationInfo answers 0 for a class it has no spec ids for. Details treats 0
-- as "no spec" everywhere but one place (core\gears.lua), which caches it as the player's spec; the player
-- then counts as having spec 0, and the spec icon lookup fails. Answering nil instead of 0 follows the
-- convention the rest of Details already uses, and lets the class icon show as it does for any spec-less player.

-- Coordinates to fall back on when a key is missing. The spec icon sheet has no "unknown" cell: its transparent
-- corner draws nothing, which is better than an error for a spec-less player saved by an older version.
local FALLBACKS = {
    class_colors = function(self) return rawget(self, "UNKNOW") end,
    class_coords = function(self) return rawget(self, "UNKNOW") end,
    class_specs_coords = function() return { 1, 1, 1, 1 } end,
}

local function addFallback(name, classTable)
    if type(classTable) ~= "table" or getmetatable(classTable) then
        return
    end

    setmetatable(classTable, { __index = FALLBACKS[name] })
end

-- A spec of 0 cached by an older version would keep the player on the empty spec icon
local function forgetEmptySpecs()
    if type(_detalhes.cached_specs) ~= "table" then
        return
    end
    for guid, spec in pairs(_detalhes.cached_specs) do
        if spec == 0 then
            _detalhes.cached_specs[guid] = nil
        end
    end
end

-- The texture coordinates of the class in Details' 4x4 class icon sheet. The patcher paints the class's icon
-- into one of the sheet's empty cells (localTools/interface/buildDetailsClassIcons.py); without one, the
-- unknown cell keeps the bar correct.
local function iconCoords(class)
    if class.detailsCell then
        local column, row = class.detailsCell[1], class.detailsCell[2]
        return { column / 4, (column + 1) / 4, row / 4, (row + 1) / 4 }
    end
    return { 0.75, 1, 0.75, 1 }
end

-- Writes the custom classes into one set of class tables, keeping any value already there
local function addClasses(colors, coords)
    if not CustomClasses then
        return
    end

    for _, class in pairs(CustomClasses) do
        if type(colors) == "table" and not rawget(colors, class.token) then
            colors[class.token] = { class.color[1], class.color[2], class.color[3] }
        end
        if type(coords) == "table" then
            coords[class.token] = iconCoords(class)
        end
    end
end

-- The tables Details reads at runtime, whatever profile they came from
local function applyToLiveTables()
    addClasses(_detalhes.class_colors, _detalhes.class_coords)
    for name in pairs(FALLBACKS) do
        addFallback(name, _detalhes[name])
    end
    forgetEmptySpecs()
end

if not _detalhes then
    return
end

-- Tables Details builds once at load and never replaces
if CustomClasses then
    for classId, class in pairs(CustomClasses) do
        if _detalhes.player_class then
            _detalhes.player_class[class.token] = true
        end
        if _detalhes.classstring_to_classid then
            _detalhes.classstring_to_classid[class.token] = classId
        end
    end
end

-- No spec is nil, not 0 (see the header). Every caller already accepts nil.
local framework = DetailsFramework
if framework and framework.GetSpecializationInfo then
    local getSpecializationInfo = framework.GetSpecializationInfo
    framework.GetSpecializationInfo = function(...)
        local specId = getSpecializationInfo(...)
        if specId == 0 then
            return nil
        end
        return specId
    end
end

-- 1. Details' defaults: ApplyProfile copies any key a saved profile lacks from here
local defaults = _detalhes.default_profile
if defaults then
    addClasses(defaults.class_colors, defaults.class_coords)
end

-- 2. Every profile application replaces the live tables: restore the classes on the fresh copies
hooksecurefunc(_detalhes, "ApplyProfile", applyToLiveTables)

-- 3. A profile may already have been applied before this addon loaded
applyToLiveTables()
