"""The other dungeons' legendaries' base items (mod-legendary Definitions 4-24) as world SQL: appended to
modules/mod-legendary/data/sql/db-world/base/legendary_items.sql between its markers.

Each base is an Item.dbc row with no template of its own (the custom item ids rule): its template is copied from the
item whose look it wears (localTools/patchSinisterStrike.ps1 $legendaryItems), every stat, spell, socket and limit
stripped - a copy rolls its own (character_legendary) - and its class, subclass, material, slot and sheath set to the
row's, which the server enforces over the template.

Usage: python localTools/legendary/buildLegendaryItemSql.py
"""

import struct
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SQL = REPO / "modules" / "mod-legendary" / "data" / "sql" / "db-world" / "base" / "legendary_items.sql"
ITEM_DBC = REPO / "server" / "Data" / "dbc" / "Item.before-paragon-glyphs.dbc"
BEGIN = "-- BEGIN generated by localTools/legendary/buildLegendaryItemSql.py"
END = "-- END generated"

# Base item, the template its look comes from, its name: French first (the server's own language), English second
LEGENDARIES = [
    (21424, 31294, "Épaulières de Capacitus", "Capacitus' Spaulders"),
    (1258, 28288, "Abaque de Pathaleon", "Pathaleon's Abacus"),
    (21432, 31284, "Brassards de Sepethrea", "Sepethrea's Bracers"),
    (21425, 37785, "Ceinture d'Ingvar", "Ingvar's Girdle"),
    (21420, 35574, "Cuirasse de Keleseth", "Keleseth's Breastplate"),
    (26541, 37748, "Collier d'Annhylde", "Annhylde's Necklace"),
    (21437, 27528, "Poignes de Kargath", "Kargath's Grips"),
    (21433, 27517, "Bandelettes de Nethekurse", "Nethekurse's Wraps"),
    (5828, 31290, "Chevalière de Porung", "Porung's Signet"),
    (21421, 10399, "Plastron de VanCleef", "VanCleef's Chestguard"),
    (21429, 10403, "Ceinture à poudre de Gilnid", "Gilnid's Powder Belt"),
    (21444, 12977, "Moufles de Cookie", "Cookie's Mitts"),
    (18161, 35641, "Bottes du roi Dred", "King Dred's Boots"),
    (21430, 35632, "Robe de Novos", "Novos' Robe"),
    (27218, 35631, "Pendentif de Tharon'ja", "Tharon'ja's Pendant"),
    (21423, 49794, "Jambières du Dévoreur", "Devourer's Legplates"),
    (21434, 37793, "Heaume de Bronjahm", "Bronjahm's Helm"),
    (6673, 49800, "Anneau de l'âme reflétée", "Ring of the Mirrored Soul"),
    (8688, 43573, "Étincelle d'Ionar", "Ionar's Spark"),
    (21450, 36995, "Poings de Loken", "Fists of Loken"),
    (6674, 36979, "Chevalière de Bjarngrim", "Bjarngrim's Signet"),
    # The Hollow Voice's Unique: quality 6, red (the client extension DLL's UniqueQuality.cpp)
    (10555, 49800, "Écho du Néant", "Echo of the Void"),
    # L'Infini's: a trinket, Dark Matter's template
    (16067, 46038, "L'Étoile captive", "The Captive Star"),
]
# Rows made another slot by localTools/patchSinisterStrike.ps1 ($legendaryItems InventoryType): the stock row is read
INVENTORY_TYPES = {16067: 12}
UNIQUE = {10555}


# Every legendary base (the three Scarlet Cathedral ones written by hand above the generated block, the others below)
CATHEDRAL = [24567, 996, 21428]

# Sockets by slot (InventoryType), as the item level 277 epics have them most (2026-10-07): 1 meta, 2 red, 4 yellow,
# 8 blue; and a socket bonus of stamina, which suits every wearer (SpellItemEnchantment: 2868 +6, 3307 +9, 3766 +12).
# A trinket has none.
SOCKETS = {
    1: ((1, 2), 3766),          # head: a meta and one
    2: ((2,), 2868),            # neck
    3: ((2,), 2868),            # shoulders
    5: ((2, 4), 3307),          # chest
    20: ((2, 4), 3307),         # robe
    6: ((2, 4), 3307),          # belt
    7: ((2, 4), 3307),          # legs
    8: ((2, 4), 3307),          # feet
    9: ((2,), 2868),            # wrists
    10: ((2,), 2868),           # hands
    11: ((2,), 2868),           # ring
    16: ((2,), 2868),           # cloak
}


def sockets_sql(rows):
    lines = ["-- Every legendary base's sockets: a stock epic's of its slot, with a stamina bonus"]
    for base in CATHEDRAL + [legendary[0] for legendary in LEGENDARIES]:
        inventory = rows[base][3]
        colors, bonus = SOCKETS.get(inventory, ((), 0))
        colors = list(colors) + [0] * (3 - len(colors))
        lines.append(f"UPDATE `item_template` SET `socketColor_1` = {colors[0]}, `socketColor_2` = {colors[1]}, "
                     f"`socketColor_3` = {colors[2]},\n    `socketContent_1` = 0, `socketContent_2` = 0, "
                     f"`socketContent_3` = 0, `socketBonus` = {bonus} WHERE `entry` = {base};")
    return "\n".join(lines) + "\n"


def item_rows():
    data = ITEM_DBC.read_bytes()
    count, _, size = struct.unpack_from("<III", data, 4)
    rows = {}
    for index in range(count):
        entry, cls, subclass, _, material, _, inventory, sheath = struct.unpack_from("<8I", data, 20 + index * size)
        inventory = INVENTORY_TYPES.get(entry, inventory)
        rows[entry] = (cls, subclass, struct.unpack("<i", struct.pack("<I", material))[0], inventory, sheath)
    return rows


def quote(text):
    return text.replace("'", "''")


def block(base, source, french, english, row):
    cls, subclass, material, inventory, sheath = row
    return f"""-- {base} {french}: copied from {source}, its look's item
DELETE FROM `item_template` WHERE `entry` = {base};
DELETE FROM `item_template_locale` WHERE `ID` = {base};
DROP TEMPORARY TABLE IF EXISTS `legendary_base`;
CREATE TEMPORARY TABLE `legendary_base` SELECT * FROM `item_template` WHERE `entry` = {source};
UPDATE `legendary_base` SET
    `entry` = {base}, `name` = '{quote(french)}', `Quality` = {6 if base in UNIQUE else 5}, `ItemLevel` = 227, `RequiredLevel` = 80,
    `class` = {cls}, `subclass` = {subclass}, `Material` = {material}, `InventoryType` = {inventory},
    `sheath` = {sheath},
    `displayid` = {71003 + LEGENDARIES.index((base, source, french, english))}, `bonding` = 1, `armor` = 0,
    `ScalingStatDistribution` = 0, `ScalingStatValue` = 0,
    `stat_type1` = 0, `stat_value1` = 0, `stat_type2` = 0, `stat_value2` = 0, `stat_type3` = 0, `stat_value3` = 0,
    `stat_type4` = 0, `stat_value4` = 0, `stat_type5` = 0, `stat_value5` = 0, `stat_type6` = 0, `stat_value6` = 0,
    `stat_type7` = 0, `stat_value7` = 0, `stat_type8` = 0, `stat_value8` = 0, `stat_type9` = 0, `stat_value9` = 0,
    `stat_type10` = 0, `stat_value10` = 0,
    `spellid_1` = 0, `spellid_2` = 0, `spellid_3` = 0, `spellid_4` = 0, `spellid_5` = 0,
    `spelltrigger_1` = 0, `spelltrigger_2` = 0, `spelltrigger_3` = 0, `spelltrigger_4` = 0, `spelltrigger_5` = 0,
    `itemset` = 0, `SellPrice` = 0, `BuyPrice` = 0, `MaxDurability` = 0, `description` = '',
    `socketColor_1` = 0, `socketContent_1` = 0, `socketColor_2` = 0, `socketContent_2` = 0, `socketColor_3` = 0,
    `socketContent_3` = 0, `socketBonus` = 0, `GemProperties` = 0, `RandomProperty` = 0, `RandomSuffix` = 0,
    `AllowableClass` = -1, `AllowableRace` = -1, `Flags` = 0, `FlagsExtra` = 0, `ItemLimitCategory` = 0,
    `RequiredSkill` = 0, `RequiredSkillRank` = 0, `requiredspell` = 0, `RequiredReputationFaction` = 0,
    `RequiredReputationRank` = 0, `maxcount` = 0, `stackable` = 1;
INSERT INTO `item_template` SELECT * FROM `legendary_base`;
DROP TEMPORARY TABLE `legendary_base`;
INSERT INTO `item_template_locale` (`ID`, `locale`, `Name`, `Description`, `VerifiedBuild`) VALUES
({base}, 'frFR', '{quote(french)}', '', 0),
({base}, 'enUS', '{quote(english)}', '', 0);
"""


def main():
    rows = item_rows()
    blocks = []
    for legendary in LEGENDARIES:
        base = legendary[0]
        if base not in rows:
            raise SystemExit(f"Item.dbc has no row {base}")
        blocks.append(block(*legendary, rows[base]))
    generated = (f"{BEGIN}\n-- The other dungeons' legendaries (mod-legendary Definitions 4-24): see the script for "
                 f"how each is made.\n" + "\n".join(blocks) + "\n" + sockets_sql(rows) + f"{END}\n")
    text = SQL.read_text(encoding="utf-8")
    if BEGIN in text:
        text = text[:text.index(BEGIN)] + generated + text[text.index(END) + len(END) + 1:]
    else:
        text = text.rstrip("\n") + "\n\n" + generated
    SQL.write_text(text, encoding="utf-8", newline="\n")
    print(f"{len(blocks)} legendary base items written to {SQL.relative_to(REPO)}")


if __name__ == "__main__":
    main()
