// Custom playable classes framework.
//
// A row in the world table `custom_class` makes a class id (10, 12-15) playable and names the class whose
// rules it borrows. The core already reads that table for the per-class combat tables (crit, dodge, regen,
// rating scaling); this script answers the engine's "is this player class X?" question with the template
// class, so everything driven by IsClass - attack power from strength, what the class may equip, reactive
// abilities, trainers - behaves like the template without touching those code paths.
//
// What a class still brings itself: its spells, talents and the data generated by localTools/customClasses
// (ChrClasses, race/class pairs, start position, base stats per level, skills, trainer).

#include "ObjectMgr.h"
#include "Player.h"
#include "PlayerScript.h"
#include "ScriptMgr.h"

namespace
{
// A template class exists to supply combat maths and what the class may wear - nothing else. Every other
// context is a class speciality that a new class must not inherit, and claiming them caused real bugs:
//   CLASS_CONTEXT_ABILITY        is the Death Knight rune machinery (InitRunes, TakeRunePower, rune regen):
//                                a rage class that claims it is handed runes it can never spend
//   CLASS_CONTEXT_SKILL          starts weapon skills at maximum, which only suits a level 55 hero class
//   CLASS_CONTEXT_EQUIP_RELIC    lets the class equip the template's relic (a Death Knight sigil)
//   CLASS_CONTEXT_TALENT_POINT_CALC  applies the Death Knight's "no talents before 56" rule
//   CLASS_CONTEXT_ABILITY_REACTIVE, _EQUIP_SHIELDS and _WEAPON_SWAP only ever test rogue, hunter, warrior,
//                                paladin or shaman, so a custom class matches nothing through them anyway
// CLASS_CONTEXT_INIT, _TELEPORT, _QUEST, _TAXI and _GRAVEYARD stay out for the same reason: they drive the
// Death Knight starting zone and class quests.
bool UsesTemplate(ClassContext context)
{
    switch (context)
    {
        case CLASS_CONTEXT_STATS:
        case CLASS_CONTEXT_EQUIP_ARMOR_CLASS:
            return true;
        default:
            return false;
    }
}

class CustomClassPlayerScript final : public PlayerScript
{
public:
    CustomClassPlayerScript() : PlayerScript("CustomClassPlayerScript", {
        PLAYERHOOK_ON_PLAYER_IS_CLASS
    }) { }

    Optional<bool> OnPlayerIsClass(Player const* player, Classes playerClass, ClassContext context) override
    {
        if (!player)
            return std::nullopt;

        uint8 const ownClass = player->getClass();
        uint8 const templateClass = sObjectMgr->GetClassFormulaTemplate(ownClass);
        if (templateClass == ownClass)
            return std::nullopt;

        // A class trainer teaches the template's spells, so only a class that starts from that kit uses one
        bool const usesTemplate = context == CLASS_CONTEXT_CLASS_TRAINER
            ? (sObjectMgr->GetSpellClassMask(ownClass) & (1 << (templateClass - 1))) != 0
            : UsesTemplate(context);
        if (!usesTemplate)
            return std::nullopt;

        // The class answers to its own id and to its template's, so both class checks match
        return playerClass == ownClass || playerClass == templateClass;
    }
};
}

void AddCustomClassScripts()
{
    new CustomClassPlayerScript();
}
