-- Generated by localTools/customClasses/buildCustomClasses.py from classes.json. Do not edit.

-- Custom class slots no class uses any more: 10, 14, 15
DELETE FROM `custom_class` WHERE `ClassId` IN (10, 14, 15);
DELETE FROM `playercreateinfo` WHERE `class` IN (10, 14, 15);
DELETE FROM `player_class_stats` WHERE `Class` IN (10, 14, 15);
DELETE FROM `playercreateinfo_skills` WHERE `classMask` IN (512, 8192, 16384);
DELETE FROM `playercreateinfo_spell_custom` WHERE `classmask` IN (512, 8192, 16384);
DELETE FROM `trainer` WHERE `Type` = 0 AND `Requirement` IN (10, 14, 15);

DELETE FROM `custom_class` WHERE `ClassId` IN (12, 13);
INSERT INTO `custom_class` (`ClassId`, `TemplateClass`, `InheritSpells`, `Roles`, `StartLevel`, `Name`, `Comment`) VALUES
(12, 6, 0, 14, 10, 'Pestiféré', 'Plague tank: carries its own diseases, spreads them, detonates them'),
(13, 9, 0, 8, 15, 'Nécromancien', 'Commander of temporary melee and ranged undead minions');

-- Class 12 (Pestiféré), built on class 6
DELETE FROM `playercreateinfo` WHERE `class` = 12;
-- Every race starts where race 1 class 1 does
INSERT INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`)
  SELECT `races`.`race`, 12, `start`.`map`, `start`.`zone`, `start`.`position_x`, `start`.`position_y`, `start`.`position_z`, `start`.`orientation`
  FROM (SELECT * FROM `playercreateinfo` WHERE `race` = 1 AND `class` = 1) `start`
  JOIN (SELECT DISTINCT `race` FROM `playercreateinfo` WHERE `race` IN (1, 2, 3, 4, 5, 6, 7, 8, 10, 11)) `races`;
DELETE FROM `player_class_stats` WHERE `Class` = 12;
INSERT INTO `player_class_stats` (`Class`, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`)
  SELECT 12, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit` FROM `player_class_stats` WHERE `Class` = 6;
-- Levels the template class never sees (the Death Knight starts at 55) come from the start class, or the server refuses to start
INSERT INTO `player_class_stats` (`Class`, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`)
  SELECT 12, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit` FROM (SELECT * FROM `player_class_stats` WHERE `Class` = 1) `fallback`
  WHERE `Level` NOT IN (SELECT `Level` FROM (SELECT `Level` FROM `player_class_stats` WHERE `Class` = 12) `have`);
DELETE FROM `playercreateinfo_skills` WHERE `classMask` = 2048;
INSERT INTO `playercreateinfo_skills` (`raceMask`, `classMask`, `skill`, `rank`, `comment`)
  SELECT `raceMask`, 2048, `skill`, `rank`, CONCAT('Pestiféré', ' - ', `comment`) FROM `playercreateinfo_skills`  WHERE `classMask` & 32 AND `classMask` != 0;
DELETE FROM `playercreateinfo_spell_custom` WHERE `classmask` = 2048;
-- The class's own spellbook tab replaces the template's class skill lines
DELETE FROM `playercreateinfo_skills` WHERE `classMask` = 2048 AND `skill` IN (6, 8, 26, 38, 39, 50, 51, 56, 78, 134, 163, 184, 188, 189, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 217, 218, 236, 237, 251, 253, 256, 257, 267, 270, 354, 355, 373, 374, 375, 573, 574, 593, 594, 613, 633, 653, 654, 655, 656, 761, 763, 764, 765, 766, 767, 768, 770, 771, 772, 775, 776, 780, 781, 782, 783, 784, 785, 786, 787);
INSERT INTO `playercreateinfo_skills` (`raceMask`, `classMask`, `skill`, `rank`, `comment`) VALUES (0, 2048, 900, 1, 'Pestiféré');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES
  (0, 2048, 6603, 'Pestiféré'),
  (0, 2048, 9078, 'Pestiféré'),
  (0, 2048, 9077, 'Pestiféré'),
  (0, 2048, 8737, 'Pestiféré'),
  (0, 2048, 750, 'Pestiféré'),
  (0, 2048, 196, 'Pestiféré'),
  (0, 2048, 197, 'Pestiféré'),
  (0, 2048, 198, 'Pestiféré'),
  (0, 2048, 199, 'Pestiféré'),
  (0, 2048, 200, 'Pestiféré'),
  (0, 2048, 201, 'Pestiféré'),
  (0, 2048, 202, 'Pestiféré'),
  (0, 2048, 203, 'Pestiféré'),
  (0, 2048, 674, 'Pestiféré'),
  (0, 2048, 3127, 'Pestiféré'),
  (0, 2048, 90200, 'Pestiféré'),
  (0, 2048, 90210, 'Pestiféré');
DELETE FROM `trainer` WHERE `Type` = 0 AND `Requirement` = 12;
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`)
  SELECT COALESCE(MAX(`Id`), 0) + 1, 0, 12, 'Ready for some training?', 0 FROM `trainer`;

-- Class 13 (Nécromancien), built on class 9
DELETE FROM `playercreateinfo` WHERE `class` = 13;
INSERT INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`)
  SELECT `race`, 13, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation` FROM `playercreateinfo` WHERE `class` = 9 AND `race` IN (1, 2, 3, 4, 5, 6, 7, 8, 10, 11);
-- Races the start class cannot be: a starting point belongs to the race, so any of its classes gives the same one
INSERT INTO `playercreateinfo` (`race`, `class`, `map`, `zone`, `position_x`, `position_y`, `position_z`, `orientation`)
  SELECT `p`.`race`, 13, `p`.`map`, `p`.`zone`, `p`.`position_x`, `p`.`position_y`, `p`.`position_z`, `p`.`orientation` FROM (SELECT * FROM `playercreateinfo`) `p`
  JOIN (SELECT `race`, MIN(`class`) AS `class` FROM `playercreateinfo` WHERE `race` IN (1, 2, 3, 4, 5, 6, 7, 8, 10, 11) GROUP BY `race`) `pick` ON `pick`.`race` = `p`.`race` AND `pick`.`class` = `p`.`class`
  WHERE `p`.`race` NOT IN (SELECT `race` FROM (SELECT `race` FROM `playercreateinfo` WHERE `class` = 13) `taken`);
DELETE FROM `player_class_stats` WHERE `Class` = 13;
INSERT INTO `player_class_stats` (`Class`, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`)
  SELECT 13, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit` FROM `player_class_stats` WHERE `Class` = 9;
-- Levels the template class never sees (the Death Knight starts at 55) come from the start class, or the server refuses to start
INSERT INTO `player_class_stats` (`Class`, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit`)
  SELECT 13, `Level`, `BaseHP`, `BaseMana`, `Strength`, `Agility`, `Stamina`, `Intellect`, `Spirit` FROM (SELECT * FROM `player_class_stats` WHERE `Class` = 9) `fallback`
  WHERE `Level` NOT IN (SELECT `Level` FROM (SELECT `Level` FROM `player_class_stats` WHERE `Class` = 13) `have`);
DELETE FROM `playercreateinfo_skills` WHERE `classMask` = 4096;
INSERT INTO `playercreateinfo_skills` (`raceMask`, `classMask`, `skill`, `rank`, `comment`)
  SELECT `raceMask`, 4096, `skill`, `rank`, CONCAT('Nécromancien', ' - ', `comment`) FROM `playercreateinfo_skills`  WHERE `classMask` & 256 AND `classMask` != 0;
DELETE FROM `playercreateinfo_spell_custom` WHERE `classmask` = 4096;
-- The class's own spellbook tab replaces the template's class skill lines
DELETE FROM `playercreateinfo_skills` WHERE `classMask` = 4096 AND `skill` IN (6, 8, 26, 38, 39, 50, 51, 56, 78, 134, 163, 184, 188, 189, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 217, 218, 236, 237, 251, 253, 256, 257, 267, 270, 354, 355, 373, 374, 375, 573, 574, 593, 594, 613, 633, 653, 654, 655, 656, 761, 763, 764, 765, 766, 767, 768, 770, 771, 772, 775, 776, 780, 781, 782, 783, 784, 785, 786, 787);
INSERT INTO `playercreateinfo_skills` (`raceMask`, `classMask`, `skill`, `rank`, `comment`) VALUES (0, 4096, 901, 1, 'Nécromancie');
INSERT INTO `playercreateinfo_spell_custom` (`racemask`, `classmask`, `Spell`, `Note`) VALUES
  (0, 4096, 6603, 'Nécromancien'),
  (0, 4096, 90400, 'Nécromancien'),
  (0, 4096, 90402, 'Nécromancien'),
  (0, 4096, 90422, 'Nécromancien');
DELETE FROM `trainer` WHERE `Type` = 0 AND `Requirement` = 13;
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`)
  SELECT COALESCE(MAX(`Id`), 0) + 1, 0, 13, 'Ready for some training?', 0 FROM `trainer`;

