-- Generated by localTools/customClasses/buildCustomClasses.py from classes.json. Do not edit.
-- Custom classes known to the client: token, name, color, class icon cell and the Dungeon
-- Finder roles it may queue as.
CustomClasses = {
    [12] = { token = "PESTIFERE", name = "Pestiféré", color = { 0.420, 0.580, 0.270 }, iconCell = { 3, 2 }, roles = { tank = true, healer = true, damage = true }, detailsCell = { 2, 2 } },
}
