-- The paragon board (mod-stat-growth ParagonSystem.cpp).
--
-- Talking to the keeper in Stormwind opens this. The board itself comes from ParagonBoard.lua, shipped in the
-- same patch and generated by the same script as the server's copy; the server only ever sends this frame the
-- character's own state, because an addon whisper caps at 255 bytes and 241 nodes would be a hundred of them.
--
-- The server decides what may be allocated. Everything here is presentation: a node the frame thinks is legal
-- is still checked before anything is spent.

local PREFIX = "Paragon"

local WINDOW_WIDTH, WINDOW_HEIGHT = 940, 640
-- The canvas takes everything the chrome does not: the title band ends 64 below the top, and the button row
-- needs about 36 at the bottom. The old insets left a band of bare ground under the tree.
local CANVAS_LEFT, CANVAS_TOP = 14, 66
local CANVAS_RIGHT, CANVAS_BOTTOM = 14, 42
-- The outermost node sits at radius 780 and is drawn 80 across, so 1700 holds the board with nothing spare.
-- Slack here is empty ground to pan into, and it is what let the board shrink away from the viewport.
local BOARD_EXTENT = 1700
local NODE_SIZE = { [0] = 44, [1] = 60, [2] = 80 }
-- Fraction of the node the icon is drawn at, per socket. Each fills that socket's hole and is cropped into a
-- circle by the ring, which draws over it - an icon smaller than the hole just shows its own square edge,
-- which is what it used to do. The values come from the art: buildParagonArt.py widens the minor and notable
-- rings inward until the corners of an icon this size land on metal, so the two move together.
local ICON_SCALE = { [0] = 0.61, [1] = 0.61, [2] = 0.50 }
-- The drawn height of the whole link texture, not of the bar inside it: the texture is mostly transparent
-- margin so that rotating it does not smear (buildParagonArt.py, padLinkBar). The bar is a quarter of this,
-- so the line reads as about 7 pixels.
local LINK_WIDTH = 28

local MIN_ZOOM, MAX_ZOOM, ZOOM_STEP = 0.4, 1.8, 0.12
-- Opens showing the hub and the first few rings rather than the whole board. Fitting all 217 nodes in the
-- window puts them at 17 pixels, which is unreadable; the far half of the tree is meant to be panned to.
local DEFAULT_ZOOM = 0.85

-- Locked branches stay visible but clearly out of reach: seeing what you are not going to get is most of what
-- a board this size is for. Not so faint they turn into texture, though - that was the first attempt.
local ALPHA_LOCKED, ALPHA_REACHABLE, ALPHA_TAKEN = 0.55, 0.85, 1.0

local TINT_LOCKED    = { 0.32, 0.32, 0.30 }
local TINT_REACHABLE = { 0.72, 0.62, 0.42 }
local TINT_TAKEN     = { 1.0, 0.78, 0.32 }

local SOUND_OPEN      = "AchievementMenuOpen"
local SOUND_CLOSE     = "AchievementMenuClose"
local SOUND_HOVER     = "GAMESCREENSMALLBUTTONMOUSEOVER"
local SOUND_MINOR     = "Glyph_MinorCreate"      -- inscribing minor power; the small click
local SOUND_NOTABLE   = "Glyph_MajorCreate"      -- the same sound with weight behind it
local SOUND_KEYSTONE  = "LEVELUPSOUND"           -- layered over the glyph, never instead of it
local SOUND_RESET     = "Glyph_MajorDestroy"     -- audibly the reverse of MajorCreate
local SOUND_DENIED    = "igQuestFailed"

local ART = "Interface\\Paragon\\"

local state = {
    open = false,
    cap = 50,
    available = 0,
    earned = 0,
    spent = 0,
    allocated = {},
    pending = nil,                          -- node waiting on the server's answer
    receiving = false,
}

local frame, canvas, board, pointText, spentText, statusText
local nodeButtons, linkTextures = {}, {}
local adjacency = {}
local animations = {}

--------------------------------------------------------------------------------
-- Board helpers
--------------------------------------------------------------------------------

local function buildAdjacency()
    if next(adjacency) then return end
    for _, link in ipairs(ParagonBoard.links) do
        local a, b = link[1], link[2]
        adjacency[a] = adjacency[a] or {}
        adjacency[b] = adjacency[b] or {}
        table.insert(adjacency[a], b)
        table.insert(adjacency[b], a)
    end
end

local function isAllocated(id)
    local node = ParagonBoard.nodes[id]
    if not node then return false end
    if node.free then return true end
    return state.allocated[id] == true
end

-- Reachable means "next to something already held", which is the same rule the server enforces.
local function isReachable(id)
    if isAllocated(id) then return false end
    for _, neighbour in ipairs(adjacency[id] or {}) do
        if isAllocated(neighbour) then return true end
    end
    return false
end

--------------------------------------------------------------------------------
-- Line drawing
--------------------------------------------------------------------------------

-- Rotating a texture between two points. 3.3.5 cannot anchor a texture's four corners independently, so the
-- rotation has to happen in the texture coordinates while the texture itself stays axis-aligned. This is the
-- long-standing community solution (wowpedia, "Drawing a line"), kept as-is because the trigonometry is
-- fiddly and well tested.
local function drawLine(texture, parent, sx, sy, ex, ey, width)
    local dx, dy = ex - sx, ey - sy
    local cx, cy = (sx + ex) / 2, (sy + ey) / 2
    if dx < 0 then
        dx, dy = -dx, -dy
    end

    local length = math.sqrt(dx * dx + dy * dy)
    if length < 0.5 then
        texture:Hide()
        return
    end

    local s, c = -dy / length, dx / length
    local sc = s * c
    local boxWidth, boxHeight
    local BLx, BLy, TLx, TLy, TRx, TRy, BRx, BRy

    if dy >= 0 then
        boxWidth, boxHeight = (length * c) - (width * s), (width * c) - (length * s)
        BLx, BLy, BRy = (width / length) * sc, s * s, (length / width) * sc
        BRx, TLx, TLy, TRx = 1 - BLy, BLy, 1 - BRy, 1 - BLx
        TRy = BRx
    else
        boxWidth, boxHeight = (length * c) + (width * s), (width * c) - (length * s)
        BLx, BLy, BRx = s * s, -(length / width) * sc, 1 + (width / length) * sc
        BRy, TLx, TLy, TRy = BLx, -BLy, 1 - BLx, 1 - BLx
        TRx = BRy
    end

    texture:ClearAllPoints()
    texture:SetTexCoord(TLx, TLy, BLx, BLy, TRx, TRy, BRx, BRy)
    texture:SetPoint("BOTTOMLEFT", parent, "BOTTOMLEFT", cx - (boxWidth / 2), cy - (boxHeight / 2))
    texture:SetPoint("TOPRIGHT", parent, "BOTTOMLEFT", cx + (boxWidth / 2), cy + (boxHeight / 2))
    texture:Show()
end

--------------------------------------------------------------------------------
-- Animation: the cascade when a node is taken
--------------------------------------------------------------------------------

local function addAnimation(entry)
    entry.elapsed = 0
    table.insert(animations, entry)
end

local function updateAnimations(elapsed)
    for index = #animations, 1, -1 do
        local animation = animations[index]
        animation.elapsed = animation.elapsed + elapsed
        local progress = animation.elapsed / animation.duration
        if progress >= 1 then
            animation.finish(animation)
            table.remove(animations, index)
        else
            animation.step(animation, progress)
        end
    end
end

-- The node swells and settles. Small, but it is what makes a click feel like it landed.
local function animateNode(button)
    local base = button.baseSize
    addAnimation({
        duration = 0.35,
        step = function(_, progress)
            local scale = progress < 0.4 and (1 + 0.3 * (progress / 0.4))
                or (1.3 - 0.3 * ((progress - 0.4) / 0.6))
            button:SetSize(base * scale, base * scale)
        end,
        finish = function() button:SetSize(base, base) end,
    })
end

-- The link behind it lights up as a spark runs along it. This is the part people remember, so it is the part
-- worth the frames.
local function animateLink(texture, sx, sy, ex, ey)
    local spark = board.sparkPool[#board.sparkPool]
    if not spark then return end
    table.remove(board.sparkPool)

    spark:SetAlpha(1)
    spark:Show()
    addAnimation({
        duration = 0.25,
        step = function(_, progress)
            spark:ClearAllPoints()
            spark:SetPoint("CENTER", board, "BOTTOMLEFT",
                sx + (ex - sx) * progress, sy + (ey - sy) * progress)
            texture:SetVertexColor(1, 0.85 + 0.15 * progress, 0.4 + 0.5 * progress)
        end,
        finish = function()
            spark:Hide()
            table.insert(board.sparkPool, spark)
        end,
    })
end

-- Newly reachable neighbours fade in a few frames apart, so the change ripples outward instead of popping.
local function animateRipple(button, delay)
    addAnimation({
        duration = delay + 0.25,
        step = function(_, progress)
            local total = delay + 0.25
            local started = (progress * total) - delay
            if started > 0 then
                button:SetAlpha(ALPHA_LOCKED + (ALPHA_REACHABLE - ALPHA_LOCKED) * (started / 0.25))
            end
        end,
        finish = function() button:SetAlpha(ALPHA_REACHABLE) end,
    })
end

local function flashCanvas()
    local flash = board.flash
    flash:SetAlpha(0.16)
    flash:Show()
    addAnimation({
        duration = 0.5,
        step = function(_, progress) flash:SetAlpha(0.16 * (1 - progress)) end,
        finish = function() flash:Hide() end,
    })
end

--------------------------------------------------------------------------------
-- Rendering
--------------------------------------------------------------------------------

local function refreshNode(id)
    local button = nodeButtons[id]
    if not button then return end

    local taken, reachable = isAllocated(id), isReachable(id)
    local tint = taken and TINT_TAKEN or (reachable and TINT_REACHABLE or TINT_LOCKED)
    button:SetAlpha(taken and ALPHA_TAKEN or (reachable and ALPHA_REACHABLE or ALPHA_LOCKED))
    button.glow:SetVertexColor(tint[1], tint[2], tint[3])
    button.glow:SetAlpha(taken and 0.5 or (reachable and 0.28 or 0.08))
    button.icon:SetDesaturated(not taken)
end

local function refreshLinks()
    for _, link in ipairs(linkTextures) do
        local lit = isAllocated(link.a) and isAllocated(link.b)
        if lit then
            link.texture:SetVertexColor(1, 0.85, 0.45)
            link.texture:SetAlpha(1)
        else
            local live = isAllocated(link.a) or isAllocated(link.b)
            link.texture:SetVertexColor(0.62, 0.72, 0.95)
            link.texture:SetAlpha(live and 0.8 or 0.42)
        end
    end
end

local function refreshHeader()
    pointText:SetText(state.available)
    spentText:SetFormattedText("%d / %d", state.spent, state.cap)

    local banked = state.earned - state.cap
    if banked > 0 then
        statusText:SetFormattedText("|cff888888%d point(s) en réserve|r", banked)
    else
        statusText:SetText("")
    end
end

local function refreshAll()
    for id in pairs(ParagonBoard.nodes) do
        refreshNode(id)
    end
    refreshLinks()
    refreshHeader()
end

--------------------------------------------------------------------------------
-- Frame construction
--------------------------------------------------------------------------------

local function nodePosition(node)
    return (BOARD_EXTENT / 2) + node.x, (BOARD_EXTENT / 2) + node.y
end

local PENDING_TIMEOUT = 3.0

local function allocate(id)
    if state.pending then return end
    if not isReachable(id) then
        PlaySound(SOUND_DENIED)
        return
    end
    if state.available <= 0 then
        PlaySound(SOUND_DENIED)
        UIErrorsFrame:AddMessage("Aucun point de parangon disponible.", 1, 0.3, 0.3, 1, 3)
        return
    end

    state.pending = id
    state.pendingAt = GetTime()
    SendAddonMessage(PREFIX, "ALLOC\t" .. id, "WHISPER", UnitName("player"))
end

local function onNodeEnter(self)
    local node = ParagonBoard.nodes[self.nodeId]
    PlaySound(SOUND_HOVER)
    -- Anchored right by default, but a node on the right of the screen would push the tooltip off it
    local centre = self:GetLeft()
    local side = (centre and centre > UIParent:GetWidth() * 0.6) and "ANCHOR_LEFT" or "ANCHOR_RIGHT"
    GameTooltip:SetOwner(self, side)
    GameTooltip:AddLine(node.name, 1, 0.82, 0.35)
    GameTooltip:AddLine(node.description, 1, 1, 1, true)
    if isAllocated(self.nodeId) then
        GameTooltip:AddLine("Acquis.", 0.4, 1, 0.4)
    elseif isReachable(self.nodeId) then
        GameTooltip:AddLine("Coût : 1 point.", 0.7, 0.8, 1)
    else
        GameTooltip:AddLine("Pas encore accessible.", 0.7, 0.4, 0.4)
    end
    GameTooltip:Show()
    self.glow:SetAlpha(math.min(1, self.glow:GetAlpha() + 0.35))
end

local function onNodeLeave(self)
    GameTooltip:Hide()
    refreshNode(self.nodeId)
end

local function createNode(id, node)
    local size = NODE_SIZE[node.type] or NODE_SIZE[0]
    local button = CreateFrame("Button", nil, board)
    button:SetSize(size, size)
    button.baseSize = size
    button.nodeId = id

    local x, y = nodePosition(node)
    button:SetPoint("CENTER", board, "BOTTOMLEFT", x, y)

    -- A dark disc under the socket. Without it the icon sits straight on the nebula and neither reads; this
    -- is the glow texture tinted black, so it is a soft round shadow rather than a square patch.
    button.backing = button:CreateTexture(nil, "BACKGROUND")
    button.backing:SetTexture(ART .. "Paragon-Node-Glow")
    button.backing:SetVertexColor(0, 0, 0)
    button.backing:SetAlpha(0.8)
    button.backing:SetPoint("CENTER")
    button.backing:SetSize(size * 1.25, size * 1.25)

    button.glow = button:CreateTexture(nil, "ARTWORK")
    button.glow:SetTexture(ART .. "Paragon-Node-Glow")
    button.glow:SetBlendMode("ADD")
    button.glow:SetPoint("CENTER")
    button.glow:SetSize(size * 1.25, size * 1.25)

    button.icon = button:CreateTexture(nil, "ARTWORK")
    button.icon:SetTexture(node.icon)
    button.icon:SetPoint("CENTER")
    local iconScale = ICON_SCALE[node.type] or ICON_SCALE[0]
    button.icon:SetSize(size * iconScale, size * iconScale)
    button.icon:SetTexCoord(0.08, 0.92, 0.08, 0.92)

    button.ring = button:CreateTexture(nil, "OVERLAY")
    button.ring:SetTexture(ART .. (node.type == 2 and "Paragon-Node-Keystone"
        or node.type == 1 and "Paragon-Node-Notable" or "Paragon-Node-Minor"))
    button.ring:SetAllPoints()

    button:SetScript("OnEnter", onNodeEnter)
    button:SetScript("OnLeave", onNodeLeave)
    button:SetScript("OnClick", function(self) allocate(self.nodeId) end)

    nodeButtons[id] = button
end

local function createBoard()
    buildAdjacency()

    for id, node in pairs(ParagonBoard.nodes) do
        createNode(id, node)
    end

    for _, link in ipairs(ParagonBoard.links) do
        local a, b = ParagonBoard.nodes[link[1]], ParagonBoard.nodes[link[2]]
        if a and b then
            local texture = board:CreateTexture(nil, "BORDER")
            texture:SetTexture(ART .. "Paragon-Link")
            local ax, ay = nodePosition(a)
            local bx, by = nodePosition(b)
            drawLine(texture, board, ax, ay, bx, by, LINK_WIDTH)
            table.insert(linkTextures, { texture = texture, a = link[1], b = link[2],
                ax = ax, ay = ay, bx = bx, by = by })
        end
    end

    board.sparkPool = {}
    for _ = 1, 8 do
        local spark = board:CreateTexture(nil, "OVERLAY")
        spark:SetTexture(ART .. "Paragon-Link-Spark")
        spark:SetBlendMode("ADD")
        spark:SetSize(28, 28)
        spark:Hide()
        table.insert(board.sparkPool, spark)
    end

    board.flash = frame:CreateTexture(nil, "OVERLAY")
    board.flash:SetTexture(1, 0.72, 0.28, 1)
    board.flash:SetBlendMode("ADD")
    board.flash:SetAllPoints(canvas)
    board.flash:Hide()
end

local function createChrome()
    RetailUI.ApplyNineSlice(frame, false)

    local header = frame:CreateTexture(nil, "BORDER")
    RetailUI.SetAtlas(header, "_UI-Frame-TopTileStreaks")
    header:SetHeight(43)
    header:SetPoint("TOPLEFT", frame, "TOPLEFT", 6, -21)
    header:SetPoint("TOPRIGHT", frame, "TOPRIGHT", -2, -21)

    local function insetCorner(atlas, point)
        local texture = frame:CreateTexture(nil, "ARTWORK")
        RetailUI.SetAtlas(texture, atlas, true)
        texture:SetPoint(point, canvas, point)
        return texture
    end
    local topLeft = insetCorner("UI-Frame-InnerTopLeft", "TOPLEFT")
    local topRight = insetCorner("UI-Frame-InnerTopRight", "TOPRIGHT")
    local bottomLeft = insetCorner("UI-Frame-InnerBotLeftCorner", "BOTTOMLEFT")
    local bottomRight = insetCorner("UI-Frame-InnerBotRight", "BOTTOMRIGHT")
    local function insetEdge(atlas, vertical, firstPoint, firstAnchor, firstRelative,
            secondPoint, secondAnchor, secondRelative)
        local texture = frame:CreateTexture(nil, "ARTWORK")
        RetailUI.SetAtlas(texture, atlas)
        if vertical then texture:SetWidth(3) else texture:SetHeight(3) end
        texture:SetPoint(firstPoint, firstAnchor, firstRelative)
        texture:SetPoint(secondPoint, secondAnchor, secondRelative)
    end
    insetEdge("!UI-Frame-InnerLeftTile", true, "TOPLEFT", topLeft, "BOTTOMLEFT",
        "BOTTOMLEFT", bottomLeft, "TOPLEFT")
    insetEdge("!UI-Frame-InnerRightTile", true, "TOPRIGHT", topRight, "BOTTOMRIGHT",
        "BOTTOMRIGHT", bottomRight, "TOPRIGHT")
    insetEdge("_UI-Frame-InnerTopTile", false, "TOPLEFT", topLeft, "TOPRIGHT",
        "TOPRIGHT", topRight, "TOPLEFT")
    insetEdge("_UI-Frame-InnerBotTile", false, "BOTTOMLEFT", bottomLeft, "BOTTOMRIGHT",
        "BOTTOMRIGHT", bottomRight, "BOTTOMLEFT")

    -- Centred in the title band, which runs from 21 to 64 below the top of the frame. At -8 the text sat
    -- above the band entirely and its descenders were cut by the band's own top edge.
    local title = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
    title:SetPoint("TOP", frame, "TOP", 0, -32)
    title:SetText("Parangon")
    title:SetTextColor(1, 0.82, 0)

    local orb = CreateFrame("Frame", nil, frame)
    orb:SetSize(72, 72)
    orb:SetPoint("TOPLEFT", frame, "TOPLEFT", 36, -38)
    local orbBackground = orb:CreateTexture(nil, "ARTWORK")
    RetailUI.SetAtlas(orbBackground, "ChallengeMode-KeystoneSlotBG")
    orbBackground:SetAllPoints()
    local orbFrame = orb:CreateTexture(nil, "OVERLAY")
    RetailUI.SetAtlas(orbFrame, "ChallengeMode-KeystoneSlotFrame")
    orbFrame:SetPoint("CENTER")
    orbFrame:SetSize(76, 76)

    pointText = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalHuge")
    pointText:SetPoint("CENTER", orb, "CENTER", 0, 2)
    pointText:SetTextColor(0.7, 0.9, 1)

    spentText = frame:CreateFontString(nil, "OVERLAY", "GameFontNormal")
    spentText:SetPoint("TOP", orb, "BOTTOM", 0, -2)

    statusText = frame:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    statusText:SetPoint("TOPLEFT", orb, "BOTTOMLEFT", -10, -22)

    local closeButton = CreateFrame("Button", nil, frame)
    closeButton:SetSize(24, 24)
    closeButton:SetPoint("TOPRIGHT", frame, "TOPRIGHT", -5, -5)
    closeButton:SetFrameLevel(frame:GetFrameLevel() + 20)
    closeButton:SetNormalTexture(RetailUIAtlas["redbutton-exit-2x"][1])
    RetailUI.SetAtlas(closeButton:GetNormalTexture(), "redbutton-exit-2x")
    closeButton:SetPushedTexture(RetailUIAtlas["redbutton-exit-pressed-2x"][1])
    RetailUI.SetAtlas(closeButton:GetPushedTexture(), "redbutton-exit-pressed-2x")
    closeButton:SetHighlightTexture(RetailUIAtlas["redbutton-highlight-2x"][1])
    RetailUI.SetAtlas(closeButton:GetHighlightTexture(), "redbutton-highlight-2x")
    closeButton:GetHighlightTexture():SetBlendMode("ADD")
    closeButton:SetScript("OnClick", function() frame:Hide() end)
end

-- Sized to the label rather than to a number picked in advance: a stock panel button is meant to hug its
-- text, and "Fermer" in a 170 wide plate is what made these look like placeholders.
local function createButton(label, anchorPoint, offsetX, onClick)
    local button = CreateFrame("Button", nil, frame, "UIPanelButtonTemplate")
    button:SetHeight(22)
    button:SetPoint(anchorPoint, frame, anchorPoint, offsetX, 16)
    button:SetText(label)
    button:SetWidth(math.max(96, button:GetFontString():GetStringWidth() + 32))

    button:SetScript("OnClick", onClick)
    return button
end

local function panTo(x, y)
    local scale = board:GetScale()
    local maxX = math.max(0, BOARD_EXTENT - canvas:GetWidth() / scale)
    local maxY = math.max(0, BOARD_EXTENT - canvas:GetHeight() / scale)
    canvas:SetHorizontalScroll(math.max(0, math.min(maxX, x)))
    canvas:SetVerticalScroll(math.max(0, math.min(maxY, y)))
end

-- What sits in the middle of the viewport, in board coordinates.
local function viewCentre()
    local scale = board:GetScale()
    return canvas:GetHorizontalScroll() + canvas:GetWidth() / (2 * scale),
           canvas:GetVerticalScroll() + canvas:GetHeight() / (2 * scale)
end

local function centreOn(x, y)
    local scale = board:GetScale()
    panTo(x - canvas:GetWidth() / (2 * scale), y - canvas:GetHeight() / (2 * scale))
end

-- How far out the board may be zoomed before it stops covering the viewport. A scroll frame cannot take a
-- negative offset, so past that point there is nothing left to scroll: the board pins to the top left and
-- leaves bare ground down the right hand side instead of sitting in the middle. Zooming out stops there.
local function zoomFloor()
    local width, height = canvas:GetWidth(), canvas:GetHeight()
    if not width or width <= 0 then
        return MIN_ZOOM
    end
    return math.max(MIN_ZOOM, width / BOARD_EXTENT, height / BOARD_EXTENT)
end

-- Zooming has to hold the middle of the view still. SetScale alone scales the child about its own top-left
-- anchor, so the board slides into the corner as it shrinks - which is exactly what it was doing.
local function setZoom(scale)
    scale = math.max(zoomFloor(), math.min(MAX_ZOOM, scale))
    if math.abs(scale - board:GetScale()) < 0.001 then
        return
    end

    local cx, cy = viewCentre()
    board:SetScale(scale)
    canvas:UpdateScrollChildRect()
    centreOn(cx, cy)
end

local function createFrame()
    frame = CreateFrame("Frame", "ParagonFrame", UIParent)
    frame:SetSize(WINDOW_WIDTH, WINDOW_HEIGHT)
    frame:SetPoint("CENTER")
    frame:SetFrameStrata("HIGH")
    frame:EnableMouse(true)
    frame:SetMovable(true)
    frame:Hide()

    local ground = frame:CreateTexture(nil, "BACKGROUND")
    ground:SetTexture(RetailUIFiles["ui-background-rock"], true)
    ground:SetHorizTile(true)
    ground:SetVertTile(true)
    ground:SetPoint("TOPLEFT", CANVAS_LEFT, -CANVAS_TOP)
    ground:SetPoint("BOTTOMRIGHT", -CANVAS_RIGHT, CANVAS_BOTTOM)

    -- 3.3.5 clips nothing but a scroll frame, so the pannable board has to live inside one.
    canvas = CreateFrame("ScrollFrame", "ParagonCanvas", frame)
    canvas:SetPoint("TOPLEFT", CANVAS_LEFT, -CANVAS_TOP)
    canvas:SetPoint("BOTTOMRIGHT", -CANVAS_RIGHT, CANVAS_BOTTOM)
    canvas:EnableMouse(true)
    canvas:EnableMouseWheel(true)

    board = CreateFrame("Frame", "ParagonBoardCanvas", canvas)
    board:SetSize(BOARD_EXTENT, BOARD_EXTENT)
    canvas:SetScrollChild(board)
    -- Without this the scroll frame does not know how far the child extends and refuses to scroll
    canvas:UpdateScrollChildRect()

    canvas:SetScript("OnMouseWheel", function(_, delta)
        setZoom(board:GetScale() + delta * ZOOM_STEP)
    end)

    canvas:SetScript("OnMouseDown", function(self)
        self.dragging = true
        self.startX, self.startY = GetCursorPosition()
        self.startH, self.startV = self:GetHorizontalScroll(), self:GetVerticalScroll()
    end)
    canvas:SetScript("OnMouseUp", function(self) self.dragging = false end)
    canvas:SetScript("OnUpdate", function(self, elapsed)
        updateAnimations(elapsed)
        -- Release a click the server never answered, rather than wedging every click after it
        if state.pending and GetTime() - (state.pendingAt or 0) > PENDING_TIMEOUT then
            state.pending = nil
        end
        if not self.dragging then return end
        local x, y = GetCursorPosition()
        local scale = board:GetScale() * UIParent:GetEffectiveScale()
        panTo(self.startH + (self.startX - x) / scale, self.startV - (self.startY - y) / scale)
    end)

    createChrome()

    -- The window's handle: the banner across the top, and the border strip under it. Kept clear of the canvas
    -- so the two drags never fight over the same pixel.
    local mover = CreateFrame("Frame", nil, frame)
    mover:SetPoint("BOTTOMLEFT", frame, "TOPLEFT", 0, -CANVAS_TOP)
    mover:SetPoint("BOTTOMRIGHT", frame, "TOPRIGHT", 0, -CANVAS_TOP)
    mover:SetHeight(CANVAS_TOP)
    mover:EnableMouse(true)
    mover:RegisterForDrag("LeftButton")
    mover:SetScript("OnDragStart", function() frame:StartMoving() end)
    mover:SetScript("OnDragStop", function() frame:StopMovingOrSizing() end)

    createBoard()

    createButton("Réinitialiser", "BOTTOMLEFT", 24, function()
        state.pendingReset = true
        SendAddonMessage(PREFIX, "RESET", "WHISPER", UnitName("player"))
    end)

    -- Escape closes it. This is how 3.3.5 does it: SetPropagateKeyboardInput arrived two expansions later, and
    -- a hand-rolled OnKeyDown would swallow every other key the frame happens to have focus for.
    tinsert(UISpecialFrames, "ParagonFrame")

    -- Hung off OnHide so the button, Escape and anything else that closes the frame all behave the same.
    frame:SetScript("OnHide", function()
        PlaySound(SOUND_CLOSE)
        state.open = false
    end)
end

--------------------------------------------------------------------------------
-- Server messages
--------------------------------------------------------------------------------

local function onAllocated(id)
    local node = ParagonBoard.nodes[id]
    if not node then return end

    state.allocated[id] = true
    state.pending = nil

    local button = nodeButtons[id]
    local neighbours = {}
    for _, neighbour in ipairs(adjacency[id] or {}) do
        if not isAllocated(neighbour) then
            table.insert(neighbours, neighbour)
        end
    end

    -- Light the link that was just completed, from whichever held node it came from
    for _, link in ipairs(linkTextures) do
        if (link.a == id and isAllocated(link.b)) or (link.b == id and isAllocated(link.a)) then
            local sx, sy, ex, ey = link.ax, link.ay, link.bx, link.by
            if link.a == id then sx, sy, ex, ey = link.bx, link.by, link.ax, link.ay end
            animateLink(link.texture, sx, sy, ex, ey)
            break
        end
    end

    animateNode(button)
    refreshAll()

    -- Staggered so the newly available ring spreads outward rather than appearing all at once
    for index, neighbour in ipairs(neighbours) do
        local neighbourButton = nodeButtons[neighbour]
        if neighbourButton then
            neighbourButton:SetAlpha(ALPHA_LOCKED)
            animateRipple(neighbourButton, 0.05 * index)
        end
    end

    if node.type == 2 then
        PlaySound(SOUND_NOTABLE)
        PlaySound(SOUND_KEYSTONE)
        flashCanvas()
    elseif node.type == 1 then
        PlaySound(SOUND_NOTABLE)
    else
        PlaySound(SOUND_MINOR)
    end
end

local function handle(message)
    local command, rest = message:match("^([^\t]+)\t?(.*)$")
    if not command then return end

    if command == "OPEN" or command == "STATE" then
        local signature, cap, available, earned, spent = rest:match("^(%d+)\t(%d+)\t(%d+)\t(%d+)\t(%d+)$")
        if not signature then return end

        if tonumber(signature) ~= ParagonBoard.signature then
            UIErrorsFrame:AddMessage(
                "Tableau de parangon désynchronisé : le patch du client ne correspond pas au serveur.",
                1, 0.3, 0.3, 1, 6)
        end

        state.cap, state.available = tonumber(cap), tonumber(available)
        state.earned, state.spent = tonumber(earned), tonumber(spent)
        if state.pendingReset then
            -- Glyph_MajorDestroy is audibly Glyph_MajorCreate reversed, so a board being cleared sounds like
            -- the undoing of the nodes that built it
            PlaySound(SOUND_RESET)
            state.pendingReset = nil
        end
        state.allocated = {}
        state.receiving = true
        state.opening = (command == "OPEN")
        return
    end

    if command == "NODES" then
        if not state.receiving then return end
        for id in rest:gmatch("(%d+)") do
            state.allocated[tonumber(id)] = true
        end
        return
    end

    if command == "DONE" then
        state.receiving = false
        if not frame then createFrame() end
        refreshAll()
        if state.opening and not state.open then
            state.open = true
            frame:Show()
            PlaySound(SOUND_OPEN)
            -- Start centred on the hub; the board reads from the middle outward
            setZoom(DEFAULT_ZOOM)
            centreOn(BOARD_EXTENT / 2, BOARD_EXTENT / 2)
        end
        state.opening = false
        return
    end

    if command == "GAINED" then
        local id, available, spent = rest:match("^(%d+)\t(%d+)\t(%d+)$")
        if not id then return end
        state.available, state.spent = tonumber(available), tonumber(spent)
        onAllocated(tonumber(id))
        return
    end

    if command == "POINT" then
        local available, earned = rest:match("^(%d+)\t(%d+)$")
        if available then
            state.available, state.earned = tonumber(available), tonumber(earned)
            if frame and frame:IsShown() then refreshHeader() end
        end
        return
    end

    if command == "ERROR" then
        state.pending = nil
        state.pendingReset = nil
        PlaySound(SOUND_DENIED)
        UIErrorsFrame:AddMessage(rest, 1, 0.3, 0.3, 1, 3)
        return
    end
end

local listener = CreateFrame("Frame")
listener:RegisterEvent("CHAT_MSG_ADDON")
listener:SetScript("OnEvent", function(_, event, prefix, message, _, sender)
    if event ~= "CHAT_MSG_ADDON" or prefix ~= PREFIX or sender ~= UnitName("player") then
        return
    end
    handle(message)
end)

-- Also reachable without walking to the keeper, which matters while building the board out.
SLASH_PARAGON1 = "/paragon"
SlashCmdList["PARAGON"] = function()
    SendAddonMessage(PREFIX, "OPEN", "WHISPER", UnitName("player"))
end
