-- Generated by localTools/interface/extractRetailUi.py from retail atlas data. Do not edit.
-- name = { file, width, height, left, right, top, bottom, horizTile, vertTile }
RetailUIAtlas = {
    ["ui-frame-portraitmetal-cornertopleft-2x"] = { "Interface\\RetailUI\\ui-frame-portraitmetal-cornertopleft-2x", 75, 75, 0, 0.585938, 0, 0.585938, false, false },
    ["ui-frame-metal-cornertopleft-2x"] = { "Interface\\RetailUI\\ui-frame-metal-cornertopleft-2x", 75, 75, 0, 0.585938, 0, 0.585938, false, false },
    ["ui-frame-metal-cornertopright-2x"] = { "Interface\\RetailUI\\ui-frame-metal-cornertopright-2x", 75, 75, 0, 0.585938, 0, 0.585938, false, false },
    ["ui-frame-metal-cornerbottomleft-2x"] = { "Interface\\RetailUI\\ui-frame-metal-cornerbottomleft-2x", 32, 32, 0, 1.000000, 0, 1.000000, false, false },
    ["ui-frame-metal-cornerbottomright-2x"] = { "Interface\\RetailUI\\ui-frame-metal-cornerbottomright-2x", 32, 32, 0, 1.000000, 0, 1.000000, false, false },
    ["_ui-frame-metal-edgetop-2x"] = { "Interface\\RetailUI\\ui-frame-metal-edgetop-2x", 32, 75, 0, 1.000000, 0, 0.585938, true, false },
    ["_ui-frame-metal-edgebottom-2x"] = { "Interface\\RetailUI\\ui-frame-metal-edgebottom-2x", 16, 32, 0, 1.000000, 0, 1.000000, true, false },
    ["!ui-frame-metal-edgeleft-2x"] = { "Interface\\RetailUI\\ui-frame-metal-edgeleft-2x", 75, 16, 0, 0.585938, 0, 1.000000, false, true },
    ["!ui-frame-metal-edgeright-2x"] = { "Interface\\RetailUI\\ui-frame-metal-edgeright-2x", 75, 16, 0, 0.585938, 0, 1.000000, false, true },
    ["_UI-Frame-TopTileStreaks"] = { "Interface\\RetailUI\\ui-frame-toptilestreaks", 256, 43, 0, 1.000000, 0, 0.671875, true, false },
    ["UI-Frame-InnerTopLeft"] = { "Interface\\RetailUI\\ui-frame-innertopleft", 6, 6, 0, 0.750000, 0, 0.750000, false, false },
    ["UI-Frame-InnerTopRight"] = { "Interface\\RetailUI\\ui-frame-innertopright", 6, 6, 0, 0.750000, 0, 0.750000, false, false },
    ["UI-Frame-InnerBotLeftCorner"] = { "Interface\\RetailUI\\ui-frame-innerbotleftcorner", 6, 6, 0, 0.750000, 0, 0.750000, false, false },
    ["UI-Frame-InnerBotRight"] = { "Interface\\RetailUI\\ui-frame-innerbotright", 6, 6, 0, 0.750000, 0, 0.750000, false, false },
    ["!UI-Frame-InnerLeftTile"] = { "Interface\\RetailUI\\ui-frame-innerlefttile", 3, 256, 0, 0.750000, 0, 1.000000, false, true },
    ["!UI-Frame-InnerRightTile"] = { "Interface\\RetailUI\\ui-frame-innerrighttile", 3, 256, 0, 0.750000, 0, 1.000000, false, true },
    ["_UI-Frame-InnerTopTile"] = { "Interface\\RetailUI\\ui-frame-innertoptile", 256, 3, 0, 1.000000, 0, 0.750000, true, false },
    ["_UI-Frame-InnerBotTile"] = { "Interface\\RetailUI\\ui-frame-innerbottile", 256, 3, 0, 1.000000, 0, 0.750000, true, false },
    ["redbutton-exit-2x"] = { "Interface\\RetailUI\\redbutton-exit-2x", 24, 24, 0, 0.562500, 0, 0.593750, false, false },
    ["redbutton-exit-pressed-2x"] = { "Interface\\RetailUI\\redbutton-exit-pressed-2x", 24, 24, 0, 0.562500, 0, 0.593750, false, false },
    ["redbutton-exit-disabled-2x"] = { "Interface\\RetailUI\\redbutton-exit-disabled-2x", 24, 24, 0, 0.562500, 0, 0.593750, false, false },
    ["redbutton-highlight-2x"] = { "Interface\\RetailUI\\redbutton-highlight-2x", 24, 24, 0, 0.562500, 0, 0.593750, false, false },
    ["questbg-parchment"] = { "Interface\\RetailUI\\questbg-parchment", 299, 407, 0, 0.583984, 0, 0.794922, false, false },
}
RetailUIFiles = {
    ["ui-background-rock"] = "Interface\\RetailUI\\ui-background-rock",
    ["ui-background-marble"] = "Interface\\RetailUI\\ui-background-marble",
}
