-- Gardien-chef Vorhan's eye (mod-stat-growth WardenVorhan.cpp, the gaze): drawn in the interface over his torso, so
-- nothing hides it - neither his nameplate nor the world (a model in the world was hidden behind the nameplate). The
-- server says when: "GAZE <guid> <ms> <height> <width>" on the WardenVorhan prefix, the eye opening over `ms` at
-- `height` yards over the unit's feet, `width` yards wide. Where that is on screen comes from the client extension's
-- UnitScreenPosition. Its 64 frames (8 x 8 in WardenGaze.blp) and their timeline:
-- localTools/wardenVorhan/buildGazeUi.py.
local PREFIX = "WardenVorhan"
local ATLAS = "Interface\\WardenVorhan\\WardenGaze"
local GRID = 8
-- The frames' shape (256 x 128) and how small or big the eye may get on screen, whatever the distance (pixels wide)
local ASPECT = 2
local SMALLEST, LARGEST = 120, 560
-- After the opening: its burst held, then faded out (seconds)
local HOLD, FADE = 0.5, 0.35
-- Its height when it cannot be placed on the unit (pixels)
local FALLBACK = 150

-- Generated by buildGazeUi.py: { ms from the start, frame }
local TIMELINE = {
    { 0, 0 }, { 96, 1 }, { 192, 2 }, { 288, 3 }, { 385, 4 }, { 481, 5 }, { 577, 6 }, { 673, 7 },
    { 769, 8 }, { 865, 9 }, { 962, 10 }, { 1058, 11 }, { 1154, 12 }, { 1250, 13 }, { 1346, 14 }, { 1442, 15 },
    { 1538, 16 }, { 1635, 17 }, { 1731, 18 }, { 1827, 19 }, { 1923, 20 }, { 2019, 21 }, { 2115, 22 }, { 2212, 23 },
    { 2308, 24 }, { 2404, 25 }, { 2500, 26 }, { 2596, 27 }, { 2692, 28 }, { 2788, 29 }, { 2885, 30 }, { 2981, 31 },
    { 3077, 32 }, { 3173, 33 }, { 3269, 34 }, { 3365, 35 }, { 3462, 36 }, { 3558, 37 }, { 3654, 38 }, { 3750, 39 },
    { 3846, 40 }, { 3942, 41 }, { 4038, 42 }, { 4135, 43 }, { 4231, 44 }, { 4327, 45 }, { 4423, 46 }, { 4519, 47 },
    { 4615, 48 }, { 4712, 49 }, { 4808, 50 }, { 4904, 51 }, { 5000, 53 }, { 5150, 52 }, { 5282, 54 }, { 5398, 53 },
    { 5500, 55 }, { 5590, 54 }, { 5669, 56 }, { 5739, 55 }, { 5800, 57 }, { 5854, 56 }, { 5901, 58 }, { 5946, 57 },
    { 6000, 63 },
}

local frame = CreateFrame("Frame", nil, WorldFrame)
-- Over everything the world and the interface draw, but the dialogs and the tooltips
frame:SetFrameStrata("FULLSCREEN")
frame:SetSize(ASPECT * SMALLEST, SMALLEST)
frame:Hide()
local eye = frame:CreateTexture(nil, "OVERLAY")
eye:SetAllPoints()
eye:SetTexture(ATLAS)

local gaze

local function ShowFrame(index)
    local column, row = index % GRID, math.floor(index / GRID)
    eye:SetTexCoord(column / GRID, (column + 1) / GRID, row / GRID, (row + 1) / GRID)
end

local function FrameAt(ms)
    local index = TIMELINE[1][2]
    for _, key in ipairs(TIMELINE) do
        if key[1] > ms then
            break
        end
        index = key[2]
    end
    return index
end

frame:SetScript("OnUpdate", function(self)
    if not gaze then
        self:Hide()
        return
    end
    local elapsed = GetTime() - gaze.start
    local length = gaze.ms / 1000
    if elapsed > length + HOLD + FADE then
        gaze = nil
        self:Hide()
        return
    end
    -- The timeline is 6 s long: a longer or shorter gaze plays it at its own pace
    ShowFrame(FrameAt(elapsed / length * 6000))
    eye:SetAlpha(elapsed > length + HOLD and math.max(0, 1 - (elapsed - length - HOLD) / FADE) or 1)
    self:ClearAllPoints()
    -- Where: on the unit's torso (the client extension's projection); failing that under its nameplate; failing that
    -- high in the middle of the screen - never not at all. Why it fell back is said once in the chat.
    local u, v, depth, tangent
    if UnitScreenPosition then
        u, v, depth, tangent = UnitScreenPosition(gaze.guid, gaze.height)
    end
    if u and depth and tangent and tangent > 0 then
        local width, height = WorldFrame:GetWidth(), WorldFrame:GetHeight()
        local pixels = gaze.width / (2 * depth * tangent) * height
        pixels = math.max(SMALLEST, math.min(LARGEST, pixels))
        self:SetSize(pixels, pixels / ASPECT)
        self:SetPoint("CENTER", WorldFrame, "TOPLEFT", u * width, -v * height)
        return
    end
    local plate = C_NamePlate and C_NamePlate.GetNamePlateByGUID and C_NamePlate.GetNamePlateByGUID(gaze.guid)
    self:SetSize(2 * FALLBACK, FALLBACK)
    if plate and plate:IsShown() then
        self:SetPoint("TOP", plate, "BOTTOM", 0, -10)
    else
        self:SetPoint("CENTER", WorldFrame, "TOP", 0, -WorldFrame:GetHeight() * 0.3)
    end
    if not gaze.told then
        gaze.told = true
        local where = plate and "sous la barre de nom." or "en haut de l'écran."
        local why = UnitScreenPosition and ("position à l'écran introuvable pour " .. tostring(gaze.guid)) or
            "UnitScreenPosition absent (extension du client pas à jour)"
        DEFAULT_CHAT_FRAME:AddMessage(format("|cffd0a060Regard du geôlier :|r %s, œil affiché %s", why, where))
    end
end)

local listener = CreateFrame("Frame")
listener:RegisterEvent("CHAT_MSG_ADDON")
listener:SetScript("OnEvent", function(_, _, prefix, message)
    if prefix ~= PREFIX then
        return
    end
    local kind, guid, ms, height, width = strsplit("\t", message)
    if kind ~= "GAZE" or not guid then
        return
    end
    gaze = { guid = guid, ms = tonumber(ms) or 6000, height = tonumber(height) or 4, width = tonumber(width) or 5,
        start = GetTime() }
    ShowFrame(0)
    frame:Show()
end)
