using System.Reflection;
using System.Text;
using System.Text.Json;
using MultiConverter.Lib.Converters;

namespace RetailImport;

public sealed class Manifest
{
    public string OutputRoot { get; set; }
    public string Generated { get; set; }
    public string Sql { get; set; }
    // Body textures at the stock size (half retail's) rather than retail's own
    public bool HalveBodyTextures { get; set; }
    public List<DisplaySpec> Displays { get; set; } = [];
    public List<ItemSpec> Items { get; set; } = [];
}

public sealed class DisplaySpec
{
    public int Id { get; set; }
    public int RetailDisplay { get; set; }
    public string Slot { get; set; }
    public int Clone { get; set; }
    // A helmet's HelmetGeosetVisData ids (male, female: the hair and ears it hides); the clone's when absent
    public int[] HelmetVis { get; set; }
    public string Note { get; set; }
}

public sealed class ItemSpec
{
    public int Entry { get; set; }
    public int Display { get; set; }
    public int Class { get; set; }
    public int Subclass { get; set; }
    public int Material { get; set; }
    public int InventoryType { get; set; }
    public int Sheath { get; set; }
    public int StatsFrom { get; set; }
    public string Name { get; set; }
    public string NameFr { get; set; }
    public string Description { get; set; }
    public string DescriptionFr { get; set; }
}

/// <summary>
/// Converts the retail looks named in items.json into 3.3.5 client files and the rows that use them:
/// - models (.m2 + .skin) under OutputRoot at their archive path, Item\ObjectComponents\{Weapon|Shoulder}\
/// - the textures ItemDisplayInfo gives them, beside them; the textures the models hardcode, in a Retail\ subfolder
///   (some share a name with a different stock file, armorreflect4.blp for one, which must not be replaced)
/// - the inventory icons, Interface\Icons\
/// - Generated: the ItemDisplayInfo.dbc and Item.dbc rows localTools\patchSinisterStrike.ps1 installs
/// - Sql: the item_template rows of the test items
/// </summary>
public sealed class Importer(Retail retail, string repoRoot, string workDir)
{
    private readonly Dictionary<uint, string> convertedModels = new();
    private readonly Dictionary<uint, string> copiedTextures = new();
    private readonly Dictionary<string, uint> bodyTextureOwners = new(StringComparer.OrdinalIgnoreCase);
    private bool halveBodyTextures;
    private readonly List<string> report = [];
    private bool failed;
    private string outputRoot;

    private sealed record Row(int Id, int CloneOf, string[] ModelName, string[] ModelTexture, string Icon,
        string[] BodyTextures, int[] Geosets, int[] HelmetVis, string Note, object Retail);

    public bool Run(Manifest manifest)
    {
        outputRoot = Path.Combine(repoRoot, manifest.OutputRoot);
        halveBodyTextures = manifest.HalveBodyTextures;
        if (Directory.Exists(outputRoot))
            Directory.Delete(outputRoot, true);
        Directory.CreateDirectory(outputRoot);
        Directory.CreateDirectory(workDir);

        var rows = new List<Row>();
        foreach (var display in manifest.Displays)
            rows.Add(ImportDisplay(display));

        foreach (var item in manifest.Items)
            if (manifest.Displays.All(display => display.Id != item.Display))
                Fail($"item {item.Entry} uses display {item.Display}, which items.json does not import");

        var generated = new
        {
            comment = "Generated by localTools/retailImport (RetailImport import) - do not edit by hand.",
            displays = rows,
            items = manifest.Items.Select(item => new
            {
                item.Entry, item.Class, item.Subclass, item.Material, item.Display, item.InventoryType, item.Sheath,
            }),
        };
        File.WriteAllText(Path.Combine(repoRoot, manifest.Generated),
            JsonSerializer.Serialize(generated, new JsonSerializerOptions
            {
                WriteIndented = true, NewLine = "\n", PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            }) + "\n");
        File.WriteAllText(Path.Combine(repoRoot, manifest.Sql), BuildSql(manifest), new UTF8Encoding(false));

        foreach (var line in report)
            Console.WriteLine(line);
        Console.WriteLine(failed ? "Import FAILED" : $"Imported {rows.Count} displays into {manifest.OutputRoot}");
        return !failed;
    }

    private void Fail(string message)
    {
        failed = true;
        report.Add("ERROR " + message);
    }

    // ChrRaces ids the 3.3.5 client has, and the suffix its head models carry (Item\ObjectComponents\Head\
    // <name>_<Race><M|F>.m2): retail names them the same way, in lower case
    private static readonly Dictionary<int, string> ClassicRaces = new()
    {
        [1] = "Hu", [2] = "Or", [3] = "Dw", [4] = "Ni", [5] = "Sc", [6] = "Ta", [7] = "Gn", [8] = "Tr", [10] = "Be",
        [11] = "Dr",
    };

    // ItemDisplayInfoMaterialRes.ComponentSection -> the 3.3.5 folder of that region's textures
    private static readonly string[] SectionFolders =
    [
        "ArmUpperTexture", "ArmLowerTexture", "HandTexture", "TorsoUpperTexture", "TorsoLowerTexture",
        "LegUpperTexture", "LegLowerTexture", "FootTexture",
    ];

    private Row ImportDisplay(DisplaySpec spec)
    {
        var display = retail.Table("ItemDisplayInfo")[spec.RetailDisplay];
        var modelResources = (uint[])display["ModelResourcesID"];
        var materialResources = (int[])display["ModelMaterialResourcesID"];
        report.Add($"display {spec.Id} <- retail display {spec.RetailDisplay} ({spec.Note})");

        var modelNames = new[] { "", "" };
        var modelTextures = new[] { "", "" };
        var retailModels = new List<uint>();
        var retailTextures = new List<uint>();
        switch (spec.Slot)
        {
            case "weapon":
            case "shoulder":
                ImportRigidModels(spec, modelResources, materialResources, modelNames, modelTextures, retailModels,
                    retailTextures);
                break;
            case "head":
                ImportHead(spec, modelResources[0], materialResources[0], modelNames, modelTextures, retailModels,
                    retailTextures);
                break;
            case "cape":
            {
                // A cape is the character's cape geoset painted with this texture
                var texture = Probe.TextureFiles(retail, materialResources[0]).Select(t => t.fdid).FirstOrDefault();
                if (texture == 0)
                    throw new Exception($"display {spec.Id}: retail display {spec.RetailDisplay} has no cape texture");
                modelTextures[0] = CopyTexture(texture, @"Item\ObjectComponents\Cape\");
                retailTextures.Add(texture);
                break;
            }
            case "body":
                break;
            default:
                throw new Exception(
                    $"display {spec.Id}: slot {spec.Slot} is not supported (weapon, shoulder, head, cape, body)");
        }

        // Every piece but a weapon paints the regions retail gives it; 3.3.5 has no Accessory or Scalp region
        var bodyTextures = Enumerable.Repeat("", 8).ToArray();
        if (spec.Slot != "weapon")
            foreach (var (section, materialId) in Probe.BodyMaterials(retail, spec.RetailDisplay))
            {
                if (section >= SectionFolders.Length)
                {
                    report.Add($"  WARNING retail region {Probe.SectionNames[section]} dropped (no 3.3.5 region)");
                    continue;
                }
                bodyTextures[section] = CopyBodyTexture(materialId, SectionFolders[section], retailTextures);
            }
        if (spec.Slot is "body" or "head" && modelResources.Any(resource => resource != 0) && spec.Slot != "head")
            report.Add($"  WARNING display {spec.Id}: its retail models (collections, a buckle) are not imported:"
                       + " 3.3.5 draws no model on that slot");

        // The geoset groups 3.3.5 knows are retail's first three (gloves, boots, cape, robe...)
        var geosets = ((int[])display["GeosetGroup"]).Take(3).ToArray();

        var appearance = retail.Table("ItemAppearance").Values
            .FirstOrDefault(row => (int)row["ItemDisplayInfoID"] == spec.RetailDisplay);
        var icon = "";
        uint iconFile = 0;
        if (appearance != null && (iconFile = (uint)(int)appearance["DefaultIconFileDataID"]) != 0)
            icon = CopyTexture(iconFile, @"Interface\Icons\");
        else
            report.Add($"  no retail icon for display {spec.RetailDisplay}; the clone's icon stays");

        return new Row(spec.Id, spec.Clone, modelNames, modelTextures, icon, bodyTextures, geosets, spec.HelmetVis,
            spec.Note, new
        {
            display = spec.RetailDisplay,
            models = retailModels.Select(fdid => $"{fdid} {retail.NameOf(fdid)}"),
            textures = retailTextures.Select(fdid => $"{fdid} {retail.NameOf(fdid)}"),
            icon = iconFile != 0 ? $"{iconFile} {retail.NameOf(iconFile)}" : null,
        });
    }

    // Weapons and shoulders: one rigid model a hand or a shoulder, with its texture
    private void ImportRigidModels(DisplaySpec spec, uint[] modelResources, int[] materialResources,
        string[] modelNames, string[] modelTextures, List<uint> retailModels, List<uint> retailTextures)
    {
        var folder = spec.Slot == "weapon" ? "Weapon" : "Shoulder";
        // 3.3.5 shoulders are two models, [0] left and [1] right; retail keeps both in one model resource and
        // tells them apart by ComponentModelFileData.PositionIndex (0 left, 1 right).
        var slots = spec.Slot == "shoulder" ? 2 : 1;
        for (var slot = 0; slot < slots; ++slot)
        {
            var candidates = Probe.ModelFiles(retail, modelResources[slot]).Select(model => model.fdid).ToList();
            if (spec.Slot == "shoulder")
            {
                var components = retail.Table("ComponentModelFileData");
                candidates = candidates.Where(fdid => components.TryGetValue((int)fdid, out var c)
                    && (sbyte)c["PositionIndex"] == slot && (sbyte)c["RaceID"] == 0).ToList();
            }
            if (candidates.Count == 0)
                throw new Exception(
                    $"display {spec.Id}: retail display {spec.RetailDisplay} has no model for slot {slot}");
            var textures = Probe.TextureFiles(retail, materialResources[slot]).Select(texture => texture.fdid).ToList();
            if (textures.Count == 0)
                throw new Exception(
                    $"display {spec.Id}: retail display {spec.RetailDisplay} has no texture for slot {slot}");
            modelNames[slot] = ConvertModel(candidates[0], folder) + ".mdx";
            modelTextures[slot] = CopyTexture(textures[0], $@"Item\ObjectComponents\{folder}\");
            retailModels.Add(candidates[0]);
            retailTextures.Add(textures[0]);
        }
    }

    // A helmet: one model a race and gender (the client adds _HuM, _OrF... to the display's model name), and one
    // texture. Retail's file names already carry 3.3.5's suffixes (helm_..._hum.m2).
    private void ImportHead(DisplaySpec spec, uint modelResource, int materialResource, string[] modelNames,
        string[] modelTextures, List<uint> retailModels, List<uint> retailTextures)
    {
        var components = retail.Table("ComponentModelFileData");
        string baseName = null;
        var found = new HashSet<string>();
        foreach (var (fdid, _) in Probe.ModelFiles(retail, modelResource))
        {
            if (!components.TryGetValue((int)fdid, out var component))
                continue;
            var race = (int)(sbyte)component["RaceID"];
            var gender = (int)(sbyte)component["GenderIndex"];
            if (!ClassicRaces.TryGetValue(race, out var suffix) || gender is not (0 or 1))
                continue;
            var name = ConvertModel(fdid, "Head");
            var expected = "_" + suffix + (gender == 0 ? "m" : "f");
            if (!name.EndsWith(expected, StringComparison.OrdinalIgnoreCase))
            {
                Fail($"{name}: race {race} gender {gender} should end with {expected}");
                continue;
            }
            var stem = name[..^expected.Length];
            if (baseName != null && !baseName.Equals(stem, StringComparison.OrdinalIgnoreCase))
                Fail($"display {spec.Id}: head models of two names, {baseName} and {stem}");
            baseName ??= stem;
            found.Add(suffix + (gender == 0 ? "M" : "F"));
            retailModels.Add(fdid);
        }
        if (baseName == null)
            throw new Exception($"display {spec.Id}: retail display {spec.RetailDisplay} has no head model");
        var missing = ClassicRaces.Values.SelectMany(race => new[] { race + "M", race + "F" })
            .Where(code => !found.Contains(code)).ToList();
        if (missing.Count > 0)
            report.Add($"  WARNING display {spec.Id}: no head model for {string.Join(" ", missing)}"
                       + " (those characters show no helmet)");
        modelNames[0] = baseName + ".mdx";

        var texture = Probe.TextureFiles(retail, materialResource).Select(t => t.fdid).FirstOrDefault();
        if (texture == 0)
            throw new Exception($"display {spec.Id}: retail display {spec.RetailDisplay} has no helmet texture");
        modelTextures[0] = CopyTexture(texture, @"Item\ObjectComponents\Head\");
        retailTextures.Add(texture);
    }

    // A region's texture: each file of the material (unisex _U, or _M and _F) palettized under the region's folder,
    // named as retail names it without its suffix (and the FileDataID some retail names end with). Returns that name,
    // what the display's region field holds: the client adds _U, _M or _F.
    private string CopyBodyTexture(int materialId, string folder, List<uint> retailTextures)
    {
        var components = retail.Table("ComponentTextureFileData");
        var files = new List<(uint fdid, string retailName, string suffix)>();
        string baseName = null;
        foreach (var (fdid, _) in Probe.TextureFiles(retail, materialId))
        {
            var retailName = retail.NameOf(fdid) ?? throw new Exception($"texture {fdid} is not in the listfile");
            var stem = System.Text.RegularExpressions.Regex.Replace(Path.GetFileNameWithoutExtension(retailName),
                @"_\d+$", "");
            var gender = components.TryGetValue((int)fdid, out var component) ? (int)(sbyte)component["GenderIndex"] : 3;
            var match = System.Text.RegularExpressions.Regex.Match(stem, @"^(.*)_([umf])$",
                System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            var name = match.Success ? match.Groups[1].Value : stem;
            if (baseName != null && !baseName.Equals(name, StringComparison.OrdinalIgnoreCase))
                Fail($"material {materialId}: files of two names, {baseName} and {name}");
            baseName ??= name;
            files.Add((fdid, retailName, gender switch { 0 => "M", 1 => "F", _ => "U" }));
        }
        if (baseName == null)
            throw new Exception($"material {materialId} has no texture file");

        // Retail names some textures after a model's FileDataID (Midnight: 6756705_be_m_au_u_7443182), the same name
        // for other colours or pieces: a name already holding another file gets the material's id
        string PathOf(string name, string suffix) => $@"Item\TextureComponents\{folder}\{name}_{suffix}.blp";
        if (files.Any(file => bodyTextureOwners.TryGetValue(PathOf(baseName, file.suffix), out var owner)
                              && owner != file.fdid))
            baseName = $"{baseName}_{materialId}";

        foreach (var (fdid, retailName, suffix) in files)
        {
            var archivePath = PathOf(baseName, suffix);
            if (!bodyTextureOwners.TryAdd(archivePath, fdid))
                continue;
            var bytes = BodyTexture.ToPalettized(retail.Open(fdid), retailName, halveBodyTextures ? 128 : 256,
                out var description);
            WriteOutput(archivePath, bytes);
            report.Add($"  body {fdid} {retailName} -> {archivePath} ({description})");
            retailTextures.Add(fdid);
        }
        return baseName;
    }

    /// <summary>Copies a retail BLP to archivePrefix + its own name, returns that name without extension.</summary>
    private string CopyTexture(uint fdid, string archivePrefix)
    {
        if (copiedTextures.TryGetValue(fdid, out var done))
            return done;
        var retailName = retail.NameOf(fdid) ?? throw new Exception($"texture {fdid} is not in the listfile");
        var name = Path.GetFileNameWithoutExtension(retailName);
        var bytes = Blp.ForClassic(retail.Open(fdid), retailName, out var description);
        var archivePath = archivePrefix + name + ".blp";
        WriteOutput(archivePath, bytes);
        report.Add($"  texture {fdid} {retailName} -> {archivePath} ({description})");
        copiedTextures[fdid] = name;
        return name;
    }

    private void WriteOutput(string archivePath, byte[] bytes)
    {
        var path = Path.Combine(outputRoot, archivePath.Replace('\\', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllBytes(path, bytes);
    }

    /// <summary>Converts one retail model and its skins, returns its 3.3.5 name (no extension).</summary>
    private string ConvertModel(uint fdid, string folder)
    {
        if (convertedModels.TryGetValue(fdid, out var done))
            return done;
        var retailName = retail.NameOf(fdid) ?? throw new Exception($"model {fdid} is not in the listfile");
        var name = Path.GetFileNameWithoutExtension(retailName);
        var model = new RetailM2(retail.Open(fdid));
        report.Add($"  model {fdid} {retailName}: M2 version {model.Version},"
                   + $" chunks {string.Join(" ", model.Chunks.Keys)}");

        foreach (var tag in new[] { "SKID", "BFID" })
            if (model.Chunks.ContainsKey(tag))
                Fail($"{retailName}: {tag} (external skeleton/bones) is not supported");
        // Only the first Stand is kept (ClassicM2.KeepFirstStand): its keyframes must be inside the model
        var external = model.ExternalSequences();
        if (external.Contains(((ushort)0, (ushort)0)))
            Fail($"{retailName}: Stand keeps its keyframes in an .anim file, not supported yet");
        var (particles, _) = model.Array(0x128);
        if (particles > 0)
            report.Add($"  WARNING {name}: {particles} particle emitter(s) dropped"
                       + " (MultiConverter does not convert Legion+ particles)");
        var (ribbons, _) = model.Array(0x120);
        if (ribbons > 0)
            report.Add($"  WARNING {name}: {ribbons} ribbon emitter(s) kept as they are (untested)");

        // Work folder: the retail file as MultiConverter wants it, and one .skin per view under its 3.3.5 name
        var dir = Path.Combine(workDir, name);
        if (Directory.Exists(dir))
            Directory.Delete(dir, true);
        Directory.CreateDirectory(dir);
        var views = (int)model.ViewCount;
        if (model.SkinFileIds.Length < views)
            throw new Exception($"{retailName}: {views} views but {model.SkinFileIds.Length} skin files");
        var listfile = (Dictionary<uint, string>)typeof(MultiConverter.Lib.Listfile)
            .GetField("FiledataPair", BindingFlags.NonPublic | BindingFlags.Static)!.GetValue(null)!;
        var skinPaths = new List<string>();
        for (var view = 0; view < views; ++view)
        {
            var skinName = $"{name}{view:D2}.skin";
            var skinBytes = retail.Open(model.SkinFileIds[view]);
            File.WriteAllBytes(Path.Combine(dir, skinName), skinBytes);
            File.WriteAllBytes(Path.Combine(dir, $"{name}{view:D2}.retail.skin"), skinBytes);
            listfile[model.SkinFileIds[view]] = skinName;
            skinPaths.Add(Path.Combine(dir, skinName));
        }
        // LOD skins past the view count (SFID lists them after the views) are not read by 3.3.5
        for (var lod = views; lod < model.SkinFileIds.Length; ++lod)
            listfile[model.SkinFileIds[lod]] = $"{name}-lod{lod}.skin";

        var modelPath = Path.Combine(dir, name + ".m2");
        File.WriteAllBytes(modelPath, model.ForMultiConverter());
        File.WriteAllBytes(Path.Combine(dir, name + ".retail.m2"), retail.Open(fdid));

        var previousDirectory = Environment.CurrentDirectory;
        var previousOut = Console.Out;
        var converterLog = new StringWriter();
        try
        {
            Environment.CurrentDirectory = dir;
            Console.SetOut(converterLog);
            var converter = new M2Converter(modelPath, false);
            if (!converter.Fix())
                throw new Exception($"{retailName}: MultiConverter found nothing to convert");
            converter.Save();
        }
        finally
        {
            Console.SetOut(previousOut);
            Environment.CurrentDirectory = previousDirectory;
        }
        File.WriteAllText(Path.Combine(dir, "multiconverter.log"), converterLog.ToString());

        // Our pass: 3.3.5 texture names for what the model hardcodes, and only the global flags 3.3.5 knows
        var converted = new ClassicM2(File.ReadAllBytes(modelPath));
        converted.RestoreName(model.Name);
        converted.RestoreGlobalLoops(model.GlobalLoops());
        converted.MaskGlobalFlags();
        var droppedSequences = converted.KeepFirstStand();
        if (droppedSequences > 0)
            report.Add($"  {name}: kept Stand only, {droppedSequences} character animation sequences dropped"
                       + " (no item plays them)");
        var textureCount = (int)converted.Array(0x50).count;
        var names = new List<string>();
        for (var i = 0; i < textureCount; ++i)
        {
            var textureId = i < model.TextureFileIds.Length ? model.TextureFileIds[i] : 0;
            if (converted.TextureType(i) != 0)
                names.Add("");
            else if (textureId == 0)
                throw new Exception($"{retailName}: texture {i} is hardcoded but TXID names no file");
            else
            {
                var prefix = $@"Item\ObjectComponents\{folder}\Retail\";
                names.Add(prefix + CopyTexture(textureId, prefix) + ".blp");
            }
        }
        converted.NameTextures(names);

        var skins = skinPaths.Select(File.ReadAllBytes).ToList();
        var problems = converted.Validate(skins);
        foreach (var problem in problems)
            Fail($"{name}: {problem}");
        report.Add($"  -> Item\\ObjectComponents\\{folder}\\{name}.m2 + {views} skin(s), version 264, "
                   + (problems.Count == 0 ? "structure checked" : $"{problems.Count} problem(s)"));

        WriteOutput($@"Item\ObjectComponents\{folder}\{name}.m2", converted.Data);
        for (var view = 0; view < views; ++view)
            WriteOutput($@"Item\ObjectComponents\{folder}\{name}{view:D2}.skin", skins[view]);
        convertedModels[fdid] = name;
        return name;
    }

    private static string Quote(string value) => "'" + (value ?? "").Replace("'", "''") + "'";

    private static string BuildSql(Manifest manifest)
    {
        var sql = new StringBuilder();
        sql.AppendLine("-- Generated by localTools/retailImport (RetailImport import) from");
        sql.AppendLine("-- localTools/retailImport/items.json -- do not edit by hand.");
        sql.AppendLine("--");
        sql.AppendLine("-- Test items wearing looks imported from the retail client");
        sql.AppendLine("-- (localTools/retailImport/README.md).");
        sql.AppendLine("-- Each copies a stock item's stats and shows a retail display. Their entries are below 65536");
        sql.AppendLine("-- and already in the client's Item.dbc with no template on the server before these;");
        sql.AppendLine("-- localTools/patchSinisterStrike.ps1 gives those Item.dbc rows the class, slot and display");
        sql.AppendLine("-- written here.");
        var entries = string.Join(", ", manifest.Items.Select(item => item.Entry));
        sql.AppendLine($"DELETE FROM `item_template_locale` WHERE `ID` IN ({entries});");
        sql.AppendLine($"DELETE FROM `item_template` WHERE `entry` IN ({entries});");
        sql.AppendLine();
        sql.AppendLine("DROP TEMPORARY TABLE IF EXISTS `tmp_retail_item`;");
        sql.AppendLine("CREATE TEMPORARY TABLE `tmp_retail_item` LIKE `item_template`;");
        foreach (var item in manifest.Items)
        {
            sql.AppendLine();
            sql.AppendLine($"-- {item.Name}: stats of item {item.StatsFrom}, display {item.Display}");
            sql.AppendLine(
                $"INSERT INTO `tmp_retail_item` SELECT * FROM `item_template` WHERE `entry` = {item.StatsFrom};");
            sql.AppendLine("UPDATE `tmp_retail_item` SET");
            sql.AppendLine($"    `entry` = {item.Entry},");
            sql.AppendLine($"    `name` = {Quote(item.Name)},");
            // What the server enforces from Item.dbc (DBC.EnforceItemAttributes), identical to the patched row
            sql.AppendLine($"    `class` = {item.Class},");
            sql.AppendLine($"    `subclass` = {item.Subclass},");
            sql.AppendLine("    `SoundOverrideSubclass` = -1,");
            sql.AppendLine($"    `Material` = {item.Material},");
            sql.AppendLine($"    `displayid` = {item.Display},");
            sql.AppendLine($"    `InventoryType` = {item.InventoryType},");
            sql.AppendLine($"    `sheath` = {item.Sheath},");
            sql.AppendLine($"    `description` = {Quote(item.Description)},");
            sql.AppendLine("    `itemset` = 0,");
            sql.AppendLine("    `VerifiedBuild` = NULL;");
            sql.AppendLine("INSERT INTO `item_template` SELECT * FROM `tmp_retail_item`;");
            sql.AppendLine("DELETE FROM `tmp_retail_item`;");
        }
        sql.AppendLine();
        sql.AppendLine("DROP TEMPORARY TABLE `tmp_retail_item`;");
        sql.AppendLine();
        sql.AppendLine(
            "INSERT INTO `item_template_locale` (`ID`, `locale`, `Name`, `Description`, `VerifiedBuild`) VALUES");
        sql.AppendLine(string.Join(",\n", manifest.Items.Select(item =>
            $"({item.Entry}, 'frFR', {Quote(item.NameFr)}, {Quote(item.DescriptionFr)}, NULL)")) + ";");
        return sql.ToString().Replace("\r\n", "\n");
    }
}
