"""Generates the localized boss name table used by the dungeon progress tracker.

Reads DungeonEncounter.dbc from the WotLK client (the locale archives hold the translated names) and writes
clientPatcher/interface/Interface/FrameXML/DungeonTrackerNames.lua, mapping encounter id -> name. The server
sends encounter ids, so the client shows them in its own language.

Usage: python generateEncounterNames.py [--dbc <DungeonEncounter.dbc>] [--locale frFR]
"""
import argparse
import os
import struct

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUTPUT = os.path.join(REPO, 'clientPatcher', 'interface', 'Interface', 'FrameXML', 'DungeonTrackerNames.lua')
LOCALE_INDEX = {'enUS': 0, 'koKR': 1, 'frFR': 2, 'deDE': 3, 'zhCN': 4, 'zhTW': 5, 'esES': 6, 'esMX': 7, 'ruRU': 8}
NAME_FIELD = 5  # DungeonEncounter.dbc: ID, MapID, Difficulty, OrderIndex, Bit, Name_Lang[16] + flags, ...


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dbc', default=os.path.join(os.environ.get('TEMP', '.'), 'claude', 'dbc',
                                                      'DungeonEncounter.dbc'))
    parser.add_argument('--locale', default='frFR')
    args = parser.parse_args()

    data = open(args.dbc, 'rb').read()
    assert data[:4] == b'WDBC', 'not a DBC file'
    count, fields, record_size, string_size = struct.unpack_from('<4I', data, 4)
    strings_at = 20 + count * record_size

    def string_at(offset):
        end = data.index(b'\0', strings_at + offset)
        return data[strings_at + offset:end].decode('utf8', 'replace')

    names = {}
    for index in range(count):
        record = struct.unpack_from('<%dI' % fields, data, 20 + index * record_size)
        offset = record[NAME_FIELD + LOCALE_INDEX[args.locale]] or record[NAME_FIELD]
        name = string_at(offset) if offset else ''
        if name:
            names[record[0]] = name

    lines = ['-- Generated by localTools/interface/generateEncounterNames.py from the client DungeonEncounter.dbc.',
             '-- Encounter id -> boss name, in the client language. Do not edit.',
             'DungeonTrackerNames = {']
    for encounter_id, name in sorted(names.items()):
        lines.append('    [%d] = "%s",' % (encounter_id, name.replace('\\', '\\\\').replace('"', '\\"')))
    lines.append('}')
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, 'w', encoding='utf-8', newline='\n') as file:
        file.write('\n'.join(lines) + '\n')
    print('Wrote', len(names), 'encounter names to', OUTPUT)


if __name__ == '__main__':
    main()
