"""Writes the custom classes' Dungeon Finder roles for the client extension DLL (awesome_wotlk).

    python writeDllClassRoles.py [--awesome-wotlk <repo>]

Wow.exe takes a class's Dungeon Finder roles from a static table, one byte per class id, that has no room past id 12.
The DLL (src/AwesomeWotlkLib/CustomClassRoles.cpp) keeps its own copy with room for every class id and points the
five instructions that read the table at it. This writes the custom classes' bytes into
src/AwesomeWotlkLib/CustomClassRoles.generated.h, from classes.json: the roles each class may queue as, plus leader.
localTools/buildClientDll.ps1 runs it before every DLL build, so classes.json stays the one place roles are set.
"""
import argparse
import json
import os

from buildCustomClasses import DEFINITIONS, LFG_ROLE_LEADER, role_mask

DEFAULT_AWESOME_WOTLK = r'C:\Users\alexi\Documents\GitHub\awesome_wotlk'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--awesome-wotlk', default=DEFAULT_AWESOME_WOTLK)
    args = parser.parse_args()

    definitions = json.load(open(DEFINITIONS, encoding='utf8'))['classes']
    lines = [
        '#pragma once',
        '// Generated by localTools/customClasses/writeDllClassRoles.py (TestWoW) from classes.json. Do not edit.',
        '// Each custom class id and its Dungeon Finder roles: 1 leader, 2 tank, 4 healer, 8 damage.',
        '#include <cstdint>',
        '',
        'namespace CustomClassRoles {',
        'struct ClassRole { uint8_t classId; uint8_t roles; };',
        'constexpr ClassRole Generated[] = {',
    ]
    for definition in sorted(definitions, key=lambda entry: entry['id']):
        roles = LFG_ROLE_LEADER | role_mask(definition)
        lines.append(f"    {{ {definition['id']}, {roles} }},   // {definition['token']}: "
                     f"{', '.join(sorted(definition.get('roles', ['damage'])))}")
    lines += ['};', '}', '']
    target = os.path.join(args.awesome_wotlk, 'src', 'AwesomeWotlkLib', 'CustomClassRoles.generated.h')
    text = '\n'.join(lines)
    if not os.path.exists(target) or open(target, encoding='utf8').read() != text:
        with open(target, 'w', encoding='utf8', newline='\n') as output:
            output.write(text)
    print(f'Dungeon Finder roles for the DLL: {len(definitions)} custom classes -> {target}')


if __name__ == '__main__':
    main()
